### ISSUE TITLE
Address tag button has degraded functionality

### ISSUE THREAD

**Issue by zyphlar** [MarcusWolschon/osmeditor4android#1446] opened 2021-08-30 20:53 UTC
## Vespucci Version
16.0.0 BETA 2

## Download source
Google Play

## Device (Manufacturer and Model)
Samsung Galaxy S21

## Android Version 
11

## Behaviour/Symptoms
When clicking the `[42]` icon to insert address tags into an element, only `addr:street` and `addr:city` is added. If I want to add a house number to an element, I very often have to click on the Details tab and type `addr:` to select `addr:housenumber`

## Expected Behaviour
When clicking the `[42]` icon to insert address tags into an element, the previous behavior of adding tag fields for `addr:housenumber`, `addr:street`, and ideally `addr:city`, `addr:state`, `addr:postcode`, and maybe even a blank `addr:unit` is added.

## How to recreate
1. Create a new element near a street which doesn't have many nearby addresses (or far from a street, so that normal address interpolation doesn't take over)
2. Press the `[42]` button to note its address
3. Observe that unless near a major heavily-mapped roadway where interpolation is possible, the only tags created are `addr:street` and `addr:city`

## Any other potentially relevant information
Tested on the West coast, USA

**Comment by simonpoole** [comment] 2021-08-30 21:27
There haven't been relevant changes for 16.0 so this is likely an issue that goes back to 15.2 or earlier.

**Comment by zyphlar** [comment] 2021-08-30 21:31
Yeah it's been annoying for at least a few months now, I keep updating hoping that it gets better. It seems like interpolation got better... where it works. And just completely died where it doesn't work.

**Comment by simonpoole** [comment] 2021-08-31 06:54
To narrow this down a bit, is the issue simply that the blank fields are not shown in the property editor and need to be added manually in the details tab (this is not actually caused by changes to the address interpolation code, but needs to be fixed), but once you've added two addresses it then works?

**Comment by zyphlar** [comment] 2021-08-31 07:07
I think you're correct, I'm mentioning interpolation only because the bug doesn't appear in cases where Vespucci is trying to guess the housenumber. Essentially the bug is, when Vespucci doesn't have a good guess as to the housenumber it gives up and does not create sufficient empty address fields for manual entry, which causes frustration when address tags then need to be manually typed out on the details page.

**Comment by zyphlar** [comment] 2021-08-31 07:15
If I'm guessing at programmer intent, it seems like the "42" button was maybe created as an interpolation button -- I've never considered adding a start and end address point and then inserting between them, that's just not how I map -- but I'm trying to use it as an "add address tags" button, which is nearly useless in an umapped area. I had this expectation because of how useful the "ABC+" button is at setting up common fields for amenities.

**Comment by zyphlar** [comment] 2021-08-31 07:18
Ooh the plot thickens! The long-press alt text for the "42" button does say "add address tags." Which it does a somewhat bad job at. So maybe I'm not so crazy after all.

**Comment by simonpoole** [comment] 2021-08-31 07:31
A more general note, 15.2 added a dedicated address mode which made the add address node etc functionality available outside of the property editor again, see http://vespucci.io/help/en/15.2.0%20Release%20notes/ .

The issue with the (missing) empty fields in the property editor is due to an interaction with the auto applying of presets, I'm working on a fix for that.

**Comment by zyphlar** [comment] 2021-08-31 07:41
Sweet! Thanks for your attention to the issue. I couldn't tell if there was already a bug report for it and as you say it's one of those pernicious little things that seems like it should work but sometimes doesn't.

**Comment by simonpoole** [comment] 2021-09-01 10:22
Addressed in https://github.com/MarcusWolschon/osmeditor4android/pull/1447

The code is now more aggressive about adding "missing" fields (that is either such that are in the geocontext config, or explicitly set in the preferences, see http://vespucci.io/help/en/Advanced%20preferences/#data-and-editing-settings) and may need some further tuning.

**Closed by simonpoole** 2021-09-01 10:22 UTC
Labels: Defect, Medium
