### ISSUE TITLE
Beep when I press and hold the screen...

### ISSUE THREAD

**Issue by Ivans-Git** [MarcusWolschon/osmeditor4android#1279] opened 2020-11-10 20:55 UTC
When I press and hold the screen I hear a very unpleasant beep that even when the mobile is silent it is deactivated !!! sometimes I accidentally hit it and the scares it gives me are very strong...

**Comment by simonpoole** [comment] 2020-11-10 21:10
The 1st time you did that you got a tip displayed what the cause is (trying to use a long press in "simple mode"). In 15.1 the volume of the beep is configurable, aka volume 0 will turn in off, see https://github.com/MarcusWolschon/osmeditor4android/commit/113b02cb1b234680238c774a524dd43076b66592

I would suggest moving to the 15.1 beta if you find it so disturbing.

**Closed by simonpoole** 2020-11-10 21:10 UTC

**Comment by Ivans-Git** [comment] 2020-11-19 12:17
> La primera vez que lo hizo, se le mostró un consejo sobre la causa (tratando de usar una pulsación larga en "modo simple"). En 15.1, el volumen del pitido es configurable, también conocido como el volumen 0 se apagará, consulte [113b02c](https://github.com/MarcusWolschon/osmeditor4android/commit/113b02cb1b234680238c774a524dd43076b66592)
> 
> Sugeriría pasar a la versión beta 15.1 si lo encuentra tan perturbador.

I only ask that if the volume of the phone is muted, it does not ring, also in the settings I do not see anything to deactivate it...

**Comment by simonpoole** [comment] 2020-11-19 12:44
You need to install 15.1 for the setting to be available.
