### ISSUE TITLE
Text radio button not selected with text/no text as value in OpeningHoursFragment

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#872] opened 2019-03-10 20:34 UTC
Description:
---

See issue description

Device info:
---
<table>
<tr><td>App version</td><td>12.1.4.0</td></tr>
<tr><td>App version code</td><td>1004</td></tr>
<tr><td>Android build version</td><td>2866453cc2</td></tr>
<tr><td>Android release version</td><td>8.1.0</td></tr>
<tr><td>Android SDK version</td><td>27</td></tr>
<tr><td>Android build ID</td><td>lineage_tissot-userdebug 8.1.0 OPM7.181205.001 2866453cc2</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>tissot</td></tr>
<tr><td>Device model</td><td>Mi A1</td></tr>
<tr><td>Device product name</td><td>lineage_tissot</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>scai</td></tr>
</table>

**Comment by scaidermern** [comment] 2019-03-10 20:35
This is the issue from https://github.com/simonpoole/beautified-JOSM-preset/issues/139.

**Comment by simonpoole** [comment] 2019-03-10 21:16
What is displayed when you click two times in the text field? You should be getting a drop down with no, yes and potentially some extra values. And: are you using a custom preset?

**Comment by scaidermern** [comment] 2019-03-11 12:43
Maybe it becomes clearer with this video:

![video_2019-03-11_13-40-14](https://user-images.githubusercontent.com/1040784/54124675-5c8f5a00-4403-11e9-83d8-da73d85ecd64.gif)

As you can see the save button is disabled when text has been selected from the radio button. It doesn't matter which current value the `fee` tag has (a value containing valid opening hours behaves the same).

I don't use custom presets and never have.

**Comment by simonpoole** [comment] 2019-03-11 12:55
> 
> Maybe it becomes clearer with this video:
> 
Not really :-/.

As to how it should work:

![fee](https://user-images.githubusercontent.com/1011860/54125419-38347d00-4405-11e9-8ca9-32577dfe6c27.gif)

 Note the "Save" button will only activate if you've change something.

**Comment by scaidermern** [comment] 2019-03-11 13:10
Oh. There has been a misunderstanding on my part. I didn't recognize the gray bar on top as an input field since it differs from the other UI in vespucci. Upon tapping on the gray bar a drop down menu appears.

Sorry, PEBCAK. You can close the issue.

**Comment by simonpoole** [comment] 2019-03-11 13:16
I think the misunderstanding might be avoided by renaming "Text values" to "Text mode"? 

The OpeningHoursFragment is actually a separate project and there are a couple of small styling differences (which probably should fixed).

**Closed** 2019-03-11 13:23 UTC
Labels: Needs clarification

**Comment by scaidermern** [comment] 2019-03-11 13:38
The cause of this misunderstanding is probably the missing dialog title. All other radio button dialogs do have a large title whereas this one doesn't. I think I misinterpreted the "Fee" from the gray bar as dialog title and expected some other input field to appear. Adding a proper dialog title will make the input field more obvious.

**Comment by georg-d** [comment] 2019-05-13 11:18
@simonpoole As this user interface design is obviously misleading not only one user IMHO it makes sense to change it. I've the impression already 2 out of these 4 changes shall be sufficient - whichever are technically most easy to implement.
1. Adding a dialog title above the 3rd party component as @scaidermern suggested. This shall look like for other vespucci dialogs like e.g. surface. 
2. Initially (i.e. if key has no value yet) do not show the name of the key (this appears like a dialog title) but empty the text field or set a text like "enter text here"?
3. Add a lable before the text field, e.g. "Value: "
4. Changing the sequence so that first, the radio buttons and then the text field appears
