### ISSUE TITLE
[Vespucci 0.9.9.0.1266 F-Droid][Sony Xperia Sp C5303][Android 4.3] geolocated pics failed 

### ISSUE THREAD

**Issue by Tranquille89** [MarcusWolschon/osmeditor4android#569] opened 2017-06-15 14:14 UTC
Hello, 

If i take geolocated pics from Vespucci, i have broken pics, none image,  none geocoding and none "pics icone" on photo overlay. 

Geolocated pics taken with the photo Android app, it's ok.

Tranquille 
French Osm contributor

**Comment by simonpoole** [comment] 2017-06-15 15:18
@Tranquille89 which photo app are you using?

**Comment by simonpoole** [comment] 2017-06-22 18:41
Still waiting for input .....

**Comment by Tranquille89** [comment] 2017-06-27 17:16
Sorry for waiting. Il use standard Android app started manualy ans it's good.
If started since vespucci, i make broken file 0octet.
I gonna search your opencamera app and post After test ^^

**Comment by simonpoole** [comment] 2017-06-29 22:08
@Tranquille89 opencamera is simply known to work. We had to make fairly significant changes to the starting the camera code when we switched to building agains SDK 24 (Android 7,0) and this may be causing your problem.

**Comment by simonpoole** [comment] 2017-07-08 06:09
@Tranquille89 any news?

**Comment by spaetz** [comment] 2017-08-01 11:31
Hi there, not sure if it's exactly the same isssue, but pictures taken from Vespucci using the stock camera (which is from the vendor Bq) show up as broken and clixking on them yields a file not found error (see screenshot). This is on a nougat device 7.1.1, and Vespucci has storage permission granted.

**Comment by spaetz** [comment] 2017-08-01 11:34
Sorry, can't attach screenshot. It says Cannot access photo /storage/A5DE-6245/DCIM/image.xxx.jpg
Again storage permissions are granted to Vespucchi. Will try out OpenCamera next.

**Comment by simonpoole** [comment] 2017-08-01 12:28
Can you access the image directly (in a file browser navigate to the Vespucci/Pictures folder)?

**Comment by spaetz** [comment] 2017-08-01 20:34
Yes, I can see those from a file browser directly. They are saved in /storage/emulated/0/Vespucci/Pictures though and not in /storage/64EB-1907/DCIM as the error message suggests.
-- 
Sent from mobile device. Please excuse brevity and tpyos.

**Comment by simonpoole** [comment] 2017-08-02 07:26
Weird, I'll try and reproduce locally.

**Comment by simonpoole** [comment] 2017-08-02 10:43
OK, I understand half of the issue, the unable to access the file and the "wrong" filename are due to the logic that determines which menu item references which photo getting out of step because Uri generation is failing on photos that are not in the Vespucci folder.

The other 50% is trying to see if we can avoid the issue in the first place (that we can't access the image files via an intent when they are not in the Vespucci folder), but I suspect that is not possible, but will make another attempt.

**Comment by simonpoole** [comment] 2017-08-02 12:08
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/cc3de971d14e0036692fec2d05fe94e1c20c1b0a we may have an update going out this week, I'll ask @MarcusWolschon to include a build with this fix instead of the intended build.

**Closed by simonpoole** 2017-08-02 12:08 UTC
Labels: Needs clarification
