### ISSUE TITLE
Allowed changing background imagery even when way is selected

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1928] opened 2022-11-04 21:46 UTC
During delicate editing operations, when items are selected, access to the layers menu disappears:
![Screenshot_20221104-164020_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/200079369-ffdc47ac-4afe-4ae0-b214-7ef6af548c87.jpg)

We must exit our selection in order to regain access to the three bar layers menu, in the upper right:

![Screenshot_20221104-164055_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/200079395-35d96986-c66b-4d7d-aa90-0653ca83943b.jpg)

Certainly background layers are independent of what other operations we are doing. Therefore they should still be accessible to be changed even when we are editing a selection.

That the  Data layer is also inside the same menu, and therefore the whole menu must be turned off, is unfortunate. Perhaps the Data layer could be grayed out if necessary so there would be no fear of manipulation, but at least we could still be able to change the Background layer back and forth without having to exit our selection each time. Thank you.

**Comment by simonpoole** [comment] 2022-11-05 08:41
Duplicate of https://github.com/MarcusWolschon/osmeditor4android/issues/1772

**Closed by simonpoole** 2022-11-05 08:41 UTC
Labels: Enhancement
