### ISSUE TITLE
No matching activity for osm hyperlinks

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1100] opened 2020-02-18 06:43 UTC
in a browser, press a hyperlink and from a menu choose Share the link.

Vespucci should appear as one of the choices of a destination app to accept the intent. However it doesn't. I'm talking about links with the openstreetmap website in the title, like this: https://www.openstreetmap.org/?mlat=30.374444&mlon=114.266222&zoom=15

intent:#Intent;action=android.intent.action.SEND;type=text/plain;launchFlags=0xb080000;S.android.intent.extra.TEXT=https%3A%2F%2Fwww.openstreetmap.org%2F%3Fmlat%3D30.374444%26mlon%3D114.266222%26zoom%3D15%26layers%3DM;i.org.chromium.chrome.extra.TASK_ID=624;end

Version: current one on Google Play.

**Comment by simonpoole** [comment] 2020-02-18 07:00
Duplicate of https://github.com/MarcusWolschon/osmeditor4android/issues/844

**Closed by simonpoole** 2020-02-18 07:00 UTC
