### ISSUE TITLE
It is easy to create untagged ways

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#1332] opened 2021-02-02 17:56 UTC
For creating way (in default mode): 

- press big plus button
- select "create way"
- tap through screen to create it
- press back arrow at top left

Note that way is created, user is not going into tag selection mode and way is not marked in a validator pink.

There is also no clear warning  on upload screen (despite that there is enough space to display it).

Maybe going into tag selection mode in such case would be better? Or at least keeping way selected?

Note that in comparison ending way creation by clicking on big button you go into tag selection mode, after exiting it way (or node) remains selected, so selection is much sticker.

**Comment by matkoniecz** [comment] 2021-02-02 17:59
Spotted during attempt to create guide for complete newbies - I am aware about http://vespucci.io/help/en/Introduction/#first-time-use but it seems to be too thorough and not enough idiotproof.

For example in downloading OSM Data for first time use it is not needed to discuss all download modes.

(if you would consider content removal there as improving this first time use and moving it elsewhere I can do this)

**Comment by simonpoole** [comment] 2021-02-02 18:15
Pls don't conflate two different issues/question  in the same isdue.

In any case I can't recreate the issue: both the validation highlighting gets applied and the issue is highlighted in the upload changes list.

Which version are you seeing the issue on?

**Comment by matkoniecz** [comment] 2021-02-02 18:44
> Which version are you seeing the issue on?

15.1.6

> the issue is highlighted in the upload changes list.

by red icon that is quite easy to miss, but this one is hardest to fix and mentioned mostly to describe that also on this stage missing that is easy

> Pls don't conflate two different issues/questions in the same issue.

I though that multiple mildly-related issues about single thing would be easier. If any part will be fixed - this can be closed and I can create new one for remaining parts (or multiple issues).

**Comment by simonpoole** [comment] 2021-02-03 08:15
This seems to be 15.1 specific and is fixed in 15.2 (can't put a finger on a specific commit right now).

**Closed by simonpoole** 2021-02-03 08:15 UTC
Labels: Needs clarification
