### ISSUE TITLE
Copy-n-pasting shadows

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1406] opened 2021-06-05 18:29 UTC
Description:
---

Twice now, I have caught Vespucci, long after I have moved on, having pasted tags and their values from an earlier edit on an object. I believe it is happening while I am pasting a value from an external source, the tags then get added or clobber those on the object, without my noticing them.

Device info:
---
<table>
<tr><td>App version</td><td>15.2.2.0</td></tr>
<tr><td>App version code</td><td>1704</td></tr>
<tr><td>Android build version</td><td>7255357</td></tr>
<tr><td>Android release version</td><td>11</td></tr>
<tr><td>Android SDK version</td><td>30</td></tr>
<tr><td>Android build ID</td><td>RQ2A.210505.003</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Google</td></tr>
<tr><td>Device name</td><td>redfin</td></tr>
<tr><td>Device model</td><td>Pixel 5</td></tr>
<tr><td>Device product name</td><td>redfin</td></tr>
<tr><td>Device hardware name</td><td>redfin</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/treestryder"/>treestryder</A></td></tr>
</table>

**Comment by simonpoole** [comment] 2021-06-07 12:18
> ## Description:
> 
> Twice now, I have caught Vespucci, long after I have moved on, having pasted tags and their values from an earlier edit on an object. I believe it is happening while I am pasting a value from an external source, the tags then get added or clobber those on the object, without my noticing them.

"external source" ... can you detail what you are actually doing? This should likely be reproducible.

**Comment by treestryder** [comment] 2021-06-11 19:10
Thanks to Vespucci, where ever I might be, I am able to quickly edit nearly anything (I avoid creating areas in Vespucci, because of early pain points that have likely been resolved or my own misunderstanding). 

I'll have to pay more attention to my edits and their subsequent results. Feel free to close this, until I have something more concrete. Just wanted to make you aware something weird is happening, while I'm doing nothing out of my ordinary.

**Comment by simonpoole** [comment] 2021-06-14 15:38
I was unable to recreate this, that's why some indication of what you were doing would be helpful. 

Note that there are two different paste functions "Paste" will paste from the Vespucci internal tag clipboard, "Paste from clipboard" from the Android system clipboard. THe later is only available in the PropertyEditor.

**Comment by simonpoole** [comment] 2021-08-16 10:14
Closing as stale.

**Closed by simonpoole** 2021-08-16 10:14 UTC
Labels: Needs clarification
