### ISSUE TITLE
default="yes" in a preset for a <check> element is not working

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1260] opened 2020-10-20 13:45 UTC
## Vespucci Version
15.0.5

## Download source
Google Play Store

## Device (Manufacturer and Model)
Huawei Honor 7x

## Android Version 
9.1.0

## Behaviour/Symptoms
I wanted to create a personal preset file with some "shortcut" items with `<check>` elements with default values "yes" – they should be checked by default.

Example: `<check key="payment:coins" text="Coins" text_context="payment" default="yes"/>`

But it doesn't seem to work. I tried also default="true", value_on="yes", but I found no way to make it work. Is it possible that it's a bug or am I missing something?

My only workaround was to use a `<multiselect>` (or `<combo>`) element instead – there it is working, e.g.:
`<multiselect key="payment:coins" text="Coins" text_context="payment" values="yes" display_values="Yes" default="yes"/>`

But then it is not possible to set a "no" value as with a `<check>` element in a easy way ... or you have to set values="yes;no", which consumes some space on the screen.

The[ tutorial page](http://vespucci.io/tutorials/presets/)  says, that the default attribute is supported with `<check>` elements.

## Expected Behaviour
default="yes" should work with `<check>` elements (also in  a `<checkgroup>` of course)

## How to recreate
obvious

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information
no

**Comment by simonpoole** [comment] 2020-10-21 08:53
Automatically applying defaults is very very very controversial, I need to check the code, but I believe that we don't do it in this case.

The alternative is to make a custom preset and simply set the value (aka a "fixed" value tag)

**Comment by jajajaneeneenee** [comment] 2020-10-23 00:08
What do you mean "you don't do it in this case"? You should not do anything. I made a custom preset by coding a xml file (that's what I meant by "I wanted to create a personal preset file") and simply wanted to use the default attribute with a check element. And the tutorial page says it would be supported. So this is the core of my question: Is this wrong or not? And why not perhaps ... (if not, either the tutorial page should be updated OR it should be fixed in Vespucci).

What should be controversial here? I don't understand. It's only a preset for my personal use with some "shortcut" items with default fields (in my case for entrances and for public telephones in our city which always accept coins ... with some very rare exceptions) and I ask why the default attribute don't works as expected with check elements. And I think at other users who do perhaps try to do the same thing and also rely on the tutorial page as I did ...

Using a fixed key-value combination would be a workaround, but I wanted to keep the option to change the value quickly in special situations. 

But I found another, better workaround:

Instead of using a `<key key="xyz" value="xyz" />`(what you call a "fixed" value tag I guess)  I defined a bunch of such "shortcut items" (as I call them) only with **text elements with default values**, e.g.` <text key="payment:coins" default="yes" />` and defined another "master item" for that object with all fields (but **without** default values) which will match over the other "shortcut" items if they don't even contain ONE `<key key="xyx" value="xyz" />` element. 

Result: if I choose one of the "shortcut items" in Vespucci in the list of preset objects, the default values are assigned, but the other "master item" matches at once and is displayed for further editing ... e.g. with a `<check key="payment:coins" />` element which is already set to "yes" ... (and can be changed if necessary).

So, yes, a workaround is possible ... I only don't see a reason why the default attribute should not work with check elements, because it seems to work with ALL other kinds of elements. But perhaps I don't see the complete consequences.

It's perhaps not a high priority issue ...

**Comment by simonpoole** [comment] 2020-10-23 12:53
There are two separate issues here (sorry that I didn't notice the 1st sooner).

1. the default attribute can only have the values "on" and "off", see https://josm.openstreetmap.de/wiki/TaggingPresets (we simply stick to the JOSM specs for this).
2. when you start up the property editor, and the best matching preset is chosen, defaults are not applied (because as said this is considered controversial, and unexpected behaviour), you can however apply the preset manually and the value will get set.

**Comment by simonpoole** [comment] 2020-10-27 11:52
Closing ...

**Closed by simonpoole** 2020-10-27 11:52 UTC
Labels: Needs clarification

**Comment by jajajaneeneenee** [comment] 2020-11-01 15:42
> There are two separate issues here (sorry that I didn't notice the 1st sooner).
> 
>     1. the default attribute can only have the values "on" and "off", see https://josm.openstreetmap.de/wiki/TaggingPresets (we simply stick to the JOSM specs for this).

WOW! It is really such a no-brainer??? ... I never would have thought of that alone (I never came in touch with the JOSM specs and did not look there in this case –  I started to code some presets for Vespucci only ...). It would be GREAT to mention this in the Vespucci tutorial page, especially in this line:

![tutorial_page_line_to_improve](https://user-images.githubusercontent.com/48966999/97807167-927bf480-1c5f-11eb-88f2-548c6d2057fc.png)

You could write: _supported (use default="on" for "yes" and default="off" for "no")_  ... or something like that


And it was VERY surprising for me, that a line like this:
`<check key="test" default="yes"/>` or even this:
`<check key="test" value_on="yes" default="yes"/>`

results in:

![screenshot test=no](https://user-images.githubusercontent.com/48966999/97806589-af62f880-1c5c-11eb-92d0-f6900a153d86.jpg)

=> So, to complete your statement: any other value for default as "yes" seems to result in "no" (= off). Therefore, it should perhaps read: _The default attribute for a check element can only have the values "on" and "off", and any other value will result in "off". And the key values which will be set by default="on" and default="off" are "yes" and "no"._ [A little crazy, I think ... but OK ...]

> 
>     2. when you start up the property editor, and the best matching preset is chosen, defaults are not applied (because as said this is considered controversial, and unexpected behaviour), you can however apply the preset manually and the value will get set.

OK ... now it's clear what you meant with your short answer "Automatically applying defaults is very very very controversial". I was always talking about the second way of applying the preset, what you call a "manual apply". (Before I understood the word "automatically" in the way that it should be applied automatically, if a user taps on a preset "manually" – in the meaning of "default values should be applied automatically if a preset item with default values is choosen by the user". That's why I was very confused about your statement with the controversial thing ... you can understand "automatically applying" in different ways ...)
