### ISSUE TITLE
Unlocked map is dimmed

### ISSUE THREAD

**Issue by thany** [MarcusWolschon/osmeditor4android#2247] opened 2023-04-25 11:00 UTC
## Vespucci Version
18.1.5

## Download source
Google Play Store

## Device (Manufacturer and Model)
Sony Xperia 5IV

## Android Version 
13 (stock)

## Behaviour/Symptoms
When unlocking the map, and being zoomed in far enough, the whole map dims by about 50%. I'm not sure why this is being done, and it seems like it's not neccesary. I'm sure there's a reason for it, as something like that is quite obvious and doesn't occur by accident, but I thought I'd give it a mention anyway.

## Expected Behaviour
Don't dim the map if there isn't a good reason to do so. Or perhaps indicate somewhere why this is happening if there is a good reason for it.

## How to recreate
Zoom in to about 50 kilometres per screen width, or closer, and lock/unlock the map by tapping the padlock button.

## Crash dump submitted (no or yes + date)
no

**Comment by thany** [comment] 2023-04-25 11:01
After having created this issue, I was able to add these screenshots. Hopefully these show clearly what I'm talking about.

![Screenshot_20230425-125922](https://user-images.githubusercontent.com/152227/234257201-92da200a-960b-496c-965b-0eac579cc4d7.png)

![Screenshot_20230425-125918](https://user-images.githubusercontent.com/152227/234257211-2d4a64a8-9d0f-4601-b2e6-1c9c0e0e084b.png)

**Comment by simonpoole** [comment] 2023-04-25 11:03
Duplicate of https://github.com/MarcusWolschon/osmeditor4android/issues/2244

**Comment by thany** [comment] 2023-04-25 11:04
Is non-downloaded the reason? I see all map data, so...

**Comment by simonpoole** [comment] 2023-04-25 11:18
Sorry, thought you where on version 19 where there is actually a small issue with this. What you are seeing is normal behaviour, when the screen is unlocked only areas that have downloaded data are not dimmed, that -is- the indication that you can't edit there and need to download.

See http://vespucci.io/help/en/Introduction/#downloading-osm-data Note that the wording there is slightly wrong, as the behaviour can't be changed in the unlocked state, just for the locked state.

**Comment by thany** [comment] 2023-04-25 14:44
In that case, maybe a button in the middle of the screen "download this region" would suffice. Similar to how Organic Maps works.

Or, leave it locked if not downloaded, and ask to download once the user attempts to unlock for editing.

In general, I guess it's all about making features discoverable, isn't it. Onboarding instructions are helpful, but also easily dismissed, overlooked, or simply not understood. Making stuff naturally discoverable is difficult, but pays off more.

**Closed** 2023-04-25 16:04 UTC
Labels: Question

**Comment by thany** [comment] 2023-04-28 13:33
Hm, closed. So, this is not going to be improved then? Vespucci is already a pretty daunting app to use on the go, so I feel every little improvement to the UI helps, wouldn't you say?

**Comment by simonpoole** [comment] 2023-04-28 14:29
There is already a modal that tells you the small number of things you need to know to get started on 1st install. Adding yet a further modal just so that it too gets clicked away without being read would not seem to improve anything. Once you've downloaded data the meaning of the dimming is clear in any case.

**Comment by thany** [comment] 2023-04-28 16:39
First install may too long ago to remember those things. That's why an onboarding modal is not usually a good UI pattern, unless it _doesn't_ contain things you absolutely have to remember for next time.

Also nowhere did I suggest adding another modal. The button "download this region" could be unobstrusive and even dismissable. Or it could start downloading data automatically when on an unmetered (wifi) connection.
