### ISSUE TITLE
Problem with uploading data from Vespucci to OSM 

### ISSUE THREAD

**Issue by ReutGIS** [MarcusWolschon/osmeditor4android#1052] opened 2019-12-07 15:28 UTC
## Vespucci Version
14.0.9

## Download source
Google Play Store

## Device (Manufacturer and Model)
Xiaomi Redmi 5 Plus

## Android Version 
8.1.0
OPM1.171019.019

## Behaviour/Symptoms
Can't upload new data that was collected in specific area to OSM from app Vespucci, 
Error Message:

> Could not upload The API responded with an error, please save your date and report the issue:
> Placeholder id not found for way reference -7

## Expected Behaviour
Upload my collected data to OSM 

## How to recreate
not sure I understood the question. Try to upload new data to OSM  from Vespucci

## Crash dump submitted (no or yes + date)
no

**Comment by simonpoole** [comment] 2019-12-07 15:45
Please, before you do anything else, save the current data to a JOSM format file, and additionally export the changes to an OSC file. If possible attach the files to this ticket or send them to info@vespucci.io (once you've done that you can simply replace the data with fresh downloaded data (once I've figured out what has gone wrong I'll probably be able to fix the file and you can then load and upload them yourself).

Was there any special that happened before the issue? Do you have pan and zoom download turned on?

**Comment by ReutGIS** [comment] 2019-12-07 16:15
It's a student of mine who faced this problem. I have told him now to send you the filles

**Comment by ReutGIS** [comment] 2019-12-08 07:06
Hi, I can't send it to the following mail, it says it is blocked fro mrecieving emails.
is there any other way to send it to you?

**Comment by simonpoole** [comment] 2019-12-08 16:16
Attaching to this issue would be best.

**Comment by ReutGIS** [comment] 2019-12-08 16:43
[Mapping Group 1 (1).zip](https://github.com/MarcusWolschon/osmeditor4android/files/3936570/Mapping.Group.1.1.zip)

**Comment by simonpoole** [comment] 2019-12-08 18:04
You can try and load the included file (in Vespucci or JOSM) . I didn't get an answer to 

> Do you have pan and zoom download turned on?

Which could be key to determining the root cause of the issue (a deleted way with a placeholder id was present which shouldn't really happen). Or any other relevant information.

[fixed-20191208.txt](https://github.com/MarcusWolschon/osmeditor4android/files/3936653/fixed-20191208.txt)

**Comment by pokulo** [comment] 2020-01-15 08:44
I have most recent Vespucci-Version 14.0.13.0 from fdroid.org and the same problem with uploading the following (will add the osc and jsom file soon) changes to osm.

**Comment by simonpoole** [comment] 2020-01-15 08:49
As pointed out above we really need to know some details about the configuration too, aka if pan and zoom download was turned on, etc.

**Comment by pokulo** [comment] 2020-01-15 08:58
could not upload files via Android (OctoDroid) so I past the osc-file here:

```xml
<osmChange generator="Vespucci/14.0.13.0" version="0.6">

<create>

<node id="-7" version="1" timestamp="2020-01-15T07:48:55Z" visible="true" lat="51.032019" lon="13.7085305"/>

<node id="-56" version="1" timestamp="2020-01-15T08:25:37Z" visible="true" lat="51.0320041" lon="13.7090447"/>

<node id="-50" version="1" timestamp="2020-01-15T08:11:26Z" visible="true" lat="51.0320043" lon="13.7089392"/>

<node id="-51" version="1" timestamp="2020-01-15T08:12:25Z" visible="true" lat="51.0319602" lon="13.7088671">

<tag k="amenity" v="drinking_water"/>

</node>

<node id="-44" version="1" timestamp="2020-01-15T08:10:01Z" visible="true" lat="51.0319974" lon="13.7087604"/>

<node id="-49" version="1" timestamp="2020-01-15T08:11:21Z" visible="true" lat="51.03194" lon="13.7088701"/>

<node id="-2" version="1" timestamp="2020-01-15T08:08:47Z" visible="true" lat="51.0322439" lon="13.708387"/>

<node id="-11" version="1" timestamp="2020-01-15T08:08:43Z" visible="true" lat="51.0322356" lon="13.7084067">

<tag k="access" v="private"/>

<tag k="barrier" v="gate"/>

</node>

<node id="-55" version="1" timestamp="2020-01-15T08:25:37Z" visible="true" lat="51.0320041" lon="13.7090447"/>

<node id="-42" version="1" timestamp="2020-01-15T08:07:59Z" visible="true" lat="51.0319904" lon="13.7087051"/>

<node id="-22" version="1" timestamp="2020-01-15T07:59:57Z" visible="true" lat="51.0319857" lon="13.7086171"/>

<node id="-1" version="1" timestamp="2020-01-15T07:39:57Z" visible="true" lat="51.0320491" lon="13.708641">

<tag k="access" v="private"/>

<tag k="entrance" v="yes"/>

</node>

<node id="-6" version="1" timestamp="2020-01-15T07:45:10Z" visible="true" lat="51.0320041" lon="13.7090447"/>

<node id="-13" version="1" timestamp="2020-01-15T07:58:49Z" visible="true" lat="51.0321042" lon="13.7087948"/>

<node id="-52" version="1" timestamp="2020-01-15T08:14:23Z" visible="true" lat="51.0319248" lon="13.7089042">

<tag k="leisure" v="firepit"/>

</node>

<node id="-41" version="1" timestamp="2020-01-15T08:08:07Z" visible="true" lat="51.0320141" lon="13.7086458"/>

<node id="-45" version="1" timestamp="2020-01-15T08:09:22Z" visible="true" lat="51.0320708" lon="13.7088347"/>

<node id="-46" version="1" timestamp="2020-01-15T08:09:30Z" visible="true" lat="51.0320918" lon="13.7087822"/>

<node id="-3" version="1" timestamp="2020-01-15T08:08:22Z" visible="true" lat="51.0320923" lon="13.7087564"/>

<node id="-8" version="1" timestamp="2020-01-15T07:48:30Z" visible="true" lat="51.0318708" lon="13.7089097"/>

<node id="-48" version="1" timestamp="2020-01-15T08:10:48Z" visible="true" lat="51.0320012" lon="13.708716"/>

<node id="-57" version="1" timestamp="2020-01-15T08:32:07Z" visible="true" lat="51.0320288" lon="13.7086906"/>

<node id="-43" version="1" timestamp="2020-01-15T08:09:56Z" visible="true" lat="51.0320111" lon="13.7087261"/>

<node id="-5" version="1" timestamp="2020-01-15T07:45:57Z" visible="true" lat="51.0322588" lon="13.708403"/>

<way id="-2" version="1" timestamp="2020-01-15T07:58:49Z" visible="true">

<nd ref="-5"/>

<nd ref="-13"/>

<nd ref="-6"/>

<tag k="barrier" v="fence"/>

</way>

<way id="-13" version="1" timestamp="2020-01-15T08:32:07Z" visible="true">

<nd ref="-57"/>

<nd ref="-48"/>

<nd ref="-49"/>

<nd ref="-50"/>

<tag k="highway" v="path"/>

</way>

<way id="-3" version="1" timestamp="2020-01-15T08:26:29Z" visible="true">

<nd ref="-7"/>

<nd ref="-22"/>

<nd ref="-8"/>

<tag k="barrier" v="hedge"/>

</way>

<way id="-10" version="1" timestamp="2020-01-15T08:25:37Z" visible="true">

<nd ref="-13"/>

<nd ref="-55"/>

<nd ref="-8"/>

<nd ref="-22"/>

<nd ref="-41"/>

<nd ref="-42"/>

<nd ref="-48"/>

<nd ref="-43"/>

<nd ref="-44"/>

<nd ref="-45"/>

<nd ref="-46"/>

<nd ref="-13"/>

<tag k="leisure" v="garden"/>

</way>

<way id="-1" version="1" timestamp="2020-01-15T08:33:42Z" visible="true">

<nd ref="-2"/>

<nd ref="-11"/>

<nd ref="-3"/>

<nd ref="-57"/>

<nd ref="-1"/>

<tag k="access" v="private"/>

<tag k="highway" v="service"/>

<tag k="service" v="parking_aisle"/>

</way>

<way id="-5" version="1" timestamp="2020-01-15T08:25:37Z" visible="true">

<nd ref="-8"/>

<nd ref="-56"/>

<tag k="barrier" v="wall"/>

<tag k="material" v="stone"/>

</way>

</create>

<modify>

<node id="269170693" version="5" timestamp="2017-01-14T23:24:46Z" visible="true" lat="51.0321116" lon="13.7086783"/>

<node id="261763454" version="8" timestamp="2019-06-25T20:18:23Z" visible="true" lat="51.0330506" lon="13.7092463"/>

<node id="4608680559" version="1" timestamp="2017-01-14T23:24:46Z" visible="true" lat="51.0320708" lon="13.7086641"/>

<node id="269170691" version="6" timestamp="2017-01-14T23:24:46Z" visible="true" lat="51.0316618" lon="13.70797"/>

<node id="269170695" version="5" timestamp="2017-01-14T23:24:46Z" visible="true" lat="51.0320251" lon="13.7085367"/>

<node id="4608680560" version="1" timestamp="2017-01-14T23:24:46Z" visible="true" lat="51.0320793" lon="13.7086439"/>

<node id="16574841" version="3" timestamp="2014-09-14T17:35:22Z" visible="true" lat="51.0310345" lon="13.7071185"/>

<node id="269170692" version="5" timestamp="2017-01-14T23:24:46Z" visible="true" lat="51.032181" lon="13.7085133"/>

<node id="2505111836" version="3" timestamp="2017-01-14T23:24:46Z" visible="true" lat="51.0316842" lon="13.7081754">

<tag k="addr:city" v="Dresden"/>

<tag k="addr:country" v="DE"/>

<tag k="addr:housenumber" v="13"/>

<tag k="addr:postcode" v="01187"/>

<tag k="addr:street" v="Klingenberger Straße"/>

<tag k="entrance" v="main"/>

</node>

<node id="2373079573" version="1" timestamp="2013-07-04T09:27:55Z" visible="true" lat="51.0313197" lon="13.707412"/>

<node id="2373079581" version="3" timestamp="2017-01-14T23:24:46Z" visible="true" lat="51.0320778" lon="13.7084109"/>

<node id="269170696" version="5" timestamp="2017-01-14T23:24:46Z" visible="true" lat="51.0316091" lon="13.7080958"/>

<node id="2505111837" version="3" timestamp="2017-01-14T23:24:46Z" visible="true" lat="51.0319536" lon="13.708461">

<tag k="addr:city" v="Dresden"/>

<tag k="addr:country" v="DE"/>

<tag k="addr:housenumber" v="9"/>

<tag k="addr:postcode" v="01187"/>

<tag k="addr:street" v="Klingenberger Straße"/>

<tag k="entrance" v="main"/>

</node>

<node id="3077123025" version="1" timestamp="2014-09-14T17:35:22Z" visible="true" lat="51.0310869" lon="13.7071717"/>

<node id="2505111842" version="1" timestamp="2013-10-22T16:25:39Z" visible="true" lat="51.03209" lon="13.7082231"/>

<node id="353680862" version="4" timestamp="2013-07-04T09:27:56Z" visible="true" lat="51.0322091" lon="13.7083501"/>

<node id="261764076" version="5" timestamp="2015-03-24T21:37:49Z" visible="true" lat="51.0319646" lon="13.7080899"/>

<node id="2373079569" version="3" timestamp="2017-01-14T23:24:46Z" visible="true" lat="51.0320799" lon="13.7084059"/>

<node id="2373079576" version="1" timestamp="2013-07-04T09:27:55Z" visible="true" lat="51.0316884" lon="13.7077978"/>

<node id="2505111835" version="3" timestamp="2017-01-14T23:24:46Z" visible="true" lat="51.0318164" lon="13.7083155">

<tag k="addr:city" v="Dresden"/>

<tag k="addr:country" v="DE"/>

<tag k="addr:housenumber" v="11"/>

<tag k="addr:postcode" v="01187"/>

<tag k="addr:street" v="Klingenberger Straße"/>

<tag k="entrance" v="main"/>

</node>

<node id="4608680558" version="1" timestamp="2017-01-14T23:24:46Z" visible="true" lat="51.0320293" lon="13.7086202"/>

<node id="269170694" version="5" timestamp="2017-01-14T23:24:46Z" visible="true" lat="51.032011" lon="13.7085705"/>

<node id="4608680561" version="1" timestamp="2017-01-14T23:24:46Z" visible="true" lat="51.0320381" lon="13.708599"/>

<way id="160965702" version="35" timestamp="2020-01-15T08:28:45Z" visible="true">

<nd ref="3220559080"/>

<nd ref="3220559078"/>

<nd ref="3220559075"/>

<nd ref="3220559074"/>

<nd ref="3220559072"/>

<nd ref="3220559071"/>

<nd ref="3220559070"/>

<nd ref="3220559069"/>

<nd ref="252586712"/>

<nd ref="36829313"/>

<nd ref="3476221675"/>

<nd ref="252586711"/>

<nd ref="3476221658"/>

<nd ref="3476221682"/>

<nd ref="36829312"/>

<nd ref="30774956"/>

<nd ref="30774955"/>

<nd ref="30774954"/>

<nd ref="30774953"/>

<nd ref="2271305529"/>

<nd ref="2271305506"/>

<nd ref="2463871267"/>

<nd ref="2463871294"/>

<nd ref="30774971"/>

<nd ref="30774970"/>

<nd ref="30774969"/>

<nd ref="1935504586"/>

<nd ref="30774968"/>

<nd ref="30774967"/>

<nd ref="30774966"/>

<nd ref="30774965"/>

<nd ref="347529497"/>

<nd ref="30774964"/>

<nd ref="347529496"/>

<nd ref="30774963"/>

<nd ref="30774962"/>

<nd ref="2327920056"/>

<nd ref="1729320401"/>

<nd ref="1729320402"/>

<nd ref="1729320403"/>

<nd ref="1729320405"/>

<nd ref="1729320410"/>

<nd ref="1729320408"/>

<nd ref="2409474391"/>

<nd ref="2409474390"/>

<nd ref="1729320412"/>

<nd ref="1729320414"/>

<nd ref="2727912406"/>

<nd ref="1729320415"/>

<nd ref="1729320416"/>

<nd ref="1729320419"/>

<nd ref="1729320418"/>

<nd ref="1729320417"/>

<nd ref="1729320420"/>

<nd ref="1729320422"/>

<nd ref="1729320423"/>

<nd ref="2505373828"/>

<nd ref="1729320424"/>

<nd ref="4568733197"/>

<nd ref="1729320427"/>

<nd ref="4568733198"/>

<nd ref="1729320430"/>

<nd ref="1729320429"/>

<nd ref="1729320433"/>

<nd ref="1729320432"/>

<nd ref="2302550287"/>

<nd ref="1729320431"/>

<nd ref="2520734667"/>

<nd ref="1729320428"/>

<nd ref="3355586632"/>

<nd ref="2302550273"/>

<nd ref="1729320426"/>

<nd ref="1729320425"/>

<nd ref="2437832550"/>

<nd ref="2437832553"/>

<nd ref="1202672920"/>

<nd ref="1202672926"/>

<nd ref="1202672915"/>

<nd ref="2614883770"/>

<nd ref="3239833267"/>

<nd ref="1202674679"/>

<nd ref="3239833290"/>

<nd ref="3239833282"/>

<nd ref="2614883781"/>

<nd ref="1202674657"/>

<nd ref="2845812530"/>

<nd ref="2845812511"/>

<nd ref="2845812510"/>

<nd ref="2845812524"/>

<nd ref="2845812527"/>

<nd ref="2845812509"/>

<nd ref="2845812506"/>

<nd ref="2845812512"/>

<nd ref="2845812521"/>

<nd ref="2845812538"/>

<nd ref="2845812515"/>

<nd ref="2845812525"/>

<nd ref="2845812514"/>

<nd ref="2845812513"/>

<nd ref="2845812520"/>

<nd ref="2845812528"/>

<nd ref="1202674661"/>

<nd ref="1202674683"/>

<nd ref="1617876981"/>

<nd ref="2327920059"/>

<nd ref="1202679036"/>

<nd ref="1202678998"/>

<nd ref="1202679012"/>

<nd ref="1202679017"/>

<nd ref="1202679031"/>

<nd ref="1202679035"/>

<nd ref="2692688831"/>

<nd ref="1202679001"/>

<nd ref="3884401521"/>

<nd ref="1202679005"/>

<nd ref="3884401536"/>

<nd ref="3884401538"/>

<nd ref="3884401540"/>

<nd ref="5209858851"/>

<nd ref="5209858850"/>

<nd ref="2327232674"/>

<nd ref="1202679025"/>

<nd ref="2327232669"/>

<nd ref="1202678994"/>

<nd ref="2327232676"/>

<nd ref="2327232694"/>

<nd ref="2327232682"/>

<nd ref="2327232677"/>

<nd ref="1202679042"/>

<nd ref="1202679007"/>

<nd ref="1202679011"/>

<nd ref="1202679027"/>

<nd ref="1202679030"/>

<nd ref="1202678997"/>

<nd ref="1202679000"/>

<nd ref="1202679016"/>

<nd ref="1202679034"/>

<nd ref="1202679039"/>

<nd ref="1202679004"/>

<nd ref="1202679008"/>

<nd ref="1202679024"/>

<nd ref="1202679018"/>

<nd ref="1202679032"/>

<nd ref="1202679037"/>

<nd ref="2411307396"/>

<nd ref="1202679002"/>

<nd ref="2077323638"/>

<nd ref="2077323637"/>

<nd ref="2077323633"/>

<nd ref="2077323631"/>

<nd ref="5553374965"/>

<nd ref="5553374964"/>

<nd ref="5328069647"/>

<nd ref="5328069651"/>

<nd ref="6585946772"/>

<nd ref="2416679915"/>

<nd ref="6458412863"/>

<nd ref="2327920058"/>

<nd ref="109799472"/>

<nd ref="109799467"/>

<nd ref="1202674670"/>

<nd ref="3977972558"/>

<nd ref="3977972560"/>

<nd ref="2583600613"/>

<nd ref="2583600562"/>

<nd ref="2583600529"/>

<nd ref="2583600602"/>

<nd ref="2583600607"/>

<nd ref="2583600566"/>

<nd ref="3977972559"/>

<nd ref="5707537146"/>

<nd ref="5707537149"/>

<nd ref="2583600541"/>

<nd ref="2583600554"/>

<nd ref="3977972557"/>

<nd ref="2583600556"/>

<nd ref="2583600574"/>

<nd ref="2583600558"/>

<nd ref="2583600594"/>

<nd ref="2583600580"/>

<nd ref="1202674662"/>

<nd ref="2327920057"/>

<nd ref="6149604742"/>

<nd ref="6149604741"/>

<nd ref="30894995"/>

<nd ref="30894994"/>

<nd ref="4545050941"/>

<nd ref="30894992"/>

<nd ref="534887"/>

<nd ref="30159617"/>

<nd ref="424260256"/>

<nd ref="30159616"/>

<nd ref="2761857994"/>

<nd ref="3220559112"/>

<nd ref="2036291802"/>

<nd ref="424260273"/>

<nd ref="3853537"/>

<nd ref="1493415833"/>

<nd ref="424260262"/>

<nd ref="3853536"/>

<nd ref="2691356909"/>

<nd ref="2691356911"/>

<nd ref="2705559319"/>

<nd ref="2705559348"/>

<nd ref="3220559081"/>

<nd ref="3220559096"/>

<nd ref="3220559097"/>

<nd ref="3220559098"/>

<nd ref="3220559080"/>

</way>

<way id="38538188" version="2" timestamp="2020-01-15T08:28:57Z" visible="true">

<nd ref="2302550273"/>

<nd ref="1729320426"/>

<nd ref="1729320425"/>

<nd ref="456098956"/>

<nd ref="2302550273"/>

<tag k="landuse" v="commercial"/>

</way>

<way id="24769641" version="5" timestamp="2020-01-15T07:38:12Z" visible="true">

<nd ref="269170695"/>

<nd ref="2373079581"/>

<nd ref="2373079569"/>

<nd ref="269170692"/>

<nd ref="269170693"/>

<nd ref="4608680560"/>

<nd ref="4608680559"/>

<nd ref="-1"/>

<nd ref="4608680558"/>

<nd ref="4608680561"/>

<nd ref="269170694"/>

<nd ref="269170695"/>

<tag k="addr:city" v="Dresden"/>

<tag k="addr:country" v="DE"/>

<tag k="addr:housenumber" v="7"/>

<tag k="addr:postcode" v="01187"/>

<tag k="addr:street" v="Klingenberger Straße"/>

<tag k="building" v="yes"/>

<tag k="height" v="11"/>

</way>

<way id="228651382" version="4" timestamp="2020-01-15T07:46:44Z" visible="true">

<nd ref="269170695"/>

<nd ref="-7"/>

<nd ref="2505111837"/>

<nd ref="2505111835"/>

<nd ref="2505111836"/>

<nd ref="269170696"/>

<nd ref="269170691"/>

<nd ref="2373079581"/>

<nd ref="269170695"/>

<tag k="building" v="apartments"/>

<tag k="building:colour" v="#E7E7E4"/>

<tag k="building:levels" v="5"/>

<tag k="building:levels:underground" v="1"/>

<tag k="building:material" v="plaster"/>

<tag k="height" v="20"/>

<tag k="roof:colour" v="#9C5E45"/>

<tag k="roof:height" v="3.8"/>

<tag k="roof:levels" v="1"/>

<tag k="roof:material" v="roof_tiles"/>

<tag k="roof:shape" v="gabled"/>

</way>

<way id="228651381" version="1" timestamp="2020-01-15T07:53:35Z" visible="true">

<nd ref="2373079586"/>

<nd ref="2373079587"/>

<nd ref="2373079580"/>

<nd ref="2373079579"/>

<nd ref="2373079586"/>

<tag k="access" v="private"/>

<tag k="amenity" v="parking"/>

<tag k="capacity" v="16"/>

<tag k="capacity:disabled" v="no"/>

<tag k="capacity:parent" v="no"/>

<tag k="capacity:women" v="no"/>

<tag k="fee" v="no"/>

<tag k="lit" v="no"/>

<tag k="maxstay" v="no"/>

<tag k="park_ride" v="no"/>

<tag k="parking" v="surface"/>

<tag k="smoothness" v="bad"/>

<tag k="supervised" v="no"/>

<tag k="surface" v="concrete:plates"/>

</way>

<way id="218037750" version="8" timestamp="2020-01-15T07:44:43Z" visible="true">

<nd ref="16574841"/>

<nd ref="3077123025"/>

<nd ref="2373079573"/>

<nd ref="2373079576"/>

<nd ref="261764076"/>

<nd ref="2505111842"/>

<nd ref="353680862"/>

<nd ref="-2"/>

<nd ref="-5"/>

<nd ref="261763454"/>

<tag k="highway" v="residential"/>

<tag k="lit" v="yes"/>

<tag k="maxspeed" v="30"/>

<tag k="name" v="Klingenberger Straße"/>

<tag k="postal_code" v="01187"/>

<tag k="sidewalk" v="both"/>

<tag k="smoothness" v="excellent"/>

<tag k="surface" v="asphalt"/>

<tag k="zone:maxspeed" v="DE:30"/>

</way>

</modify>

<delete>

<way id="-4" version="1" timestamp="2020-01-15T07:49:49Z" visible="true">

<nd ref="-9"/>

<nd ref="-10"/>

<tag k="barrier" v="wall"/>

<tag k="material" v="stone"/>

</way>

<way id="-7" version="1" timestamp="2020-01-15T08:00:49Z" visible="true">

<nd ref="-25"/>

<nd ref="-26"/>

<nd ref="-23"/>

<nd ref="-24"/>

<nd ref="-27"/>

</way>

<way id="-6" version="1" timestamp="2020-01-15T08:02:02Z" visible="true">

<nd ref="-40"/>

<nd ref="-14"/>

<nd ref="-15"/>

<nd ref="-16"/>

<nd ref="-17"/>
<nd ref="-18"/>
<nd ref="-19"/>
</way>
</delete>
</osmChange>
```

**Comment by pokulo** [comment] 2020-01-15 09:01
> As pointed out above we really need to know some details about the configuration too, aka if pan and zoom download was turned on, etc.

no pan-/zoom-download.

I used simple mode cut and pasted some ways including way id=-4 which seems to have missing id -9 and -10. Could cut and past cause the problem?

**Comment by pokulo** [comment] 2020-01-15 09:05
does josm-file containe more details you need?

**Comment by pokulo** [comment] 2020-01-15 09:05
does josm-file contain more details you need?

**Comment by simonpoole** [comment] 2020-01-15 09:06
Yes cut and paste could cause the problem (logically it has to delete the original elements as you might not actually paste before the upload, but in the case of new elements it shouldn't be adding them to the upload ). To fix your specifc upload you simply need to remove the deleted elements from the JOSM format file and then load that and upload.

Thanks for the helpful report.

**Comment by simonpoole** [comment] 2020-01-15 11:22
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/0e84f7d933c471ded8f05b8238940e9124e00485 leaving the issue open for reference for now.

**Comment by pokulo** [comment] 2020-01-15 11:28
@simonpoole @ReutGIS thanks for you fast replies! I will simply wait for your Bugfix, hope this will also sanitize my broken changeset.. :)

**Comment by simonpoole** [comment] 2020-01-15 11:32
The fix doesn't fix the issue in the existing data, if you can send me your data as a JOSM file, I can do it quickly manually and re-post it here.

**Comment by pokulo** [comment] 2020-01-16 07:04
Rhanks for you proposed help. the JOSM-file is quite large. I don't know what is contained there. Seems to contain all my changes since install of vespucci. Does it contain any confidential settings like account data?

**Comment by pokulo** [comment] 2020-01-16 07:05
Cant you import my OSC-file and send my my changes as JOSM?

**Comment by simonpoole** [comment] 2020-01-16 08:13
> 
> 
> Thanks for you proposed help. The JOSM-file is quite large. I don't know what is contained there. Seems to contain all my changes since install of vespucci. Does it contain any confidential settings like account data?

No it only contains OSM data plus your changes, the OSC file has to be applied to the area you where editing so a bit of a pain, the fulll file would be easier..

**Comment by pokulo** [comment] 2020-01-17 10:22
kk, will send it to you. thanks

**Comment by pokulo** [comment] 2020-01-17 16:20
@simonpoole I actually had the following Problem sending my mail to info@vespucci.io:
```
The mail system

<info@vespucci.io>: TLS is required, but was not offered by host
    mail.poole.ch[212.254.75.189]
```

**Comment by simonpoole** [comment] 2020-01-19 11:07
That's you mail client/server requiring TLS.

**Comment by pokulo** [comment] 2020-01-19 13:39
Don't think so. I wrote my mail using posteo.de, never heard they use Swiss Servers to deliver mails. Reason is still present: 

Websites prove their identity via certificates, which are valid for a set time period. The certificate for mail.poole.ch expired on 10/6/2009.

I can simply try to send the mail again. Maybe it was because of the attachment.

**Comment by simonpoole** [comment] 2020-01-19 13:44
See https://posteo.de/en/help/activating-tls-sending-guarantee

**Comment by pokulo** [comment] 2020-01-19 13:54
Yes, indeed. But my solution is not, to disable this guarantee. The preferred solution would be, to push a new TLS-Certificate to that server.

**Comment by simonpoole** [comment] 2020-01-19 14:01
It isn't so simple (and a smtp server isn't a webserver) and currently I would need to change the server to something that supports TLS (which is happening but not right now).

**Comment by pokulo** [comment] 2020-01-19 14:03
ok, I can simply upload my file here now, since I use a laptop to write this. wait a second....

**Comment by pokulo** [comment] 2020-01-19 14:09
puha, github dow not suppert tar.xz-Files? do they want to unzip it?

**Comment by pokulo** [comment] 2020-01-19 14:10
So, if you still want to help me, I would be very pleased. Here is my changes since I installed vespucci (and hopefully not so much more):

[pokulo.changes.issue_1052.vespucci.josm.zip](https://github.com/MarcusWolschon/osmeditor4android/files/4082751/pokulo.changes.issue_1052.vespucci.josm.zip)

**Comment by simonpoole** [comment] 2020-01-19 14:58
So can you try loading this into vespucci or JOSM and then uploading?
[fxed.vespucci.zip](https://github.com/MarcusWolschon/osmeditor4android/files/4082798/fxed.vespucci.zip)

**Comment by pokulo** [comment] 2020-01-19 16:01
Tank you so much, will try it today!

**Comment by pokulo** [comment] 2020-01-19 16:15
@simonpoole: Your fix did work for me. good work. 

hope I can support you doing more like this. 

Best regards. 
Heinrich

**Closed** 2020-01-29 22:59 UTC
Labels: Defect, FIXED, High Priority
