### ISSUE TITLE
Consider making note upload from note editor asynchronous

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#727] opened 2018-06-07 11:45 UTC
Currently responding to note, posting comment and/or changing state and selecting upload can lock-up for a long time (multiple messages about frozen app from Android with offer to terminate it or send report or wait are typical).

**Comment by simonpoole** [comment] 2018-06-07 17:38
The upload -is- asynchronous (you can't actually do any network communications on the main thread, aka there is no choice), so the problem  has to have a different root cause.  You are uploading single changes as I understand?

**Comment by matkoniecz** [comment] 2018-06-07 17:41
Usually it is comment and switch note state to closed. Commit + upload all bug changes works fine, uploading directly from note edit menu frequently freezes program.

**Comment by simonpoole** [comment] 2018-06-07 17:46
Is the note dialog still shown when this happens (the dialog should typically be long gone because it is dismissed and the upload is handled by a AsyncTask)?

**Comment by matkoniecz** [comment] 2018-06-07 17:48
> Is the note dialog still shown when this happens

Yes.

**Comment by simonpoole** [comment] 2018-06-07 19:07
Ah yes, while the network comms itself is async the method itself waits for the AsyncTask to complete.

**Comment by simonpoole** [comment] 2018-06-07 19:37
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/af961b884c7e0835160b7c1d9ec2f4598f4d408b

**Closed by simonpoole** 2018-06-07 19:37 UTC
Labels: Defect
