### ISSUE TITLE
Feature - Merge areas into a single area

### ISSUE THREAD

**Issue by johantiden** [MarcusWolschon/osmeditor4android#1262] opened 2020-10-24 09:06 UTC
I often need to merge adjacent areas. This can be parking surfaces or other landuse. In order to do this I have to 

1. Merge the areas' nodes,
2. Cut each area, where the two areas now intersect. This results in four ways, two outer and two inner along the intersection. 
3. Remove the two inner ways. 
4. Select the two outer areas. Press the merge button. 

This can probably be automated. Either by asking for two cut points, or just guessing from where the areas intersect (with or without step 1). You could always undo and try again if it doesn't look good. 

The same rules for merging should apply: Both nodes need to have the same set of tags or else the tag editor should open.

**Comment by simonpoole** [comment] 2020-10-24 21:00
Duplicate of https://github.com/MarcusWolschon/osmeditor4android/issues/322

**Closed by simonpoole** 2020-10-24 21:00 UTC
