### ISSUE TITLE
Corrupt local data: new nodes marked as "changed" - cannot upload

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1170] opened 2020-05-26 13:16 UTC
Description:
---

Only way out is to revert all local changes.

Will try to reproduce 

Device info:
---
<table>
<tr><td>App version</td><td>14.1.4.0</td></tr>
<tr><td>App version code</td><td>1407</td></tr>
<tr><td>Android build version</td><td>6352890</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QQ2A.200501.001.B2</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Google</td></tr>
<tr><td>Device name</td><td>crosshatch</td></tr>
<tr><td>Device model</td><td>Pixel 3 XL</td></tr>
<tr><td>Device product name</td><td>crosshatch</td></tr>
<tr><td>Device hardware name</td><td>crosshatch</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>joihoin</td></tr>
</table>

**Comment by simonpoole** [comment] 2020-05-26 13:39
You should save the data either as a JOSM format file or in OCS format, no need to redo any work and helps with debugging too. 

How did you determine that the objects were marked as "changed".

**Comment by johantiden** [comment] 2020-05-26 14:25
I did save the files as osc. They were still corrupt after importing.

The upload dialog had them as (ish) `node #-1     changed`, where they should have been "created". Negative placeholder index minus 1. 

Uploading returns a server error similar to "could not find reference node -1". I can reload the corrupt files to get the exact message if you want.

**Comment by johantiden** [comment] 2020-05-26 14:28
It's very hard to reproduce. I suspect that it's a combination of pan/zoom auto download and being near memory limit so that a lot of items are flushed. I may have hit _undo_ during pan/zoom. I don't know. The app was very unstable from a long session (memory leaks?).

**Comment by johantiden** [comment] 2020-05-26 18:05
It's very hard to reproduce. I suspect that it's a combination of pan/zoom auto download and being near memory limit so that a lot of items are flushed. I may have hit _undo_ during pan/zoom. I don't know. The app was very unstable from a long session (memory leaks?).

**Comment by simonpoole** [comment] 2020-05-26 18:18
Unlikely to be directly pan and zoom related as the pruning specifically doesn't touch any created or changed elements. So maybe undo related.

Exporting to doesn't fix the issue but the file can be manually fixed and the data uploaded.

**Comment by johantiden** [comment] 2020-05-26 18:26
Don't worry about the data. It was just 5 minutes of work and I opted to redo it manually.

If you still want the file for debug purposes I can see if I can upload it somehow

**Comment by johantiden** [comment] 2020-05-26 18:31
```
<?xml version='1.0' encoding='UTF-8' ?><osmChange generator="Vespucci/14.1.4.0" version="0.6"><create><node id="-7" version="1" timestamp="2020-05-26T10:19:09Z" visible="true" lat="59.3455311" lon="18.0072383" /><node id="-14" version="1" timestamp="2020-05-26T10:24:36Z" visible="true" lat="59.3458963" lon="18.0072225" /><node id="-25" version="1" timestamp="2020-05-26T10:26:32Z" visible="true" lat="59.3459789" lon="18.0076473" /><node id="-2" version="1" timestamp="2020-05-26T10:24:48Z" visible="true" lat="59.3460616" lon="18.007216" /><node id="-12" version="1" timestamp="2020-05-26T10:25:10Z" visible="true" lat="59.3462939" lon="18.0081211" /><node id="-19" version="1" timestamp="2020-05-26T10:24:02Z" visible="true" lat="59.3456397" lon="18.007628" /><node id="-21" version="1" timestamp="2020-05-26T10:26:16Z" visible="true" lat="59.3463332" lon="18.0079061" /><node id="-11" version="1" timestamp="2020-05-26T10:25:21Z" visible="true" lat="59.3464413" lon="18.0082323" /><node id="-17" version="1" timestamp="2020-05-26T10:26:11Z" visible="true" lat="59.346481" lon="18.0080141" /><node id="-18" version="1" timestamp="2020-05-26T10:19:06Z" visible="true" lat="59.345476" lon="18.0075046" /><node id="-23" version="1" timestamp="2020-05-26T10:25:01Z" visible="true" lat="59.346221" lon="18.0072474" /><node id="-4" version="1" timestamp="2020-05-26T10:24:30Z" visible="true" lat="59.3457961" lon="18.0077459" /><node id="-24" version="1" timestamp="2020-05-26T10:26:46Z" visible="true" lat="59.3455166" lon="18.0073095" /><node id="-22" version="1" timestamp="2020-05-26T10:24:20Z" visible="true" lat="59.3457194" lon="18.0072295" /><node id="-15" version="1" timestamp="2020-05-26T10:25:36Z" visible="true" lat="59.3465253" lon="18.0077704" /><node id="-16" version="1" timestamp="2020-05-26T10:26:22Z" visible="true" lat="59.3461228" lon="18.0077524" /><node id="-9" version="1" timestamp="2020-05-26T10:25:12Z" visible="true" lat="59.3463765" lon="18.0076689" /><node id="-13" version="1" timestamp="2020-05-26T10:24:57Z" visible="true" lat="59.3460822" lon="18.0079615" /><node id="-3" version="1" timestamp="2020-05-26T10:26:37Z" visible="true" lat="59.3458351" lon="18.0075422" /><node id="-8" version="1" timestamp="2020-05-26T10:26:42Z" visible="true" lat="59.3456796" lon="18.0074286" /><node id="-10" version="1" timestamp="2020-05-26T10:24:45Z" visible="true" lat="59.3459393" lon="18.0078538" /><node id="-5" version="1" timestamp="2020-05-26T10:18:45Z" visible="true" lat="59.345443" lon="18.0072568" /><way id="-2" version="1" timestamp="2020-05-26T10:26:41Z" visible="true"><nd ref="263753654" /><nd ref="-5" /><nd ref="-24" /><nd ref="-8" /><nd ref="-3" /><nd ref="-25" /><nd ref="-16" /><nd ref="-21" /><nd ref="-17" /><tag k="highway" v="service" /><tag k="service" v="parking_aisle" /></way><way id="-4" version="1" timestamp="2020-05-26T10:26:42Z" visible="true"><nd ref="-19" /><nd ref="-8" /><nd ref="-22" /><tag k="highway" v="service" /><tag k="service" v="parking_aisle" /></way><way id="-8" version="1" timestamp="2020-05-26T10:19:12Z" visible="true"><nd ref="-18" /><nd ref="-24" /><nd ref="-7" /><tag k="highway" v="service" /><tag k="service" v="parking_aisle" /></way><way id="-3" version="1" timestamp="2020-05-26T10:26:36Z" visible="true"><nd ref="-4" /><nd ref="-3" /><nd ref="-14" /><tag k="highway" v="service" /><tag k="service" v="parking_aisle" /></way><way id="-7" version="1" timestamp="2020-05-26T10:26:22Z" visible="true"><nd ref="-13" /><nd ref="-16" /><nd ref="-23" /><tag k="highway" v="service" /><tag k="service" v="parking_aisle" /></way><way id="-1" version="1" timestamp="2020-05-26T10:26:11Z" visible="true"><nd ref="-11" /><nd ref="-17" /><nd ref="-15" /><tag k="highway" v="service" /><tag k="service" v="parking_aisle" /></way><way id="-5" version="1" timestamp="2020-05-26T10:26:32Z" visible="true"><nd ref="-10" /><nd ref="-25" /><nd ref="-2" /><tag k="highway" v="service" /><tag k="service" v="parking_aisle" /></way><way id="-6" version="1" timestamp="2020-05-26T10:26:15Z" visible="true"><nd ref="-12" /><nd ref="-21" /><nd ref="-9" /><tag k="highway" v="service" /><tag k="service" v="parking_aisle" /></way></create><modify><node id="364330260" version="2" timestamp="2010-11-14T22:53:26Z" visible="true" lat="59.3463926" lon="18.0073053" /><node id="364330262" version="2" timestamp="2010-11-14T22:53:31Z" visible="true" lat="59.3465936" lon="18.007709" /><node id="364330263" version="2" timestamp="2010-11-14T22:52:45Z" visible="true" lat="59.3463494" lon="18.0075296" /><node id="364330261" version="2" timestamp="2010-11-14T22:53:28Z" visible="true" lat="59.3466368" lon="18.0074847" /></modify><delete><node id="-1" version="1" timestamp="2020-05-26T10:34:49Z" visible="true" lat="59.3457552" lon="18.0073594" /><node id="-6" version="1" timestamp="2020-05-26T10:19:30Z" visible="true" lat="59.3456363" lon="18.0076177" /><node id="-20" version="1" timestamp="2020-05-26T10:34:46Z" visible="true" lat="59.3456322" lon="18.007483" /></delete></osmChange> 
```

**Comment by simonpoole** [comment] 2020-05-26 18:32
If possible attach the file to the issue (you may have to change the extension to make github happy).

**Comment by johantiden** [comment] 2020-05-26 18:35
[2020-05-26T103149.osc.txt](https://github.com/MarcusWolschon/osmeditor4android/files/4684271/2020-05-26T103149.osc.txt)

**Comment by johantiden** [comment] 2020-05-26 18:36
id="-1" appears twice

**Comment by simonpoole** [comment] 2020-05-26 19:01
> 
> 
> id="-1" appears twice

Hmm I don't see that anywhere in the file.

You said the app was "unstable" what symptoms was it showing? In general things will simply get very slow if you have too much data loaded (and that may cause issues with state saving), but that is with 10'000s of nodes.

**Comment by johantiden** [comment] 2020-05-26 19:54
Low fps (1-2), unresponsive when trying to "Download current view" so I tap outside to close it. All subsequent "online" actions seem to be queued after that event which never finishes.

Sometimes I get an exception upon opening the tags editor. I can still edit though. When the editor is closed, the map has been zoomed back to somewhere I was earlier.

Eventually I have to force exit the app. This usually results in loss of local data when starting again.

Just panning around Stockholm I get
`Nodes (current/Waynodes/API): 14123/17012/0`

**Comment by simonpoole** [comment] 2020-05-26 20:51
That sounds wrong. Definitely you should not regularly have that much data loaded (if you stay zoomed in things will be OK, but zooming out will force Vespucci to retain everything in the viewbox). If you are editing in a high density area I would either not zoom out so far or turn auto download off and only load manually.

As a comparison go to openstreetmap.org, zoom to zoom level 17 over central Stockholm, and then try to edit with iD (that will be -less- data than 14'000 nodes worth).

However it is rather unlikely that any of the above anything directly to do with the original issue.

**Comment by johantiden** [comment] 2020-05-27 07:49
Just started the app and this is what I see:
![Screenshot_20200527-094830](https://user-images.githubusercontent.com/22770524/82992339-4cab6800-9fff-11ea-96fb-8346d725b4a8.png)

**Comment by johantiden** [comment] 2020-05-27 07:55
But yes, lets drop the idea of too much data.

**Comment by simonpoole** [comment] 2020-05-27 08:24
> 
> 
> Just started the app and this is what I see:
> 
You have a preset filter for route relations active, I'm not quite sure what you expect to see except members of such routes.

**Comment by johantiden** [comment] 2020-05-27 08:33
That was expected but I didn't expect to see over 10000 nodes at zoom 19. FPS 6

**Comment by johantiden** [comment] 2020-05-27 08:34
I also get this a lot when panning around with Stockholm Orthophoto image layer.
![Screenshot_20200527-103134](https://user-images.githubusercontent.com/22770524/82996657-94cd8900-a005-11ea-9afa-ab76b9e5d825.png)

**Comment by johantiden** [comment] 2020-05-27 08:35
Just reporting everything I see at this point :)

**Comment by simonpoole** [comment] 2020-05-27 08:42
Data size, there are two different aspects:

- overall amount of data in memory (that is what is displayed in the debugging output on the screen), when this is high things become slower, but rendering will be largely unaffected.

- amount of data rendered in the view, if this gets too high, for example by zooming out in a high density area, rendering and frame rate will become very slow, potentially dropping to a level which makes the UI difficult to use (this could be addressed by switching to a data style that stops rendering earlier).

**Comment by simonpoole** [comment] 2020-05-27 08:48
> 
> I also get this a lot when panning around with Stockholm Orthophoto image layer.
>

Without knowing details, this is likely due to the imagery being delivered by a WMS server in PNG format and the tile size exceeding what can be passed via IPC on Android. With other words the entry in the editor layer index should be corrected to use png8 or jpeg (naturally the very large size of the tiles stresses everything including how fast the tiles can be downloaded),

**Comment by johantiden** [comment] 2020-05-27 08:54
I have no idea about the format. This is a standard layer also available in iD and JOSM. I would have guessed it's configured correctly. Maybe not.
https://www.openstreetmap.org/edit#map=19/59.34492/18.03987

**Comment by johantiden** [comment] 2020-05-27 09:08
Regarding fps, removing the background (any background) seems to improve fps the most. I can have a lot of nodes rendered and still maintain a (semi) high fps. 

![Screenshot_20200527-110434](https://user-images.githubusercontent.com/22770524/82999970-0a3b5880-a00a-11ea-9f3d-39a9337db8f2.png)

Mapbox zoom 17 outside downloaded area. Drops to 7 fps.
![Screenshot_20200527-110649](https://user-images.githubusercontent.com/22770524/83000160-45d62280-a00a-11ea-8958-3ff7f6623143.png)

No data, no background yields 333 fps.

**Comment by johantiden** [comment] 2020-05-27 09:10
I guess we have gone way side tracked now. 👯‍♂️

**Comment by johantiden** [comment] 2020-05-27 09:36
Back to the issue at hand: Maybe for now this issue could be scoped to some simple validation of data before attempting to upload. It seemed like the response I got back when trying to upload was actually from OpenStreetMap. Not sure. 

This should reduce the risk of uploading corrupt data in the long term.

**Comment by johantiden** [comment] 2020-05-27 09:37
And this would probably end up att the bottom of the backlog :)

**Comment by johantiden** [comment] 2020-05-27 12:18
`//attempt to save the day by compressing too large PNGs`
:)

**Comment by johantiden** [comment] 2020-05-27 14:21
FYI: I have built and installed the master branch now. It seems a little more stable at first glance. Still the low FPS though.

**Comment by johantiden** [comment] 2020-05-27 17:56
`Util.beep();` is super annoying. Loudness: :100: It's playing even if sound has been turned off.

(I know it's probably temporary. Just don't forget to remove it)

**Comment by simonpoole** [comment] 2020-05-27 18:25
What are you doing for it to beep? Essentially it is only used on invalid keys from a keyboard and when you try a long press in simple mode.

Note that there is no real difference in rendering and so on between 14.1 and 15.0. If you want higher fps, there are a number of tips on the website, but for example you can turn rendering of the touch areas off, reduce the number of layers, turn of icon rendering for nodes, use a style without multi-polygon rendering and so on.

**Comment by johantiden** [comment] 2020-05-27 19:28
Easy mode enabled, long press. It used to give a snack bar message in 14.1. Now it also beeps.

I just wanted to try out the PNG compression trick and see if it felt more stable! I might try to code a few tricks/hacks myself to learn where the performance is lost.

**Comment by simonpoole** [comment] 2020-08-30 17:45
Don't think there is currently anything actionable any more here.

**Closed by simonpoole** 2020-08-30 17:45 UTC
Labels: Needs clarification
