### ISSUE TITLE
do not fill values with the +ABC function

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#282] opened 2015-05-04 16:51 UTC
If i have an `highway=residential` and push the +ABC Button i get a nice collection of keys to fill.
But some already have a value filled in!

    oneway=no
    bridge=no
    tunnel=no
    cutting=no
    embankment=no
    lit=no

If a user do not check these, there will be bogus data pushed in the Database!
Could be much more stuff on amenity=fuel:
https://www.openstreetmap.org/node/2539752897 (version 2)

**Comment by simonpoole** [comment] 2015-05-05 21:09
This is mainly due to the new JOSM payment preset (and a couple of other ones that have been changed in the same way). The only sane way to fix this is to change the default value for the tag to an empty string which will lead to the tags being deleted if not explicitly set. The problem is a general issue with the presets and not just with the +ABC function.

**Comment by simonpoole** [comment] 2015-05-06 22:33
I have a fix for this, which is not super elegant but works reaonably well.. 

On the one hand its a small bug fix to the preset code for check elements and adding disable_off="true" for such elements. This will not cover all such cases (aka those not using check elements) but likely most.

**Comment by MarcusWolschon** [comment] 2015-05-07 09:52
Great!
Am 07.05.2015 00:33 schrieb "simonpoole" <notifications@github.com>:

**Comment by simonpoole** [comment] 2015-05-08 10:17
"Fixed" see https://github.com/MarcusWolschon/osmeditor4android/commit/bc4bd0c4d8057048fb7bd0bd1e7fca9849b6eb55 and https://github.com/simonpoole/beautified-JOSM-preset

Note: there are likely more presets that would benefit from changing them to "check" objects, if you find any please feel free to point them out.

**Closed** 2015-05-08 10:17 UTC
Labels: bug, Priority-High, Type-Defect

**Comment by HolgerJeromin** [comment] 2015-05-08 17:20
Thank you!
