### ISSUE TITLE
Can't paste object after downloading new area

### ISSUE THREAD

**Issue by ltog** [MarcusWolschon/osmeditor4android#1005] opened 2019-10-05 18:13 UTC
## Vespucci Version
13.1.8

## Download source
F-Droid (?)

## Device (Manufacturer and Model)
Fairphone 2

## Android Version 
Android 7.1.2 : Fairphone Open OS (not the default one)

## Behaviour/Symptoms
I can not copy and paste objects when I download a new area in between.

## Expected Behaviour
It should be possible to do that.

## How to recreate

1. Download some data
2. Select an object
3. Select `Copy` in menu
4. Choose upload/download menu -> Download current view
5. Choose big + button
6. Menus `Paste object` and `Paste multiple times` are missing

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information
I know that one can use the menu `Add current view to download` but this adds more object to memory...

**Comment by simonpoole** [comment] 2019-10-06 22:31
This isn't really a bug, as it is so by design. The copy op simply stores a reference to the object, pasting then actually makes the copy. Given that 14.0 changes things that merging data is the default downloading process, I somewhat doubt that changing the semantics makes sense now.

**Comment by simonpoole** [comment] 2019-10-21 11:27
> 
> 
> This isn't really a bug, as it is so by design. The copy op simply stores a reference to the object, pasting then actually makes the copy.

This is actually no longer true so it should be possible to maintain the objects over complete reloads now.

**Comment by simonpoole** [comment] 2020-05-15 15:47
Addressed in https://github.com/MarcusWolschon/osmeditor4android/commit/1f5504f5e5914994bf450f23a2734f14b1317941

**Closed by simonpoole** 2020-05-15 15:47 UTC
Labels: Enhancement
