### ISSUE TITLE
Crashes when downloading area (OSMOSE)

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1036] opened 2019-11-08 06:19 UTC
Description:
---

Crashing when downloading certain area with our without clear.

Device info:
---
<table>
<tr><td>App version</td><td>14.0.3.0</td></tr>
<tr><td>App version code</td><td>1305</td></tr>
<tr><td>Android build version</td><td>A405FNXXU2ASJ1</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PPR1.180610.011.A405FNXXU2ASJ1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>a40</td></tr>
<tr><td>Device model</td><td>SM-A405FN</td></tr>
<tr><td>Device product name</td><td>a40eea</td></tr>
<tr><td>Device hardware name</td><td>exynos7885</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>kudlav</td></tr>
</table>

**Comment by kudlav** [comment] 2019-11-08 06:21
this area (Faculty of Information Technology, Brno University of Technology):
https://www.openstreetmap.org/?mlat=49.22770&mlon=16.59498#map=17/49.22770/16.59498
https://www.openstreetmap.org/?mlat=49.22578&mlon=16.59853#map=17/49.22579/16.59853

**Comment by simonpoole** [comment] 2019-11-08 07:42
Seems as if this is caused by OSMOSE having illegal ids in the download, if the error is still happening can you test if turning of OSMOSE in the task configuraion fixes the issue (naturally we shouldn't crash on illegal input, fixing that now).

**Comment by simonpoole** [comment] 2019-11-08 08:28
Crash fixed (hopefully) in https://github.com/MarcusWolschon/osmeditor4android/commit/26d2524f5c0e9f38eeb2e51e768cff999a2b0f56

**Comment by simonpoole** [comment] 2019-11-08 09:46
See https://twitter.com/osmose_qa/status/1192727531138498561 totally unannounced, not backwards compatible and will likely lead to us removing OSMOSE support.

**Comment by kudlav** [comment] 2019-11-08 12:04
I can confirm, that it works fine after disabling issues downloading.

--
Vladan Kudláč

Dne pá 8. 11. 2019 10:46 uživatel Simon Poole <notifications@github.com>
napsal:

**Comment by simonpoole** [comment] 2019-11-13 13:38
The specific issue was fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/26d2524f5c0e9f38eeb2e51e768cff999a2b0f56

**Closed by simonpoole** 2019-11-13 13:38 UTC
