### ISSUE TITLE
Append - wrong end of way chosen

### ISSUE THREAD

**Issue by johantiden** [MarcusWolschon/osmeditor4android#1302] opened 2020-12-13 19:12 UTC
## Vespucci Version
15.1 play store
```
Vespucci 15.1.0
Flavor: current
Maximum avaliable memory 536870912
Total memory used 71266704
Tile Cache ESRIWORLDIMAGERYCLARITY usage Size 66846720 of maximum 67108864 #entries 255
State file size 3452180 last changed 2020-12-13 19:04:10
Bug state file size 2350 last changed 2020-12-13 19:04:10
Relations (current/API): 489/0
Ways (current/API): 3092/0
Nodes (current/Waynodes/API): 39133/38906/0
Available location providers
passive enabled true
network enabled true
gps enabled true
```

## Device (Manufacturer and Model)
Oneplus 8 Pro

## Android Version 
11

## Behaviour/Symptoms
Wrong end (south) of way used when appending

## Expected Behaviour
The way is extended to reach the other way, from the north point. 

## How to recreate
I don't know the state my app is in. The north end has a higher ID than the south end. 

1. Select way
2. Click the append icon
3. Click on north end of way
4. Click on another way 

See attached video 

[video](https://photos.app.goo.gl/BL1RDV14cCnEtnqJ9)

**Comment by johantiden** [comment] 2020-12-13 19:23
I can reproduce it with new ways


Just create a new way with two nodes. Append from the first point. The is extended from the second node instead.

**Comment by simonpoole** [comment] 2020-12-13 20:07
Thank for the report, fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/b260b6d6a154f0dc30c50e35742c82e73430bba2

**Comment by johantiden** [comment] 2020-12-13 21:08
Reproduced in `bc9ed3202`. Fixed in `b260b6d6a`! Good job!

**Comment by johantiden** [comment] 2020-12-13 21:26
I see some other weird bahavior though. The "done" FAB doesn't seem to work in append mode for me. It works in other modes, like creating a new path.

**Comment by johantiden** [comment] 2020-12-13 21:27
And for UX, the confirmation `onBackPressed` is pretty annoying.

**Comment by simonpoole** [comment] 2020-12-13 21:58
> I see some other weird bahavior though. The "done" FAB doesn't seem to work in append mode for me. It works in other modes, like creating a new path.

That is a regression caused by the fix, fixing in turn currently.

**Comment by simonpoole** [comment] 2020-12-13 22:52
So that's fixed too, note that the "conventional" way of exiting that mode by clicking again on the last node continues to work even after the UI and refactoring changes.

**Closed** 2020-12-15 01:09 UTC
Labels: Defect, FIXED
