### ISSUE TITLE
Crashes for basic operations

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#811] opened 2018-12-10 15:40 UTC
Description:
---

I encountered reproducible crashes on searching for preset entries and adding tags manually.

I send crash reports.

Device info:
---
<table>
<tr><td>App version</td><td>12.0.0.2</td></tr>
<tr><td>App version code</td><td>900</td></tr>
<tr><td>Android build version</td><td>V8.0.3.0.0.MCECNDG</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>prada</td></tr>
<tr><td>Device model</td><td>Redmi 4</td></tr>
<tr><td>Device product name</td><td>prada</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by matkoniecz** [comment] 2018-12-10 15:42
To make it more clear: adding any tag that I tried crashes Vespucci. For example amenity=parking

**Comment by simonpoole** [comment] 2018-12-10 15:53
Did you submit a crash dump?

**Comment by matkoniecz** [comment] 2018-12-10 15:54
Yes, multiple. I can generate more if that would be useful.

**Comment by simonpoole** [comment] 2018-12-10 15:58
> 
> 
> Yes, multiple. I can generate more if that would be useful.
Not necessary, found the issue.

**Comment by simonpoole** [comment] 2018-12-10 16:24
2nd time I've fallen in to this specific trap, the crash is caused by using a Java 8 specific method that is not supported on older Android versions (but nothing complains when linting etc). 

Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/292e418264f2c25fbbbd1e397e9b1eb03a963c54

**Closed by simonpoole** 2018-12-10 16:24 UTC

**Comment by matkoniecz** [comment] 2018-12-10 19:48
Good to know that crappiness of my phone is sometimes useful :)

**Comment by simonpoole** [comment] 2018-12-11 00:13
In any case a fixed build is available from the playstore now. 

Currently the automated tests don't run on Android 6 or else the issue would have been caught.

**Comment by matkoniecz** [comment] 2018-12-11 00:47
Yes, new version works well :)
