### ISSUE TITLE
Notes not fully exported

### ISSUE THREAD

**Issue by historicbruno** [MarcusWolschon/osmeditor4android#1155] opened 2020-04-10 04:07 UTC
## Vespucci Version
14.1.1.0

## Download source
F-Droid

## Device (Manufacturer and Model)
Samsung SM-J727T1

## Android Version 
8.1.0

## Behaviour/Symptoms
When attempting to export a large number of new, open notes to an .osn file, only a partial list occurs.

## Expected Behaviour
The exported .osn should contain all notes according to the menu option.

## How to recreate
I created several hundred notes in Vespucci during a survey, intending to export them to .osn and import in JOSM. All notes are new and open, and regardless of which menu option I use, only some of the notes are exported. Only my own local notes are present, I haven't downloaded any others.

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information
The app crashed a few times while selecting/unselected notes, causing some data loss, but I'm not sure it's related to this bug. I filed a separate report for that crash. The notes I want are all visible in Vespucci (except a few that were lost in crashes), but not all exported.

**Comment by simonpoole** [comment] 2020-04-10 09:15
The regression that causes crashes selecting a Note is fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/5034ea02217bd0ba32daedeee73aae056f8d35ad and will be included in 14.1.3 Unluckily the build process on F-Droid is rather unpredictable right now, so it might take a bit till it is available there (@Bubu).

The incomplete saving is nearly guaranteed to be due to the crash, as the in-memory state may have not been written to on device when the crash occurred, in any case I wasn't able to recreate the behaviour.

Thanks for the report.

**Closed by simonpoole** 2020-04-10 09:15 UTC

**Comment by historicbruno** [comment] 2020-04-10 12:07
Thanks!

Then I'll assume the non-exported notes are "lost", and copy them manually into JOSM while I can. If this happens again, maybe I'll have better steps to reproduce it.

**Comment by simonpoole** [comment] 2020-04-10 12:14
Well if they are being displayed in principle they should still be available (there's no magic going on, so the positions of the notes will be from the in memory store). Could you try another export and then immediately go to the debug page and submit a crash dump (that includes a large bit of the Android log and may indicate if something is going wrong).

**Comment by simonpoole** [comment] 2020-04-10 12:36
Follow up question: have you actually checked the generated file for presence (or lack of it) of the missing Notes?

**Comment by historicbruno** [comment] 2020-04-10 13:15
You're right, the data is there in the .osn file, but not imported by JOSM!

**Comment by simonpoole** [comment] 2020-04-10 13:25
Could you send me the file (or attach it to this issue), so that I can have a look at what is going on?

**Comment by historicbruno** [comment] 2020-04-10 13:44
It seems many note IDs are duplicated in the exported .osn, I'll send you the file for you to test.

**Comment by historicbruno** [comment] 2020-04-10 13:54
https://gist.github.com/historicbruno/e1ad0e6b71264b15d22cd0b8eb401502

**Comment by simonpoole** [comment] 2020-04-10 14:50
Ahhhh -that- could be crash related in that the state of the id counter got lost during the crashes. 

I should be able to renumber the file and hen everything should be OK.

**Comment by simonpoole** [comment] 2020-04-10 15:36
With a bit of xslt magic:

https://gist.github.com/simonpoole/75280e6b1cefa65aff062690e225faed

**Comment by historicbruno** [comment] 2020-04-10 17:25
That's fixed it, thanks again!
