### ISSUE TITLE
Easy cardinal direction input and rendering (was Surveillance camera node)

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2364] opened 2023-08-02 18:10 UTC
Description:
---

Hi, First thanks the App ist great. I'm using it currently to map surveillance camera and I'm missing to things to have a smooth experience. First it would be nice the see camera direction as on OSM website and second to be able to read the direction of the phone to fill that tag when next to a camera. Maybe there is already those options and I didn't find them. Thanks

Device info:
---
<table>
<tr><td>App version</td><td>19.0.3.0</td></tr>
<tr><td>App version code</td><td>2406</td></tr>
<tr><td>Android build version</td><td>LTE_C01091.12_NE_S42_2.016.00</td></tr>
<tr><td>Android release version</td><td>12</td></tr>
<tr><td>Android SDK version</td><td>31</td></tr>
<tr><td>Android build ID</td><td>SP1A.210812.016 release-keys</td></tr>
<tr><td>Device brand</td><td>Cat</td></tr>
<tr><td>Device manufacturer</td><td>Cat</td></tr>
<tr><td>Device name</td><td>S42</td></tr>
<tr><td>Device model</td><td>S42</td></tr>
<tr><td>Device product name</td><td>S42</td></tr>
<tr><td>Device hardware name</td><td>mt6761</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/daukus1"/>daukus1</A></td></tr>
</table>

**Comment by Discostu36** [comment] 2023-08-03 21:17
Duplicate of #1682?

**Closed** 2024-05-22 14:24 UTC
Labels: Enhancement
