### ISSUE TITLE
Add preferences searcher function

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2453] opened 2023-12-11 09:44 UTC
The user wants to search for a particular preference. There are perhaps a hundred or more preferences. It would be great if there was a search box for preferences.

One would think 'I'll just simply search the manual, and then I'll have an idea of where in the preferences that item might be."

However the in-app manual doesn't have a search button either.

And in fact it is very hard from the app to get to the documentation website where one can finally search for items. Everything just steers the user to the built-in help menus.

**Comment by simonpoole** [comment] 2023-12-11 10:15
Duplicate of https://github.com/MarcusWolschon/osmeditor4android/issues/704

**Closed by simonpoole** 2023-12-11 10:15 UTC
Labels: Enhancement
