### ISSUE TITLE
Way rendering after way merge

### ISSUE THREAD

**Issue by blackboxlogic** [MarcusWolschon/osmeditor4android#945] opened 2019-07-15 14:55 UTC
## Vespucci Version
Vespucci 13.1.0
Flavor: current
Maximum avaliable memory 536870912
Total memory used 28092330
Tile Cache ESRIWORLDIMAGERYCLARITY usage Size 6815744 of maximum 67108864 #entries 26
State file size 445919 last changed 2019-07-14 20:42:04
Bug state file size 41586 last changed 2019-07-14 20:42:04
Relations (current/API): 10/0
Ways (current/API): 675/1
Nodes (current/Waynodes/API): 6277/6950/0
Available location providers
passive enabled true
gps enabled true
network enabled true

## Download source
Google play store, beta tester

## Device (Manufacturer and Model)
Google pixel 3

## Android Version 
9

## Behaviour/Symptoms
After two ways are merged, panning the screen so that the previously shared point is out of view can cause the new way to un-render.

## Expected Behaviour
After merging, every part of a way should render when it is located on the screen.

## How to recreate
* Find two ways A...B and B...C that share a common end point B.
* Delete all tags from way A...B (to ensure tag conflicts don't prevent way merging)
* On the map view, select way A...B
* Tap the merge button (notice that way B...C becomes highlighted as a merge-with option)
* Tap way B...C to initiate the way merge.
* Pan the map view so that point B is out of view (try panning the point off of each screen edge) 
* Observe that way A...C disappears from the screen even when part of it should still be in the view.

## Crash dump submitted (no or yes + date)
No crash

## Any other potentially relevant information
If the change set with the merged way us uploaded to OSM, then you download that area, it renders correctly again.

**Comment by simonpoole** [comment] 2019-07-15 15:42
Can't recreate based on the description. 

Could you check that you don't have any filters turned on or a using a mode that uses one (indoor mode or C-Mode).

A video of this happening might be helpful.

**Comment by blackboxlogic** [comment] 2019-07-15 22:53
Exhibit A: http://imgur.com/gallery/lQsEvvg

**Comment by simonpoole** [comment] 2019-07-16 00:09
Ok I can recreate with exactly that sequence on exactly those two ways, but for example removing the tags from the longer way and then merging works as expected. 

There is an oddity if I look at the generated data in the case of the failure, but imho nothing that should make a correct upload fail (aka the merged way seems to be correct). 

A fix and root cause analysis will have to wait to next week as I'm on vacation.

**Comment by blackboxlogic** [comment] 2019-07-16 00:22
The **upload succeeds** and the uploaded **data appears correct** so I should have enphasised that this is only a rendering issue (and likely low importance).
I hope your vacation satisfies.

**Comment by simonpoole** [comment] 2019-07-22 14:06
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/8e3c80305b2fa8183e1fa081898e171230753f9a

**Closed by simonpoole** 2019-07-22 14:06 UTC
Labels: Defect, High Priority
