### ISSUE TITLE
Vespucci has problems on (my) Sony Xperia XZ (F8332) with Android 7.1.1 and external SD-Card

### ISSUE THREAD

**Issue by versat** [MarcusWolschon/osmeditor4android#608] opened 2017-09-28 07:19 UTC
## Vespucci Version
0.9.9r1300

## Device (Manufacturer and Model)
Sony Xperia XZ (F8332)
This is the version of the XZ with 64 GB internal SD-Card and two SIM slots (of which one can, and is on my device, used for an additional external SD-Card).

## Android Version 
Android 7.1.1, latest official version from Sony

## Behaviour/Symptoms
Directly at startup of vespucci an error message is shown and the error report window is opened.
The error message says (in German):
"/storage/3335-6438/Android/data/de.blau.android/files ist nicht von Vespucci beschreibbar.
Dies könnte ein Rechteproblem oder ein technisches Problem mit dem Gerät sein"
Translated to english by me:
"/storage/3335-6438/Android/data/de.blau.android/files is not writable by Vespucci.
This could be a rights issue or a technical problem with the device"
Sometimes Vespucci then is immediately closed automatically, sometimes Vespucci works without problems but no background tiles or overlay tiles are shown.
The path shown in the error message is on the external SD-Card. Other apps do not have problems to store their tiles and resources there.
Vespucci seems to automatically use the external SD-Card, because i have not told it to do so (but i like that behaviour if it would work).
I have checked that the complete path has successfully been created by Vespucci.
There is plenty of space on the internal and external SD-Card (many, many GBs), so this can not be a problem.
When Vespucci starts for the first time it asks for two permissions (position and files/media). I have allowed them both.
The messages asking for permissions are shown AFTER the error message is shown (could this be a problem?). But even after granting access and then restarting the app the error message still appears.
Deleting cache and data does not help.
Uninstalling the app and reinstalling it does not help.
I have registered for the Beta version and tried it, but it did not help.

## Expected Behaviour
No error message. Background and overlay tiles are downloaded and shown.

## How to recreate
Just start vespucci on a Sony Xperia XZ with Android 7.1.1 (maybe the external SD-Card is necessary to reproduce it).

## Crash dump submitted (no or yes + date)
yes, 28.09.2017 about 06:57 UTC
Description added: Sony Xperia XZ, Android 7.1.1, versat

## Any other potentially relevant information
I would be happy if i could help in any way, maybe by trying a debug version or so.

**Comment by simonpoole** [comment] 2017-09-28 09:02
Thanks for the report (no need to translate from German btw).

Unluckily Android storage is a bit iffy, and tends to be very manufacturer dependent.

As you correctly noticed we try to store the tiles on external storage if possible, based on the assumption that this is in general preferable, even if slower.

Crash dump (unluckily not helpful)

android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:199)
at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:808)
at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:793)
at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:696)
at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:711)
at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:704)
at de.blau.android.util.CustomDatabaseContext.openOrCreateDatabase(CustomDatabaseContext.java:63)
at de.blau.android.util.CustomDatabaseContext.openOrCreateDatabase(CustomDatabaseContext.java:57)
at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
at de.blau.android.services.util.MapTileProviderDataBase.<init>(MapTileProviderDataBase.java:128)
at de.blau.android.services.util.MapTileFilesystemProvider.<init>(MapTileFilesystemProvider.java:60)
at de.blau.android.services.MapTileProviderService.init(MapTileProviderService.java:105)
at de.blau.android.services.MapTileProviderService.onCreate(MapTileProviderService.java:45)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:3255)
at android.app.ActivityThread.-wrap5(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1598)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:241)
at android.app.ActivityThread.main(ActivityThread.java:6274)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

Log

09-28 08:56:32.486 D/TaskStorage(16177): getTasks result count (no BB) 0
1	09-28 08:56:32.541 D/AdvancedPrefDB(16177): #prefs 1
2	09-28 08:56:32.541 D/AdvancedPrefDB(16177): Reading pref 0 OpenStreetMap
3	09-28 08:56:32.542 D/AdvancedPrefDB(16177): Adding preset OpenStreetMap
4	09-28 08:56:32.542 I/de.blau.android.presets.Preset(16177): Loading default preset
5	09-28 08:56:32.543 I/PresetIconManager(16177): External default asset package not installed
6	09-28 08:56:32.544 E/PresetIconManager(16177): Could not load asset preset_de_DE.po from any source [externalAssetPackage=null]
7	09-28 08:56:32.706 D/MapTileProviderService(16196): candidate storage directory /storage/emulated/0/Android/data/de.blau.android/files
8	09-28 08:56:32.713 E/SQLiteLog(16196): (14) cannot open file at line 32460 of [69906880ce]
9	09-28 08:56:32.713 E/SQLiteLog(16196): (14) os_unix.c:32460: (2) open(/storage/emulated/0/Android/data/de.blau.android/files/databases/osmaptilefscache_db.db) -
10	09-28 08:56:32.714 E/SQLiteDatabase(16196): Failed to open database '/storage/emulated/0/Android/data/de.blau.android/files/databases/osmaptilefscache_db.db'.
11	09-28 08:56:32.714 E/SQLiteDatabase(16196): android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
12	09-28 08:56:32.714 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
13	09-28 08:56:32.714 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
14	09-28 08:56:32.714 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:199)
15	09-28 08:56:32.714 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
16	09-28 08:56:32.714 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
17	09-28 08:56:32.714 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
18	09-28 08:56:32.714 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:808)
19	09-28 08:56:32.714 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:793)
20	09-28 08:56:32.714 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:696)
21	09-28 08:56:32.714 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:671)
22	09-28 08:56:32.714 E/SQLiteDatabase(16196): at de.blau.android.services.util.MapTileProviderDataBase.exists(MapTileProviderDataBase.java:489)
23	09-28 08:56:32.714 E/SQLiteDatabase(16196): at de.blau.android.services.MapTileProviderService.init(MapTileProviderService.java:75)
24	09-28 08:56:32.714 E/SQLiteDatabase(16196): at de.blau.android.services.MapTileProviderService.onCreate(MapTileProviderService.java:45)
25	09-28 08:56:32.714 E/SQLiteDatabase(16196): at android.app.ActivityThread.handleCreateService(ActivityThread.java:3255)
26	09-28 08:56:32.714 E/SQLiteDatabase(16196): at android.app.ActivityThread.-wrap5(ActivityThread.java)
27	09-28 08:56:32.714 E/SQLiteDatabase(16196): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1598)
28	09-28 08:56:32.714 E/SQLiteDatabase(16196): at android.os.Handler.dispatchMessage(Handler.java:102)
29	09-28 08:56:32.714 E/SQLiteDatabase(16196): at android.os.Looper.loop(Looper.java:241)
30	09-28 08:56:32.714 E/SQLiteDatabase(16196): at android.app.ActivityThread.main(ActivityThread.java:6274)
31	09-28 08:56:32.714 E/SQLiteDatabase(16196): at java.lang.reflect.Method.invoke(Native Method)
32	09-28 08:56:32.714 E/SQLiteDatabase(16196): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
33	09-28 08:56:32.714 E/SQLiteDatabase(16196): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
34	09-28 08:56:32.716 D/MapTileProviderService(16196): candidate storage directory /storage/3335-6438/Android/data/de.blau.android/files
35	09-28 08:56:32.723 E/SQLiteLog(16196): (14) cannot open file at line 32460 of [69906880ce]
36	09-28 08:56:32.723 E/SQLiteLog(16196): (14) os_unix.c:32460: (2) open(/storage/3335-6438/Android/data/de.blau.android/files/databases/osmaptilefscache_db.db) -
37	09-28 08:56:32.723 E/SQLiteDatabase(16196): Failed to open database '/storage/3335-6438/Android/data/de.blau.android/files/databases/osmaptilefscache_db.db'.
38	09-28 08:56:32.723 E/SQLiteDatabase(16196): android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
39	09-28 08:56:32.723 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
40	09-28 08:56:32.723 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
41	09-28 08:56:32.723 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:199)
42	09-28 08:56:32.723 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
43	09-28 08:56:32.723 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
44	09-28 08:56:32.723 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
45	09-28 08:56:32.723 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:808)
46	09-28 08:56:32.723 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:793)
47	09-28 08:56:32.723 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:696)
48	09-28 08:56:32.723 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:671)
49	09-28 08:56:32.723 E/SQLiteDatabase(16196): at de.blau.android.services.util.MapTileProviderDataBase.exists(MapTileProviderDataBase.java:489)
50	09-28 08:56:32.723 E/SQLiteDatabase(16196): at de.blau.android.services.MapTileProviderService.init(MapTileProviderService.java:75)
51	09-28 08:56:32.723 E/SQLiteDatabase(16196): at de.blau.android.services.MapTileProviderService.onCreate(MapTileProviderService.java:45)
52	09-28 08:56:32.723 E/SQLiteDatabase(16196): at android.app.ActivityThread.handleCreateService(ActivityThread.java:3255)
53	09-28 08:56:32.723 E/SQLiteDatabase(16196): at android.app.ActivityThread.-wrap5(ActivityThread.java)
54	09-28 08:56:32.723 E/SQLiteDatabase(16196): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1598)
55	09-28 08:56:32.723 E/SQLiteDatabase(16196): at android.os.Handler.dispatchMessage(Handler.java:102)
56	09-28 08:56:32.723 E/SQLiteDatabase(16196): at android.os.Looper.loop(Looper.java:241)
57	09-28 08:56:32.723 E/SQLiteDatabase(16196): at android.app.ActivityThread.main(ActivityThread.java:6274)
58	09-28 08:56:32.723 E/SQLiteDatabase(16196): at java.lang.reflect.Method.invoke(Native Method)
59	09-28 08:56:32.723 E/SQLiteDatabase(16196): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
60	09-28 08:56:32.723 E/SQLiteDatabase(16196): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
61	09-28 08:56:32.717 W/.android:remote(16196): type=1400 audit(0.0:36323): avc: denied { write } for name=\"files\" dev=\"ecryptfs\" ino=23068672 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:ecryptfs:s0 tclass=dir permissive=0 ppid=2505 pcomm=\"main\" pgid=2505 pgcomm=\"main\"
62	09-28 08:56:32.717 W/.android:remote(16196): type=1400 audit(0.0:36324): avc: denied { write } for name=\"files\" dev=\"ecryptfs\" ino=23068672 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:ecryptfs:s0 tclass=dir permissive=0 ppid=2505 pcomm=\"main\" pgid=2505 pgcomm=\"main\"
63	09-28 08:56:32.726 D/MapTileProviderService(16196): isExternalStorageRemovable claims dir is removeable
64	09-28 08:56:32.726 D/MapTileProviderService(16196): Setting cache size to 10 on /storage/3335-6438/Android/data/de.blau.android/files
65	09-28 08:56:32.726 I/OSMTileProviderDB(16196): creating database instance
66	09-28 08:56:32.727 W/DatabaseContext(16196): getDatabasePath(osmaptilefscache_db) = /storage/3335-6438/Android/data/de.blau.android/files/databases/osmaptilefscache_db.db
67	09-28 08:56:32.727 E/SQLiteLog(16196): (14) cannot open file at line 32460 of [69906880ce]
68	09-28 08:56:32.727 E/SQLiteLog(16196): (14) os_unix.c:32460: (2) open(/storage/3335-6438/Android/data/de.blau.android/files/databases/osmaptilefscache_db.db) -
69	09-28 08:56:32.728 E/SQLiteDatabase(16196): Failed to open database '/storage/3335-6438/Android/data/de.blau.android/files/databases/osmaptilefscache_db.db'.
70	09-28 08:56:32.728 E/SQLiteDatabase(16196): android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
71	09-28 08:56:32.728 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
72	09-28 08:56:32.728 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
73	09-28 08:56:32.728 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:199)
74	09-28 08:56:32.728 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
75	09-28 08:56:32.728 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
76	09-28 08:56:32.728 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
77	09-28 08:56:32.728 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:808)
78	09-28 08:56:32.728 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:793)
79	09-28 08:56:32.728 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:696)
80	09-28 08:56:32.728 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:711)
81	09-28 08:56:32.728 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:704)
82	09-28 08:56:32.728 E/SQLiteDatabase(16196): at de.blau.android.util.CustomDatabaseContext.openOrCreateDatabase(CustomDatabaseContext.java:63)
83	09-28 08:56:32.728 E/SQLiteDatabase(16196): at de.blau.android.util.CustomDatabaseContext.openOrCreateDatabase(CustomDatabaseContext.java:57)
84	09-28 08:56:32.728 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
85	09-28 08:56:32.728 E/SQLiteDatabase(16196): at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
86	09-28 08:56:32.728 E/SQLiteDatabase(16196): at de.blau.android.services.util.MapTileProviderDataBase.<init>(MapTileProviderDataBase.java:128)
87	09-28 08:56:32.728 E/SQLiteDatabase(16196): at de.blau.android.services.util.MapTileFilesystemProvider.<init>(MapTileFilesystemProvider.java:60)
88	09-28 08:56:32.728 E/SQLiteDatabase(16196): at de.blau.android.services.MapTileProviderService.init(MapTileProviderService.java:105)
89	09-28 08:56:32.728 E/SQLiteDatabase(16196): at de.blau.android.services.MapTileProviderService.onCreate(MapTileProviderService.java:45)
90	09-28 08:56:32.728 E/SQLiteDatabase(16196): at android.app.ActivityThread.handleCreateService(ActivityThread.java:3255)
91	09-28 08:56:32.728 E/SQLiteDatabase(16196): at android.app.ActivityThread.-wrap5(ActivityThread.java)
92	09-28 08:56:32.728 E/SQLiteDatabase(16196): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1598)
93	09-28 08:56:32.728 E/SQLiteDatabase(16196): at android.os.Handler.dispatchMessage(Handler.java:102)
94	09-28 08:56:32.728 E/SQLiteDatabase(16196): at android.os.Looper.loop(Looper.java:241)
95	09-28 08:56:32.728 E/SQLiteDatabase(16196): at android.app.ActivityThread.main(ActivityThread.java:6274)
96	09-28 08:56:32.728 E/SQLiteDatabase(16196): at java.lang.reflect.Method.invoke(Native Method)
97	09-28 08:56:32.728 E/SQLiteDatabase(16196): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
98	09-28 08:56:32.728 E/SQLiteDatabase(16196): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
99	09-28 08:56:32.728 D/MapTileProviderService(16196): Opening DB hit android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database

To complicate things tiles are downloaded by a background process which explains the asynchronicity (even though that should be handled correctly) that you saw.

Have you tried without the SD card installed (please only do this if it doesn't cause you too much trouble)?

I'm away for 10 days starting tomorrow, so won't be able to do anything about this right now.

**Comment by versat** [comment] 2017-09-28 09:14
Thanks for the fast response.
I've ejected the external SD-Card and started Vespucci again => No problems any more, tiles are loaded and shown.
Even after inserting the SD-Card again Vespucci keeps working without error messages. It seems like it furthermore uses the internal SD-Card.
I guess i will only get problems again after an update/reinstall or when deleting cache/data.
I can live with this for a while, so i wish you a nice holiday/time off :)

**Comment by simonpoole** [comment] 2017-09-28 10:02
The behaviour (using the internal card) is expected as it will prefer an existing tile database over creating a new one (what I was hoping would work for you).

Naturally this doesn't resolve the root cause, which will need some more investigation.

**Comment by simonpoole** [comment] 2017-10-12 12:42
Question @versat I'm trying to determine why verspucci tried to use the directory in question even though it wasn't able to write to it. Die you ever have an older (would have to been pre-Android 6) OS on the device and tested Vespucci on it?

**Comment by versat** [comment] 2017-10-12 12:56
No, i have bought the device about three month ago and first thing i did was updating to the latest Firmware with all the security updates. Then (with Android 7.1.1) i made a Firmwarereset.
Now the interesting part:
When switching to the new smartphone, i just used the external SDCard from my old smartphone (Sony Xperia Z2 with Android 5). I had Vespucci installed on it too, so it could really be the case that this directly already existed and the new smartphone has not created the directory.
I tried deleting the directory on the external SDCard and restarting Vespucci and it created the directory again. But this did not help.
Maybe it would have been better if i had deleted the Android directory on the external SDCard before putting it in the new device. But if i remember it correctly i have not deleted anything.

**Comment by simonpoole** [comment] 2017-10-12 17:05
Naturally the question would still be why you weren't able to write to it in the first place even if it already existed.

**Comment by versat** [comment] 2017-10-13 06:29
Yes, when Vespucci is able to create the complete path/directories, why is it not able to write into it? Is it possible/useful to open a messagebox with more details (errorcode) in this case?

**Comment by simonpoole** [comment] 2017-10-30 20:04
1304, that is rolling our now, has a fix for the above issue (but no explanation for the in general weird situation). Closing this for now.

**Closed by simonpoole** 2017-10-30 20:04 UTC
Labels: Defect, Medium Priority

**Comment by versat** [comment] 2017-11-03 12:11
I've tested the new version.
After deleting cache and data and uninstalling vespucci, i installed it again.
Now there are no more error reporting messages and the background images were loaded without problems.
When looking at the filesystem i saw that the path on the external SD Card has been created again (i've deleted it before too), but no files were in it.
The files all were created on the internal SD Card.
