### ISSUE TITLE
Split way history choice doesn't work in advanced mode

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2029] opened 2023-01-19 07:56 UTC
Description:
---

Long pressing node to choose which side of a split way keeps history doesn't work in the advanced UI mode. It starts a new way from that node instead and cancels the split. 

Reverting to simple mode fixes the issue.

Device info:
---
<table>
<tr><td>App version</td><td>18.1.0.0</td></tr>
<tr><td>App version code</td><td>2302</td></tr>
<tr><td>Android build version</td><td>S908BXXU2BVL1</td></tr>
<tr><td>Android release version</td><td>13</td></tr>
<tr><td>Android SDK version</td><td>33</td></tr>
<tr><td>Android build ID</td><td>TP1A.220624.014.S908BXXU2BVL1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>b0s</td></tr>
<tr><td>Device model</td><td>SM-S908B</td></tr>
<tr><td>Device product name</td><td>b0sxeea</td></tr>
<tr><td>Device hardware name</td><td>s5e9925</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/letsridebikes"/>letsridebikes</A></td></tr>
</table>

**Comment by HolgerJeromin** [comment] 2023-01-19 08:00
duplicate of fixed #2017 ?

**Comment by simonpoole** [comment] 2023-01-19 08:49
> duplicate of fixed #2017 ?

Yes this is fixed (will be in the next maintenance release).

**Closed by simonpoole** 2023-01-19 08:49 UTC
