### ISSUE TITLE
Precise mapping ability

### ISSUE THREAD

**Issue by brbar** [MarcusWolschon/osmeditor4android#2127] opened 2023-02-12 07:12 UTC
App does not allow to map nodes precisely compared to desktop mappers just because the node location is hidden by your finger. I would suggest to create some spot on the screen where you will be able to move your finger and the previously selected node which located way outside from that area will be moved. This way you will be able to choose exact location for your node.

**Comment by simonpoole** [comment] 2023-02-12 12:11
Duplicate of https://github.com/MarcusWolschon/osmeditor4android/issues/2125

But as said there, the functionality has been available for a good decade.

**Closed** 2023-02-12 12:11 UTC
Labels: Enhancement
