### ISSUE TITLE
Data Styling – a validation styling with code 8 results in ways without any strokeWidth

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1371] opened 2021-04-07 23:53 UTC
## Vespucci Version
15.2.0

## Behaviour/Symptoms
I appreciate a lot the improvements which came with Vespucci v15.2.0 and Data Styling, specially regarding the new (enhanced) labelling features! I already use it in my own data styling files ...

I also played around a little with **validation styling by codes**, and the standard styles already contains one line which gives nodes with an AGE validation error code 2 a yellow colour (instead of the standard magenta/pink) – this workes as expected:

`<feature type="validation" code="2" updateWidth="true" widthFactor="1.5" color="ffffe000" style="STROKE" cap="BUTT" join="MITER" />`

I added a line for code 8 (= MISSING_TAG) to have another special colour for such nodes (here a800ff = violet):

`<feature type="validation" code="8" updateWidth="true" widthFactor="1.5" color="ffa800ff" style="STROKE" cap="BUTT" join="MITER" />`

And it also worked for nodes e.g. shops with a missing name, but the **negative side effect** was that roads with missing names got a stroke width of nearly zero, like a wireframe graphic line (a very thin line in violet is visible). It looks like that:

![Validation_code_styling_with_code_8](https://user-images.githubusercontent.com/48966999/113945960-b2fc3c00-9807-11eb-87b0-a851a4ffbd7a.jpg)

And I found no way to prevent this .... I tried adding "strokeWith=1.5", removed updateWidth and widthFactor or tried codes like this:

```
<feature type="validation" code="8" >
	<feature type="node" tags="shop" updateWidth="true" widthFactor="1.2" color="ffa800ff" style="STROKE" cap="BUTT" join="MITER" />
</feature>
```

Or:
```
<feature type="problem_node_tagged" updateWidth="true" widthFactor="1.5" color="ffff00ff" style="FILL" cap="BUTT" join="MITER">
	<feature type="validation" code="8" updateWidth="true" widthFactor="1.5" color="ffa800ff" style="STROKE" cap="BUTT" join="MITER" />
</feature>
```
But that doesn't seem to be possible ... and nothing worked.

Is this a bug or am I missing something?

**Comment by simonpoole** [comment] 2021-04-09 07:35
The problem is likely (haven't been able to test yet) that the zoom dependent width changing isn't applied to the validation styles due to an oversight. You should be able to to set updateWidth="false" and increase strokeWidth as a workaround though.

**Comment by jajajaneeneenee** [comment] 2021-04-10 01:08
Your proposed workaround did work. I had to set updateWidth="false" and strokeWidth at least to 6.0 or 8.0 to get a width nearly as thick as before with the standard "problem colouring" in a higher zoom level, and of course it has a fixed width now ... and it's too thick in lower zoom levels .. but for a workaround it's ok.

By the way, it does not only concern error code 8, but also the other numbers. But I think that's already clear for you ...

And one small question: can the strokeWidth of the coloured outline around NODES be modified in any way? It doesn't seem to be affected by strokeWidth (the attribute is only for ways I guess).

**Comment by simonpoole** [comment] 2021-04-10 17:46
> And one small question: can the strokeWidth of the coloured outline around NODES be modified in any way? It doesn't seem to be affected by strokeWidth (the attribute is only for ways I guess).

IIRC that is defined in problem_node_tagged but I may be mistaken.

**Comment by simonpoole** [comment] 2021-04-10 17:49
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/12f7e65852de8913d77ad498eea1806533d322c7

**Closed by simonpoole** 2021-04-10 17:49 UTC
Labels: Defect, Medium Priority
