### ISSUE TITLE
Undownloaded areas always still dimmed

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2258] opened 2023-04-29 02:07 UTC
As you see, I don't have the box checked:
![Screenshot_20230429-100205.jpg](https://user-images.githubusercontent.com/1230959/235278675-f5a8452f-e707-4cc5-9ad9-b3a245ba3a3b.jpg)

But still, undownloaded areas are still dimmed:

![Screenshot_20230429-100112.jpg](https://user-images.githubusercontent.com/1230959/235278716-77a51a56-3c45-4279-8b32-68dc738badc6.jpg)

**Comment by jidanni** [comment] 2023-04-29 02:12
(It wouldn't be so bad if, instead of just dimming, also have an option to just draw a big orange rectangle around non- downloaded areas... 
That way at least the rest of the map would still be nice and bright. 
Yes, then there needs to be indication of which side of that border is which.
)

**Comment by simonpoole** [comment] 2023-04-29 06:03
Duplicate of https://github.com/MarcusWolschon/osmeditor4android/issues/2244 ... just two lines down.

**Closed by simonpoole** 2023-04-29 06:03 UTC
