### ISSUE TITLE
Allow quick glimpse at 'erroring' messages

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1804] opened 2022-09-20 18:09 UTC
When we see an orange message saying some imagery is "erroring", it would be great to be have way too see a few of those errors.

Besides tapping the orange message itself, maybe have an additional menu item to show the last few errors, and the times involved if that's not too much overhead.

That way the user could have a quick check if it's a HTTP 403, or 404 etc. without the user needing to do fancy debugging.

Raw HTTP return code numbers would be good enough, if that's all you got.

**Comment by jidanni** [comment] 2022-09-20 18:37
Currently touching the disappearing orange message, actually just touches the items underneath it.

**Comment by simonpoole** [comment] 2022-09-20 20:26
> Currently touching the disappearing orange message, actually just touches the items underneath it.

Please stop complaining about standard Android user interface elements showing standard Android user interface element behaviour.

**Comment by simonpoole** [comment] 2022-09-20 20:30
Duplicate of https://github.com/MarcusWolschon/osmeditor4android/issues/1731

**Closed by simonpoole** 2022-09-20 20:30 UTC
Labels: duplicate
