### ISSUE TITLE
Bing imagery never loads anymore

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1784] opened 2022-09-19 00:17 UTC
The Bing imagery just never seems the load anymore these days. Had to use the ESRI imagery instead. It used to load here in Ontario but for some reason not anymore!

**Comment by jidanni** [comment] 2022-09-19 02:00
Now it is suddenly okay again, but who knows for how long.

**Comment by simonpoole** [comment] 2022-09-19 05:15
What exactly do you expect me to do about Bings oprtational issues?

**Comment by jidanni** [comment] 2022-09-19 23:13
(I can't tell where the problem was coming from. There was no other messages at all.)

**Comment by jidanni** [comment] 2022-09-20 14:23
Today is it is happening on and off again. It's exactly like I selected the word "none" for imagery.
I don't know how Bimg could manage to insert 100% transparent tiles, just for me.

**Comment by jidanni** [comment] 2022-09-20 14:52
![Screenshot_20220920-105131_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/191291217-39f46e71-7f0b-42f6-aeb1-ffd2f8fb9f65.jpg)
Exactly like "none", except for the logo at the bottom.

**Comment by jidanni** [comment] 2022-09-20 14:56
Vespucci 18.0.2
Flavor: current
Target SDK: 31
Maximum avaliable memory 268435456
Total memory used 35599395
Tile Cache BING usage Size 0 of maximum 33554432 #entries 0
State file size 147152 last changed 2022-09-20 14:53:24
Bug state file size 4688 last changed 2022-09-20 14:53:24
Relations (current/API): 5/0
Ways (current/API): 337/0
Nodes (current/Waynodes/API): 2136/2128/0
Available location providers
passive enabled true
network enabled true
fused enabled true
gps enabled true
Configured layers
IMAGERY 0 IMAGERY true BING
OSMDATA 1 OSMDATA true null

**Comment by HolgerJeromin** [comment] 2022-09-20 14:58
> (I can't tell where the problem was coming from. There was no error messages at all.)

No error, but a clear sign that you have no imagery :-)
Pushing a technically message "Bing does not work because of xy" will not help you.

**Comment by jidanni** [comment] 2022-09-20 15:17
Bing tiles load great today in the other apps:
![Screenshot_20220920-111553_All-In-One Offline Maps.jpg](https://user-images.githubusercontent.com/1230959/191297491-ab9c799e-7e1a-495a-9844-3f2ac92288a4.jpg)

**Comment by jidanni** [comment] 2022-09-20 15:21
Okay, I did "flush tile cache" and voila,  Bing's back! But let's see for how long...

**Comment by jidanni** [comment] 2022-09-20 17:41
Okay, I think I found a workaround. First set of visibility of the Bing layer to eyes closed.

Now close the app. Now launch it again. Now set the visibility to eyes open.

What up. From 0 the cached total jumps very high and suddenly all the imagery is back again.

Vespucci 18.0.2
Flavor: current
Target SDK: 31
Maximum avaliable memory 268435456
Total memory used 38260480
Tile Cache BING usage Size 8126464 of maximum 33554432 #entries 31
State file size 171669 last changed 2022-09-20 17:37:32
Bug state file size 9292 last changed 2022-09-20 17:37:32
Relations (current/API): 5/0
Ways (current/API): 411/0
Nodes (current/Waynodes/API): 2569/2564/0
Available location providers
passive enabled true
network enabled true
fused enabled true
gps enabled true
Configured layers
IMAGERY 0 IMAGERY true BING
OSMDATA 1 OSMDATA true null
TASKS 2 TASKS true null

**Comment by jidanni** [comment] 2022-09-20 18:25
My workaround above seems to consistently work! This must have something to do with the special treatment I read about where you sent Bing some cookie or something different than the other layers. Anyway  somehow the app  **internally** sets the visibility toggled off so one must "toggle it back on" when the app is open etc.

**Comment by jidanni** [comment] 2022-09-20 19:17
(Sometimes) just toggling It off, (eyeball closed) and then toggling it back on solves the problem too!

**Comment by simonpoole** [comment] 2022-09-20 20:40
It is likely that the failures you are seeing are caused by multiple independent issues:

- the call to Bings metadata API failing, this is tried once asynchronously on app start up, if it fails no tiles will be loaded. The app needs to be fully restarted to recover from this,
- tiles failing in a way that causes then to be marked as not available in the on device tiles cache. Flushing the cache will cause the tiles to be retried.

**Closed** 2022-09-27 13:12 UTC
Labels: invalid

**Comment by jidanni** [comment] 2023-02-02 23:08
My Miracle Solution worked perfectly again today: when at wits end do this:

Close the eyeball on Bing, close the app, open the app, open the eyeball on Bing.

Anyway, I still need to do this even in the latest version of Vespucci on Google play.
