### ISSUE TITLE
Vespucci seems to be loudly beeping sometimes

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1207] opened 2020-08-01 06:20 UTC
Description:
---

I have absolutely no idea what is going on but sometimes during editing, especially on completing download my phone will beep loudly.

It is always during Vespucci editing.

I use almost entirely default settings, nothing what I enabled should cause loud beeping.

I admit that it may be something else but it happens solely during Vespucci editing

Point @matkoniecz

Device info:
---
<table>
<tr><td>App version</td><td>15.0.0.6</td></tr>
<tr><td>App version code</td><td>1501</td></tr>
<tr><td>Android build version</td><td>V11.0.5.0.QDLMIXM</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QKQ1.191002.002.V11.0.5.0.QDLMIXM</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>daisy_sprout</td></tr>
<tr><td>Device model</td><td>Mi A2 Lite</td></tr>
<tr><td>Device product name</td><td>daisy</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by simonpoole** [comment] 2020-08-01 08:07
This is likely the replacement for the toast/snackbar if you are long pressing in "simple mode" https://github.com/MarcusWolschon/osmeditor4android/commit/f095dd5eebde5636d762c41a1796cbc564ce45f5

I'll add a note to the effect to the release notes.

**Comment by matkoniecz** [comment] 2020-08-01 10:52
Weird, I have simple mode disabled.

**Comment by simonpoole** [comment] 2020-08-01 11:32
The only other thing that beeps are undefined keyboard shortcuts.

**Comment by matkoniecz** [comment] 2020-08-01 11:42
Keyboard? Is it triggerable by gestures, multitouch or something?

**Comment by simonpoole** [comment] 2020-08-01 12:04
> 
> 
> Keyboard? Is it triggerable by gestures, multitouch or something?

Nope, naturally if something was faking keyboard input in some way it could happen too. One note "keyboard" includes any physical buttons you have on the device, so maybe you hitting one of those?

**Comment by matkoniecz** [comment] 2020-08-02 08:50
I finally found it - when I use fingerprint sensor while Vespucci is opened

**Comment by simonpoole** [comment] 2020-08-02 08:53
Hmm, maybe there's an API for turning it off while a specific app is running.

**Comment by matkoniecz** [comment] 2020-08-02 11:54
Is it possible to not emit sounds in such case? Other apps are not doing this.

**Comment by simonpoole** [comment] 2020-08-02 12:07
> 
> 
> Is it possible to not emit sounds in such case? Other apps are not doing this.

Well it isn't clear if this is something that creates a key event with the control key pressed, which would actually lead to Vespucci beeping, or if this is simply the OS beeping for whatever reason. As I wrote above there doesn't seem to be an API for this outside of actually using the sensor for authentication, at least I've not seen anything. The other problem is that I don't have a device here with under screen finger print sensor, there are definitely no beeps on any of the devices with other types of finger print detection.

**Comment by simonpoole** [comment] 2020-08-02 13:24
Just to avoid a wild goose case here, you don't have anything installed or enabled that allows fingerprint sensor gestures?

**Comment by matkoniecz** [comment] 2020-08-02 13:39
No. I also have standard system without modifications (Android One).

**Comment by simonpoole** [comment] 2020-08-02 15:19
I can create a debug version that logs key events to see if it is something that I can catch in app.

**Comment by matkoniecz** [comment] 2020-08-02 15:35
I would be glad to run it.

**Comment by simonpoole** [comment] 2020-08-02 16:38
https://drive.google.com/file/d/164MCBWFKyHXkVz9-aV7azziuNRS9H4lR/view?usp=sharing has a line of extra debugging, produce a couple of beeps and then immediately send a crash dump. Thanks.

**Comment by simonpoole** [comment] 2020-08-04 21:03
Ping

**Comment by matkoniecz** [comment] 2020-08-06 11:58
I send debug with "#1207" included in description. Curiously, beeping is not working in debug panel.

I am hit with Google blocking apk files and 'App not Installed' error.

I tried uninstalling Vespucci and removing it from list of my apps, I tried Disabling Play Protect, I tried redownloading file what finally worked.

**Comment by simonpoole** [comment] 2020-08-06 12:32
So yes it is actually generating a key press (super weird, but OK):

> 08-06 13:56:43.523 W/de.blau.android.Main(23949): Unknown key key code 0 key event KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_UNKNOWN, scanCode=114, metaState=0, flags=0x8, repeatCount=0, eventTime=36714025, downTime=36714025, deviceId=3, source=0x101, displayId=-1 }

**Comment by simonpoole** [comment] 2020-08-06 13:35
I've updated the debug build with https://github.com/MarcusWolschon/osmeditor4android/commit/54629c4828d644c23b5dd7683489eaf3d6116854 can you test if the issue is gone?

**Comment by matkoniecz** [comment] 2020-08-06 13:39
https://drive.google.com/file/d/164MCBWFKyHXkVz9-aV7azziuNRS9H4lR/view is in trash and therefore unavailable, I will compile Vespucci from source

**Comment by simonpoole** [comment] 2020-08-06 13:43
Just a sec https://drive.google.com/drive/folders/0B9pKLmh8s1h8bFI5bGd4VnhYWkk?usp=sharing is the folder link.

**Comment by matkoniecz** [comment] 2020-08-06 13:57
Thanks! I was unable to trigger beeping :)

**Comment by simonpoole** [comment] 2020-08-06 15:18
OK, closing

**Closed by simonpoole** 2020-08-06 15:18 UTC
Labels: Needs clarification
