### ISSUE TITLE
Save incomplete GPX Tracks

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1381] opened 2021-04-16 11:12 UTC
Description:
---

A few times I have started a GPX track and paused it to continue later or to upload when I have signal.
If I close the app or don't restart the tracking for a long time I lose my data.
When running a GPX tack can you please save the data to storage when paused and also auto-save points so data is not losted?

Device info:
---
<table>
<tr><td>App version</td><td>15.2.1.0</td></tr>
<tr><td>App version code</td><td>1703</td></tr>
<tr><td>Android build version</td><td>G930FXXU8ETI2</td></tr>
<tr><td>Android release version</td><td>8.0.0</td></tr>
<tr><td>Android SDK version</td><td>26</td></tr>
<tr><td>Android build ID</td><td>R16NW.G930FXXU8ETI2</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>herolte</td></tr>
<tr><td>Device model</td><td>SM-G930F</td></tr>
<tr><td>Device product name</td><td>heroltexx</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos8890</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/deanleggo"/>deanleggo</A></td></tr>
</table>

**Comment by simonpoole** [comment] 2021-04-16 11:38
We do save the track to device storage when you pause tracking and if you terminate the app it is restored when you restart. In particular in the later case as long as the app isn't running nothing is going to or be able to remove the recording.

So the behaviour you are seeing needs to be narrowed down a bit so that we can determine if there is a bug or other issue. How long is "don't restart the tracking for a long time" ?

**Comment by deanleggo** [comment] 2021-04-16 12:46
I provided fedback via the app and saw it uploaded it to Github. Thanks for the fast reply. @simonpoole what you describe is what should happen and happens most of the time but a dozen or so times, some of my GTX tracks have been lost.

If I pause tracking I'll classify this as a session. I can have multiple sessions before 'Clear GPX track and its waypoints'. Usually I'll upload the waypoints to the OSM server before clearing.

> How long is "don't restart the tracking for a long time" ?

I 'Pause GPX tracking' and go to the home screen, the app is in the app draw, so not closed (I'm not too sure what Android classifies this as). Then an hour or two later I 'Start GPX track' again. Some times the previous session of GPX tracking is lost, but not all sessions are lost.

The last time I lost a session I was out-of-range of mobile signal, I recorded a track and hit pause and then locked my phone. I unlocked my phone and used OsmAnd to navagate. Later that night (I had closed all apps) I opened Vespucci and uploaded the data. I then realised the waypoints contained data from a session at a lighthouse (previous day) but not the session I recorded earlier today.

I do have Bing aerial imagery enabled (the only change I have made for the default) and I previously had issues with the app failing to launch. But lost tracks do not coinside when the app failed to launch.
I'll try and test when I loss data to try and narrow down where the bug may be and I hope this helps.

**Comment by simonpoole** [comment] 2021-04-16 14:09
Note: you can always export the current track to stay on the safe side while experimenting.

**Comment by deanleggo** [comment] 2021-04-19 10:08
Over the last two days I tested recording tracks. 
So the issue is when I quit the app, I loss some or all of the waypoints from a GPX track. I lost tracking data every time I quit the app. Starting, pausing, or closing the app does not loss any data.
It does not matter if I exported, uploaded, or nothing. When I quit some data is lost. Usually a sesson is lost, but once only half a session was lost.

Every time I recorded a track I had Bing images visible and have not downloaded the current view I am recording in. Over the next few days I'll try recording with Bing images disabled and/or I'll download the current view I am recording in and see if that changes the issue.

**Comment by simonpoole** [comment] 2021-04-19 10:45
Bing imagery defintely won't influence this (there was a regression a couple of releases back with retrieving Bing metadata when the device didn't have network connectivity but that has long been fixed and wouldn't have any bearing on this issue in any case).

As clarification what do you mean with "quit" the app vs. "close"?

**Comment by deanleggo** [comment] 2021-04-19 10:50
Close is when I click on the home button or switch to another app.
Quit is when I swipe the app in the app draw to terminate the app.

**Comment by simonpoole** [comment] 2021-04-19 15:20
> 
> 
> Close (stopped state) is when I click on the home button or switch to another app.
> Quit (destoryed state) is when I swipe the app in the app draw to terminate the app.

There is no guarantee that terminating the app via the app draw does anything except that it's essentially a force close, if you want to cleanly exit Vespucci you should press the back button (while on the main screen).

**Comment by deanleggo** [comment] 2021-04-20 02:38
Okay, I thought the only way to force close an app is via the settings>app page. That probably also kills all the background services.

Clicking back, the app comes up with a confirmation box and closes. But the app is still in the app draw. So far this fixes the issue, but I think it'll be good if there is a way to not have to click back to make sure the track data is saved.

**Comment by simonpoole** [comment] 2021-05-12 17:01
Tentatively fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/acc30a8d161dad2de81e525e42a8656fd84b56a8

**Comment by simonpoole** [comment] 2021-06-02 12:16
@deanleggo have you been able to test against the current version (15.2.2) from the play store?

**Comment by simonpoole** [comment] 2021-06-14 21:08
Stale, closing.

**Closed by simonpoole** 2021-06-14 21:08 UTC
Labels: Work in progress, Workaround available
