### ISSUE TITLE
Add a "clear data" choice

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1765] opened 2022-09-10 04:40 UTC
Here perhaps add a  "clear data" choice, handy for ensuring a quick startup next time we open the app, in the case that we know that we are not going to be mapping anymore in this area.
![Screenshot_20220910-003757_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/189469001-0461f71e-954c-47e0-8e0a-3a41a293a1a1.jpg)

**Comment by simonpoole** [comment] 2022-09-12 07:18
The sometime long initial load times have a near constant component that is caused by loading the presets. In 18.0 this is indicated separately from loading the data, see http://vespucci.io/help/en/18.0.0%20Release%20notes/#improvements-to-app-startup.

This is otherwise a duplicate of https://github.com/MarcusWolschon/osmeditor4android/issues/1074

**Closed by simonpoole** 2022-09-12 07:18 UTC
