### ISSUE TITLE
Empty undo checkpoint created when re-selecting selected object

### ISSUE THREAD

**Issue by fansanelli** [MarcusWolschon/osmeditor4android#799] opened 2018-11-21 21:18 UTC
## Vespucci Version
11.2.0.0

## Download source
Play Store

## Device (Manufacturer and Model)
LG G6

## Android Version 
8.0.0 STOCK

## Behaviour/Symptoms
when I open Vespucci, if I select any node, I select it again to see properties, then go back without to change anything and press the undo icon, I get notified that a move node has been undone.. But there is nothing to undo...

## Expected Behaviour
Nothing to undo toast

## How to recreate
See above

## Crash dump submitted (no or yes + date)
No

**Comment by simonpoole** [comment] 2018-11-21 21:47
This is a rather old bug, but harmless. 

The problem is that when you re-select an element (you get the same behaviour with a way) we create a checkpoint in case this is the start of a drag (and it is not really possible to create it later). Now if you change the tags of the element that empty checkpoint is simply reused so you don't actually see an superfluous entry, if you don't change anything it remains around but, naturally, doesn't undo anything when undone.

**Comment by simonpoole** [comment] 2018-11-21 22:46
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/6c5b7b0ea09fbbd8e034105035156ab0602149a5

**Closed by simonpoole** 2018-11-21 22:46 UTC
Labels: Defect, Low Priority, UI
