### ISSUE TITLE
OAuth is not enabled for the current API

### ISSUE THREAD

**Issue by davidpnewton** [MarcusWolschon/osmeditor4android#1532] opened 2022-01-10 02:36 UTC
## Vespucci Version
17.0 beta 2

## Download source
Google Play

## Device (Manufacturer and Model)
Samsung Galaxy A70

## Android Version 
11.0

## Behaviour/Symptoms
After upgrading to the beta 2 an hour ago when trying to upload a changeset the following message popped up:

Could not authenticate

If you are using OAuth this is likely a bug, please send a problem report, if you are using login and password (not recommended), please check they are entered correctly.

Upon trying to use the Authorise OAuth menu option the following message pops up:

OAuth is not enabled for the current API

## Expected Behaviour
Upload should occur with OAuth authentication

## How to recreate
Try and upload a changeset

## Crash dump submitted (no or yes + date)
N/A

**Comment by davidpnewton** [comment] 2022-01-10 02:51
Reatarting the software and then re-authenticating appears to sort this out. Still something like this occurring upon version 17 upgrade could cause issues of course.

**Comment by simonpoole** [comment] 2022-01-10 06:42
See http://vespucci.io/help/en/17.0.0%20Release%20notes/

What is probably the issue is that the authorization isn't reset when you try to upload without running the authorization function 1st.

**Comment by simonpoole** [comment] 2022-01-10 12:46
Just tested this (a bit of a pain) and got, as expected a modal with:

`If you are using OAuth, re-authenticate and try again. If you are using login and password (not recommended), please check that they are entered correctly.`

after clicking the `Re-authenticate` button things work as expected. So I'm at a bit of a loss why it behaved differently for you, can you remember from which version you were upgrading?

**Comment by AgusQui** [comment] 2022-01-10 17:03
In my case, when I touch authenticate OAuth or restart OAuth, it tells me the same phrase: OAuth is not enabled for the current API

**Comment by simonpoole** [comment] 2022-01-10 17:58
Can you check the API entry? The name might be the problem, a screenshot would be nice.
We used to match on the URL, but we simply use the name to determine which client keys to use.

**Comment by AgusQui** [comment] 2022-01-10 18:24
![Screenshot_20220110-152247](https://user-images.githubusercontent.com/31557710/148818761-1eddc8bb-2335-410e-afb5-e2df888e3fca.png)

**Comment by simonpoole** [comment] 2022-01-10 18:34
@AgusQui that looks normal. Does exiting, restarting and then immediately running Re-authorize work?

**Comment by AgusQui** [comment] 2022-01-10 19:47
If it worked, the second option, re-authenticate, did not appear previously

![Screenshot_20220110-163813](https://user-images.githubusercontent.com/31557710/148828992-48daed4b-5b73-48a3-8b98-8fe4e53776a9.png)

**Comment by davidpnewton** [comment] 2022-01-10 20:37
> 
> after clicking the `Re-authenticate` button, things work as expected. So I'm at a bit of a loss why it behaved differently for you, can you remember from which version you were upgrading?

Not sure what version it was exactly. This is Google Play Store, so it might have been from 17.0 beta 1 or from the most recent maintenance release of 16.

**Comment by simonpoole** [comment] 2022-01-10 23:13
> If it worked, the second option, re-authenticate, did not appear previously
> 
Yes, that looks like the modal that should appear the 1st time. Re-authorize should then simply work.

**Comment by simonpoole** [comment] 2022-01-11 12:57
@AgusQui what Android version is running on your device?

**Comment by AgusQui** [comment] 2022-01-11 13:10
> @AgusQui what Android version is running on your device?

9

**Comment by simonpoole** [comment] 2022-01-11 13:18
The problem is that I can't recreate the issue locally at all, I always get the modal/dialog that asks you to Re-authorize and that just works.  So the questions is what was different with your and @davidpnewton setup that the key configuration for the API entry couldn't be found.

**Comment by davidpnewton** [comment] 2022-01-18 21:36
Tried switching to the sandbox API. Got a dialogue asking for my username and password to authenticate for OAuth purposes. So what should have happened appears to have happened.

**Comment by simonpoole** [comment] 2022-01-19 15:31
@davidpnewton thanks. Unluckily as mentioned this doesn't seem to be a wide spread issue, nor can I reproduce it or see anything in the code. I'm leaving the issue open for now in case somebody else has the same issue.

**Comment by davidpnewton** [comment] 2022-01-19 18:47
It's also an issue which resolved itself reasonably easily (at least for someone like me). So that further makes it less of a priority.

**Comment by Discostu36** [comment] 2022-01-21 08:51
Reauthorize doesn't work for me. Browser opens with the oath page but is immediately closed with Vespucci giving a DNS error
![Screenshot_20220121-094716_1.png](https://user-images.githubusercontent.com/30999326/150496205-0ece7ef8-81e8-4750-9c70-a924607862aa.png)

**Comment by simonpoole** [comment] 2022-02-04 08:02
17.0 has been released in the mean time without further reports of this. Closing as there isn't really anything actionable now.

**Closed by simonpoole** 2022-02-04 08:02 UTC
Labels: Defect, Medium, Known issue, BETA
