### ISSUE TITLE
Property changing error after merging 2 ways

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1621] opened 2022-04-20 03:29 UTC
Today I had to merge 2 ways on a cemetery. Both had the exactly same tag:

`vehicle:conditional=private @ (Apr-Sep: Mo-Fr 07:30-10:45,16:00-17:45; Apr-Sep: Sa 07:30-17:45; Oct-Mar: Mo-Fr 08:30-10:45; Oct-Mar: Sa 08:30-15:45; PH,Su off)`

(The syntax is correct, I also checked it with the [opening_hours evaluation tool](https://openingh.openstreetmap.de/evaluation_tool/).)

But after merging I got the message "Properties changed" and I was surprised. The result was this value of the tag:

`vehicle:conditional=Oct-Mar: Mo-Fr 08:30-10:45;private @ (Apr-Sep: Mo-Fr 07:30-10:45,16:00-17:45; Apr-Sep: Sa 07:30-17:45; PH,Su off); Oct-Mar: Sa 08:30-15:45`

**This is not correct!** I had to change it back manually.

[Vespucci Version 17.0.6.]

**Comment by simonpoole** [comment] 2022-04-20 08:10
The issue is nearly 100% due to the fact that the original tags were not actually identical (literally, not semantically). To check that I would need at least the id of the merged way.

**Comment by simonpoole** [comment] 2022-04-20 09:52
I think I can see how the issue arises, you are overriding the check for tag equality that normally takes place by using multiselect, in this case we try to maintain correctness of simple lists by merging them. This will however not work for conditional restrictions, or other tags that use semi-colons, but don't have overall list semantics.

**Closed** 2022-04-21 12:36 UTC
Labels: Defect, Medium

**Comment by jajajaneeneenee** [comment] 2022-05-02 13:29
> PS: I've pointed this out to you before: using bold font and exclamation marks is rude. You would get blocked on other projects for just that.

Pardon? Rude? Blocked? I am really stunned ... This sounds for me some kind of aggressive.

It's not meant in a rude way, only to improve readability. I worked mainly as a professional typographer and graphics designer for more than 30 years ... I use bold typefaces it how it's meant for: to emphasize important parts of a text, to structure text and so on – to improve readability. (And in this case simply because it's perhaps not 100% obvious for everyone, that the resulting value is not correct). Nothing else ... It's the equivalent of the voice when you are speaking – your voice is also not always in the same tonality (except when you are a robot). But that does not mean a rude tone.

And why should a single exclamation mark be rude? Perhaps if you make three oft them (!!!). I am aware of this and wouldn't use three exclamation marks in a forum or here, perhaps only in very very rare cases, when it cannot be misunderstood in a bad way. But a single exclamation mark is a normal sign for a text – a slight emphasis, why should this be wrong? Why else does it exist as a sign? If you want, you can really misunderstand everything.

And I really don't remember that you've ever pointed out something like that to me before. If you did, I perhaps did not understand what you mean – then I apologize.

And for the "Needs clarification“ tag: as I wrote ("Both had the exactly same tag"), the tags on the two segements have been 100% identical. I also tried this out before posting this issue, because it's clear that this is the first thing which is important.
