### ISSUE TITLE
White text on a white background

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1656] opened 2022-06-09 05:36 UTC
Description:
---

Some elements are not visible in the dark theme in the History window, as there is white text on a white background

Device info:
---
<table>
<tr><td>App version</td><td>17.1.1.0</td></tr>
<tr><td>App version code</td><td>2102</td></tr>
<tr><td>Android build version</td><td>V13.0.8.0.SKFMIXM</td></tr>
<tr><td>Android release version</td><td>12</td></tr>
<tr><td>Android SDK version</td><td>31</td></tr>
<tr><td>Android build ID</td><td>SKQ1.210908.001 test-keys</td></tr>
<tr><td>Device brand</td><td>Redmi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>sweet</td></tr>
<tr><td>Device model</td><td>M2101K6G</td></tr>
<tr><td>Device product name</td><td>sweet_global</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/mike140"/>mike140</A></td></tr>
</table>

**Comment by mic140** [comment] 2022-06-09 05:38
![IMG_20211213_195651](https://user-images.githubusercontent.com/69987154/172772334-8fd8a3be-3a9f-4028-8623-4c172c38ba37.jpg)

**Comment by mic140** [comment] 2022-06-09 05:40
![Screenshot_2022-06-09-08-31-40-906_de blau android](https://user-images.githubusercontent.com/69987154/172772603-ce49c105-405e-423e-af55-f3b3d55ef56d.jpg)

**Comment by mic140** [comment] 2022-06-09 05:43
![Uploading Screenshot_2022-06-09-08-42-57-921_de.blau.android.jpg…]()

**Comment by mic140** [comment] 2022-06-09 05:43
![Screenshot_2022-06-09-08-42-57-921_de blau android](https://user-images.githubusercontent.com/69987154/172773008-a66f482b-e5b7-43d0-a076-6efb02445afe.jpg)

**Comment by simonpoole** [comment] 2022-06-09 07:41
This is a duplicate of https://github.com/MarcusWolschon/osmeditor4android/issues/1637 I'm closing 1637 as this issue contains more information, but it still remains an upstream issue, and needs to be reported and fixed in  https://github.com/zedlabs/ElementHistoryDialog

**Comment by HolgerJeromin** [comment] 2022-06-09 08:07
This was done https://github.com/zedlabs/ElementHistoryDialog/issues/6

**Comment by mic140** [comment] 2022-08-23 06:50
In version 18.0.0.1 the problem is not solved

**Comment by simonpoole** [comment] 2022-09-02 09:34
> In version 18.0.0.1 the problem is not solved

See https://github.com/zedlabs/ElementHistoryDialog/issues/6#issuecomment-1235283772

**Closed** 2022-10-27 12:00 UTC
Labels: Medium, Upstream issue

**Comment by simonpoole** [comment] 2022-10-27 12:01
The white on white has been fixed, however I'm not convinced that the contrast between the background for changed/deleted/new elements if large enough to be legible in Vespuccis dark mode.
