### ISSUE TITLE
Unable to deactivate "Follow position icon"

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1019] opened 2019-10-19 13:41 UTC
Description:
---

I can set left or right but setting to disabled does not work.

Never knew why this thing exist. Too often I hit it by accident.

Device info:
---
<table>
<tr><td>App version</td><td>14.0.0.2</td></tr>
<tr><td>App version code</td><td>1301</td></tr>
<tr><td>Android build version</td><td>0d27</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PPOS29.114-134-2</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>ocean</td></tr>
<tr><td>Device model</td><td>moto g(7) power</td></tr>
<tr><td>Device product name</td><td>ocean_reteu</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>HolgerJeromin</td></tr>
</table>

**Comment by simonpoole** [comment] 2019-10-19 14:07
In general it is easily the most used button in the whole app, not using it would indicate some rather non-conventional use.

In any case thanks for the report, this was a regression due to a workaround a google bug in 14.0 fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/bb8b493c52cf032cf14630f94f8e112d2f562418

**Closed by simonpoole** 2019-10-19 14:07 UTC

**Comment by HolgerJeromin** [comment] 2019-10-19 15:08
> not using it would indicate some rather non-conventional use.

I often use vespucci not at my position. So hitting it looses my position without a fast way back. But glad I can disable it again. 👍

**Comment by simonpoole** [comment] 2019-10-19 15:51
> 
> 
> > not using it would indicate some rather non-conventional use.
> 
> I often use vespucci not at my position. So hitting it looses my position without a fast way back. But glad I can disable it again. 👍

Note in 14.0 you can go back to the position of the last edit.
