### ISSUE TITLE
Remember more recent distinct sources

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1719] opened 2022-08-09 16:58 UTC
Description:
---

When describing edit I use "survey" or "survey, Geoportal" as sources

Second is used rarely and is often missing from recent sources drop-down.

@matkoniecz

Device info:
---
<table>
<tr><td>App version</td><td>17.1.5.0</td></tr>
<tr><td>App version code</td><td>2106</td></tr>
<tr><td>Android build version</td><td>V11.0.5.0.QDLMIXM</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QKQ1.191002.002.V11.0.5.0.QDLMIXM</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>daisy_sprout</td></tr>
<tr><td>Device model</td><td>Mi A2 Lite</td></tr>
<tr><td>Device product name</td><td>daisy</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/Mateusz Konieczny"/>Mateusz Konieczny</A></td></tr>
</table>

**Comment by simonpoole** [comment] 2022-08-11 07:49
Currently we retain 10 entries, would you want it to be configurable or simply more?

**Comment by matkoniecz** [comment] 2022-08-11 16:59
10 latest or 10 latest distinct ones?

**Comment by simonpoole** [comment] 2022-08-11 22:43
The list has most recently used semantics so by definition these are unique entries.

**Comment by matkoniecz** [comment] 2022-08-17 08:17
Is this list supposed to remove entries at some point? Updates/app restart/app crash?

I quite regularly get random info that Vespucci crashes, mostly on app reopening (I keep submitting reports, sadly I have not found how to reproduce this).

Maybe this entries are lost as result of that?

**Comment by simonpoole** [comment] 2022-08-17 10:03
> Is this list supposed to remove entries at some point? Updates/app restart/app crash?
The oldest not used entry gets removed, it can get zapped now and then.

> I quite regularly get random info that Vespucci crashes, mostly on app reopening (I keep submitting reports, sadly I have not found how to reproduce this).


The crash reports without a heads up, aka opening an issue here, are not that helpful, if you indicate that you've submitted a crash dump I can typically at least tell you what is causing it. For example there's an issue with filenames being too long for Android if you have a GPX or GeoJSON loaded from cloud storage in 17.1 and earlier versions that could cause an error on restart and similar situations, that has been fixed for 18.0, I'm not aware of any other fundamental problems with any of the current versions.

**Comment by matkoniecz** [comment] 2022-08-17 10:10
> The crash reports without a heads up, aka opening an issue here, are not that helpful

Is it worth opening issue if it would have "I submitted crash report with 'purple swan' in description field, Vespucci crashed on switching to it for no clear reason" as sole content?

**Comment by simonpoole** [comment] 2022-08-17 10:31
> > The crash reports without a heads up, aka opening an issue here, are not that helpful
> 
> Is it worth opening issue if it would have "I submitted crash report with 'purple swan' in description field, Vespucci crashed on switching to it for no clear reason" as sole content?

Yes. All the not-actually-a-crash-but something is wrong reports end up in the same category and there is no real way to efficiently find anything there except if I can search for a specific device and time.

And as an illustration: the last report of the kind I could find from you was a week ago and the reason was due to the Logic instance no longer being present in memory after pausing the property editor and resuming it, that normally shouldn't be a problem but IIRC your device has always been rather aggressive in removing things from memory. The issue btw should be less a problem in 18.0.

**Comment by simonpoole** [comment] 2022-09-01 13:13
I just did 10+ uploads with unique comments and source values and things worked as expected, including MRU semantics, I can't see a practical reason for more than 10 entries but if you have some arguments for it I would be glad to hear them.

**Comment by matkoniecz** [comment] 2022-09-01 13:26
Then likely in my case the problem is with history of changes getting lost without known reason

**Comment by simonpoole** [comment] 2022-09-01 13:28
Closing for now, as there is not really any further hardening that can be done outside of avoiding crashes

**Closed by simonpoole** 2022-09-01 13:28 UTC
Labels: Enhancement
