### ISSUE TITLE
Destination lanes: pipe removed

### ISSUE THREAD

**Issue by Discostu36** [MarcusWolschon/osmeditor4android#1072] opened 2020-01-07 06:10 UTC
## Vespucci Version

14.0.9

## Download source

Google Play

## Device (Manufacturer and Model)

Samsung Galaxy A7 (2018)

## Android Version 

9

## Behaviour/Symptoms
I add the following tag to a three lane road:
`destination:lanes=Olympiazentrum;Fernverkehr||
`
I close the tag window and open it again. The tag has been changed to:
`destination:lanes=Olympiazentrum;Fernverkehr|
`

## Expected Behaviour

The added tag should not be altered

## How to recreate

Open [this way](https://www.openstreetmap.org/way/236855734) in Vespucci and follow the steps above.

## Crash dump submitted (no or yes + date)

No

## Any other potentially relevant information

Does not happen with destination:symbol:lanes

**Comment by simonpoole** [comment] 2020-01-07 06:16
That probably happens with any multiple value key with more than 1 empty value at the end, will have a look at it.

**Comment by simonpoole** [comment] 2020-01-07 11:46
More on the issue https://github.com/MarcusWolschon/osmeditor4android/issues/1073

**Comment by simonpoole** [comment] 2020-01-11 12:10
As a clarification the problem is not that existing values are changed, but that it is currently not possible to add a trailing empty value to a multi-select. The only realistic way to fix this is to implement array like semantics for such tags, which will need support in the presets one way or the other. 

The problem is probably harmless as in that it only happens when the last value is empty and while validators will complain functional this shouldn't matter.

**Comment by simonpoole** [comment] 2020-06-03 15:35
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/7784ecd9673c932ee964c1b1dba273bda3661115

**Closed by simonpoole** 2020-06-03 15:35 UTC
Labels: Defect
