### ISSUE TITLE
stop force-filling tag value

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#713] opened 2018-05-26 13:48 UTC
## Vespucci Version
11.0.0-4

## Download source
google play store

## Device (Manufacturer and Model)
Xiaomi Redmi 4

## Android Version 
6.0.1

## Behaviour/Symptoms
On deleting tag value present one tag value is prefilled without giving editor choice to change it

## Expected Behaviour
Dropdown is available but value is not prefilled automatically in this situation.

## How to recreate
see https://vimeo.com/272001704

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information
As workaround on may start deleting in the middle of the word, write a new tag and the delete rest of the former tag.

**Comment by simonpoole** [comment] 2018-05-26 14:51
I suspect this is due to matching with the residential preset which (naturally doesn't have different values for the primary - fixed tag). But the behaviour should clearly be different in the details form.

Note: the proper workaround is to invoke the dropdown by tapping twice (once to focus one to invoke the dropdown) and then simply select the value from the menu.

**Comment by simonpoole** [comment] 2018-05-26 15:01
Root cause: this is a side effect of the Bicycle road preset that has the following entry

`<combo key="highway" text="Highway type" values="residential,service,unclassified,path,cycleway" values_context="Highway" default="residential" />`

Which sets a default value for highway of residential, could likely be fixed with a match="none" but I need to test.

**Comment by simonpoole** [comment] 2018-05-26 17:42
Fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/262e804ca1ec2ea0bec4208e9de6a133100b5298 if you install the preset from the repo the problem should go away.

**Closed by simonpoole** 2018-05-26 17:42 UTC
Labels: BETA, Defect, High Priority
