### ISSUE TITLE
Missing icons at help pages

### ISSUE THREAD

**Issue by kudlav** [MarcusWolschon/osmeditor4android#483] opened 2016-09-23 15:40 UTC
At all help pages are missing images. Instead of them, there are shown links to them.

Samsung Galaxy A3
App: 0.9.8
Android: 5.0.2
![screenshot_2016-09-23-14-04-37](https://cloud.githubusercontent.com/assets/11516259/18791875/b07354c8-81b4-11e6-8dff-a5a5606c2636.png)

**Comment by simonpoole** [comment] 2016-09-24 07:54
Not quite clear why the images were not included in the build, will be fixed in the next update.

**Comment by simonpoole** [comment] 2016-09-24 14:29
Seems as if the gradle plugin suddenly decided not to transform markdown links.

**Comment by simonpoole** [comment] 2016-09-27 13:36
The problem is due to this https://github.com/sirthias/pegdown/issues/114 issue in pegdown, which affects only image links not normal ones which was confusing me.

Simple fix is to add alternate text to all the image links.

**Comment by simonpoole** [comment] 2016-09-27 15:29
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/f1cfd689b19f3c99209d931807873914dd461d67

**Closed by simonpoole** 2016-09-27 15:29 UTC
Labels: Defect, Known issue, Medium Priority, UI
