### ISSUE TITLE
Need to see more of the way's in parentheses stuff

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1823] opened 2022-09-22 04:37 UTC
![Screenshot_20220922-003321_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/191659125-eee9333b-5386-4fcc-9669-6c37e74106d0.jpg)
I wish there was a way to read a little more to the right. Maybe one way would be too abbreviate some of the numbers. E.g., #1234567890 could be written #1…890   etc. 
Or maybe just don't truncate the screen so small, even in landscape mode.

**Comment by simonpoole** [comment] 2022-09-22 05:54
Duplicate of https://github.com/MarcusWolschon/osmeditor4android/issues/1235

**Closed by simonpoole** 2022-09-22 05:54 UTC
