### ISSUE TITLE
stale GPS position when foregrounding Vespucci

### ISSUE THREAD

**Issue by mnalis** [MarcusWolschon/osmeditor4android#475] opened 2016-09-06 12:53 UTC
I use OsmAnd for navigation mostly, and jump in Vespucci when I notice something that needs fixing, switching between them as needed.

But when I switch back to Vespucci, for several seconds current GPS location pointer is stale, pointing to last location where I was before Vespucci was backgrounded. After several seconds it recovers and points to the right (current) location, but in the meantime it is very confusing and leads to erroneous edits sometimes.

Even when vespucci is logging its own GPX track -- track will be drawn correctly (up to the last/current location), but current location pointer won't be shown at the end of logged GPX track (where I am at the moment), but somewhere in the middle of the track (wherever I was when Vespucci was backgrounded).

I would except that pointer always point to current GPS location (and not one from several minutes ago), or at least that the pointer is removed if current location is stale/unknown at the moment.

I'm using Vespucci 0.9.7.1-1147-fdroid. IIRC it used to work normally about two years ago, but is broken for at least few months (probably more)

**Comment by simonpoole** [comment] 2016-09-07 18:52
We would need some more information on device, OS version etc.,  and how you switch between apps. There are multiple different reasons why you might be seeing the issues, the most likely that Vespucci is being started completely new (with exception of the TrackerService if you are recording a track).

**Comment by mnalis** [comment] 2016-09-09 15:27
Device is LG G3 (LG-D855), with Cyanogenmod 12.1. (Although I had same issue on Samsung Galaxy S2 with CM9 before).

First time I indeed open vescucci fresh (either from launcher, or via OsmAnd generated geo: intent), and I can tell it is loading anew because there is "loading data into memory message", painting of background from Bing for a few seconds and then "starting scan for georeferenced photos" message.

However I don't do exit Vespucci (via double back keypress) but background it, and next time I switch to it (either via OsmAnd geo: intent, or via Androids "recent apps" key [square key]) it opens vespucci immedeately without all the "loading" delays", so I assume it is using already loaded version.

However the location in vespucci remains wrong for several seconds, and then autocorrects.

**Comment by mnalis** [comment] 2016-09-09 15:44
Here is how it looks in Vespucci with "current" location in middle of the path, while OsmAnd shows correct current location in NW part of the map. Also attached is SatStat, which shows GPS is working and receiving nicely and updating GPS clock. Vespucci has been stuck in this wrong (obsolete) position for half a minute now. Current position triangle also does rotate to the compass position and Vespucci can move map and edit normally, it is just that current position is wrong.

![screenshot_2016-09-09-17-22-07](https://cloud.githubusercontent.com/assets/156656/18393062/582e043a-76b4-11e6-810f-acd72a68c6cd.png)

![screenshot_2016-09-09-17-21-42](https://cloud.githubusercontent.com/assets/156656/18392996/1ca6b5ba-76b4-11e6-80b8-5fe5940d087a.png)

_
![screenshot_2016-09-09-17-21-07](https://cloud.githubusercontent.com/assets/156656/18392808/840faf1e-76b3-11e6-9813-7e7674a1a350.png)
_

**Comment by mnalis** [comment] 2016-09-09 16:06
I've just noticed another potentially useful piece of information: if I don't  move at all after switching to Vespucci, it won't auto-correct at all (it has remained at wrong position for 10 minutes now - usually I do move after switching to Vespucci, and it automatically corrects after several seconds). When I pressed "goto GPS location" in Vespucci, it updated immedeately to correct position. 

Let me know if I can provide any more information or help otherwise!

**Comment by simonpoole** [comment] 2016-09-09 16:10
In the image above you are not following the GPS position (arrow is filled) so its not a surprise that its not centering on the current position. However I suspect that is not the cuase of your issue since it then would never correct.

**Comment by mnalis** [comment] 2016-09-12 10:00
Yes,  if I touch the arrow its position corrects immediately and map centers on it. 

I understand that if GPS following is disabled the map won't be centered on (filled) arrow, but arrow itself should always point to current location (as it does if Vespucci has been foreground all the time).

Also, it seems the bug does not happen if "follow gps" is enabled before putting Vespucci to background.

Here are exact steps to reproduce the bug (seems to always trigger it for me):

- start the Vespucci
- start GPS track logging and wait for GPS fix
- pan map a little (so "gps following" disengages and arrow becomes filled)
- background the Vespucci (by pressing home button to go to the launcher, or switch to some other app)
- walk an 100 meters or whatever
- stop walking
- bring Vespucci to foreground

The gps track will be shown on the map, but filled arrow will be showing on wrong (old) position. If I do not move nor touch the screen, it will temain at wrong position.

If the arrow is touched, or if I move for few meters, arrow will jump to correct (current) position (at the end of the drawn/logged GPS track)

**Comment by simonpoole** [comment] 2016-09-12 11:04
But this is obviously wanted and expected behaviour (that the setting of "follow gps" is persistent. 

What you -don't- want if you have just panned to a location and by that disabled the auto-GPS centering/follow and quickly start-up a web-browser or whatever and then return to Vespucci, that you loose your previous position.

The changes wrt earlier versions is that it now simply works consistently.

**Comment by mnalis** [comment] 2016-09-12 12:11
Sure, you don't want to lose previous map position if you disabled "follow GPS". I agree and support that. But that is not my problem. My problem is that arrow position on the map is invalid if Vespucci was backgrounded (and correct if it was not), not that the map is not positioned where I want it.

And currenty shown map position is independent of arrow position. 

I do not know if I am explaining clearly... For example, in the picture above, I do NOT want map centered at yellow osmose bug and housenumer 11, as "follow gps" is disabled (which you correctly state means I want map to remain where it was last time). What I DO want is that blue filled arrow moves up and left to the number 11 - where it is supposed to be, as that IS real current location (and it WOULD be there if I didn't background Vespucci)

Does that makes sense?

I cannot see any use case where it would ever be preferred that arrow is shown at invalid (obsolete) location...

**Comment by simonpoole** [comment] 2016-09-14 08:45
In 0.9.7 the blue arrow is the short cut to re-enabling the follow GPS function, it is only useful if it is on-screen (simply marking where you were when you turned it off).

In 0.9.8 the arrow itself is no longer needed for the above and could be placed where the current position is.

**Comment by mnalis** [comment] 2016-09-14 18:17
Hm, don't know about 0.9.8, but in 0.9.7.1.1155-fdroid at least, it does not mark place where you turned off "follow". Even when "follow GPS" is disabled, the blue arrow always shows the current location when you move (while you remain in Vespucci). 

Only difference is when "follow GPS" is enabled, the screen always centers on arrow. And when it is disabled, the map is static and the arrow moves instead.

That seemed logical behaviour to me, so I assumed it is by design (OsmAnd also works like that, showing current location correctly even when you pan the map).

And it works like that while one remains in Vespucci. And when one backgrounds it and comes back and moves a few meters. It only fails to work this way when you background and foreground Vespucci, but don't move enough.

**Comment by simonpoole** [comment] 2016-09-17 20:57
Should be fixed for 0.9.8 in https://github.com/MarcusWolschon/osmeditor4android/commit/16f336bda9967e22ec3583412d8c45157bfec997

**Closed by simonpoole** 2016-09-17 20:57 UTC
