### ISSUE TITLE
Rotate map by compass

### ISSUE THREAD

**Issue by Janokisu** [MarcusWolschon/osmeditor4android#1428] opened 2021-07-27 17:13 UTC
Hi, I would love it if the map rotates according to the compass. 
Whenever I map addresses, I have to take the phone upside down when I walk against the direction and to write I have to turn the phone right side up again.

**Comment by simonpoole** [comment] 2021-07-31 10:41
Duplicate of https://github.com/MarcusWolschon/osmeditor4android/issues/1382

Note this is very unlikely to get implemented as it makes editing (the raison d'être of the app) essentially impossible.

**Closed by simonpoole** 2021-07-31 10:41 UTC
Labels: Enhancement

**Comment by Janokisu** [comment] 2021-07-31 10:52
why "essentially impossible"?
One possibility would be to stop the display from rotating until it is deactivated again as soon as you tap on it and/or a node is active. Or you can only rotate it by 90° at a time. 
Before you say in advance, "that's not possible", you should first provide a test. Then one can still say, it does not work.

**Comment by simonpoole** [comment] 2021-07-31 11:24
You can easily test by turning auto rotation on.

**Comment by Janokisu** [comment] 2021-07-31 11:41
Ok and where can I find this setting in the Vespucci app?

**Comment by ChiefMikeK** [comment] 2021-08-04 07:20
Try this _app_ it has a setting for __headstand__  
`net.mm2d.android.orientationfaker`

**Comment by simonpoole** [comment] 2021-08-04 07:57
I was fettering to device level auto-orientation.

**Comment by Janokisu** [comment] 2021-08-04 15:46
Perhaps I was misunderstood. It is not the display that is to be rotated, but the map. Yes exactly, like Google Maps. If I turn to the north, the map should be aligned to the north and if I turn to the south, the map should be aligned to the south. Actually quite simple. Is there such a function or not? And if not, would it be possible to add one. Maybe as an experiment.

PS: I have lineageOS without Google

**Comment by simonpoole** [comment] 2021-08-04 16:13
> 
> 
> Perhaps I was misunderstood. It is not the display that is to be rotated, but the map. Yes exactly, like Google Maps. If I turn to the north, the map should be aligned to the north and if I turn to the south, the map should be aligned to the south. Actually quite simple. Is there such a function or not? And if not, would it be possible to add one. Maybe as an experiment.

google maps, in fact every "map" application that I know off, osmand, maps.me etc. have pre-calculated geometries, OSM editors in general do not (regardless of target platform), in particular implementing this requires generating and rendering geometries for a roughly 3 times larger area than without rotation. As a side effect it would also complicate all editing operations.   

But as said you simply don't want the map rotating under your fingers, it is a recipe for disaster. and you can simulate what it would be like by using the android orientation change as an emulation of what that would be like. 

And yes you could have some kind of method to freeze the rotation, but again that increases the amount of fiddling required (follow GPS gets turned off when you touch the unlocked screen but even that will go wrong now and then because all the interactions happen asynchronously).

So my take on it, it's a lot of work for something that likely the majority of users would immediately disable. As a sponsored feature maybe worth considering.
