### ISSUE TITLE
hide deprecated features from search results

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#651] opened 2017-12-31 13:46 UTC
I searched "farm", I think that getting farm (deprecated) as one of results is not desirable.

**Comment by simonpoole** [comment] 2018-01-04 21:41
This was a regression due to the new synonym code, fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/89d98d064fe3ba4bff1e5cf847b812153fc38579

**Closed by simonpoole** 2018-01-04 21:41 UTC
