### ISSUE TITLE
taginfo preset search results in problems with poor connection

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#703] opened 2018-05-16 10:48 UTC
## Vespucci Version
Vespucci 11.0 BETA

## Download source
google play store

## Device (Manufacturer and Model)
Xiaomi Redmi 4

## Android Version 
6.0.1

## Behaviour/Symptoms
Search in presets takes extremely long time with poor mobile internet that is enabled

## Expected Behaviour
Search in presets gives local results immediately, taginfo results are appended once response returns

## How to recreate
Enable mobile internet
Search in presets in area with poor mobile internet

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information
As workaround I kept disabling data connection during editing and enabling it during uploads.

**Comment by simonpoole** [comment] 2018-05-16 11:17
What term were you looking for? In principle there shouldn't be so much information transferred that a good or bad connection makes a difference (it does do multiple calls to taginfo so some lag is to be expected).

**Comment by matkoniecz** [comment] 2018-05-16 11:29
> In principle there shouldn't be so much information transferred

I was using it in mountains (Tatra mountains) for example https://www.openstreetmap.org/changeset/58991207#map=16/49.2499/20.0056

In this region connection quickly changes, at times being de facto nonexisting despite phone reporting that mobile internet is available.

> What term were you looking for?

I do not remember, but it should not be any edge case (maybe it had spaces, beyond that nothing weird - just short word or words in ASCII without anything like special signs, UTF-8, empty strings, very long strings, weird UTF-8 like emojis etc)

**Comment by matkoniecz** [comment] 2018-05-16 11:33
I suspect that it was during editing https://www.openstreetmap.org/node/5618872147/history and that I was fighting with #705 - I suspect that I tried to search for things like "open" "opening" or "opening hours".

This is a good guess, but nothing certain.

**Comment by simonpoole** [comment] 2018-05-16 12:46
There is an issue with taginfos keyword search in that while it is possible to limit the number of results returned there is no meaningful way to sort the results so you need to accept all the results in a first pass. That could be a problem with a very common keyword.

**Comment by matkoniecz** [comment] 2018-05-17 13:05
I managed to reproduce it inside building (very low quality mobile internet, search taking several seconds before I killed it).

Would it be useful to upload video of this happening, or is it not going to be helpful?

**Comment by simonpoole** [comment] 2018-05-20 13:48
The issue is roughly clear, the problem is that I don't believe there is a way to only enable something if there is "good" Internet connectivity (it is already disabled if there is none).

**Comment by matkoniecz** [comment] 2018-05-20 15:18
Is

> Search in presets gives local results immediately, taginfo results are appended once response returns

feasible?

**Comment by simonpoole** [comment] 2018-08-28 06:56
https://github.com/MarcusWolschon/osmeditor4android/commit/4163bbec37c7b8ff04f0f3e0b5cfd1a75588caee makes the taginfo search manual

**Closed by simonpoole** 2018-08-28 06:56 UTC
Labels: BETA, Defect, Usability
