### ISSUE TITLE
Downloading relations results in bogus version number

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#595] opened 2017-08-18 05:58 UTC
## Vespucci Version

0.9.9b1293

## Device (Manufacturer and Model)
Xiaomi redmi 4

## Android Version 

6.0.1

## Behaviour/Symptoms

Load way with relation (in my example a hiking route)

Split way

Upload

Receive edit conflict, one solutions leaves relation only on original way (damaging route relation), second causes the same edit conflict

## Expected Behaviour

Route relation is kept with the same role as original on both ways

Turn restriction relations need special handling different that route relation need

No edit conflict should appear without a real edit conflict

## How to recreate

See 2 sections above

## Crash dump submitted (no or yes + date)

No

## Any other potentially relevant information

Report is limited as I am on mobile. Ping me if additional data like location or screenshots is useful.

**Comment by simonpoole** [comment] 2017-08-18 06:19
This is definitely not a general problem (people are splitting ways that are members of relations the whole time, with correct behaviour including special handling of turn restrictions). 

So likely the cause for the problem is the edit conflict. I know it is a bit much to ask, but can you remember what the actual error message was? And point me to the way in question?

**Comment by matkoniecz** [comment] 2017-08-18 07:45
![screenshot_2017-08-18-06-34-20-234_de blau android](https://user-images.githubusercontent.com/899988/29449040-7e119308-83f9-11e7-98a1-a2388e244aee.png)

Message was of this type 
http://www.openstreetmap.org/note/1108336 is place where I messed up relation (hiking route was continuous before I split way and was unable to add new way to relation)

**Comment by matkoniecz** [comment] 2017-08-18 07:46
Real edit conflict is not likely, I reproduce it Munroe times by downloading way, splitting and attempting to upload within seconds.

**Comment by matkoniecz** [comment] 2017-08-18 07:58
Also note that I opt in to beta, so I may be the first to encounter this bug.

**Comment by simonpoole** [comment] 2017-08-18 09:53
The relevant code hasn't changed between 0.9.8 and 0.9.9 so if its a bug it is an old one. Definitely normal splits on ways that are relation members don't cause conflicts on their own so something weird is going on that we currently don't understand (the error message is produced by the API).

**Comment by simonpoole** [comment] 2017-08-18 10:14
A further question: could you force a crash report by going to the debug screen (bottom of the preferences, there is a button at the bottom of the debug information).

**Comment by simonpoole** [comment] 2017-08-18 16:17
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/67fc2c36837fa8b821c06e2aae7b85e9d88e6d9e 

I owe you at least one of your favourite beverage.

Note: you should go back to 0.9.8 till we've pushed out an updated version of 0.9.9.

**Comment by matkoniecz** [comment] 2017-08-18 19:37
> Note: you should go back to 0.9.8 till we've pushed out an updated version of 0.9.9

Is there a better way to do that than leaving beta, uninstalling and installing normal version and reconfiguring app?

> I owe you at least one of your favourite beverage.

And I owe far more for working mobile editor :) I am glad that beta testing was useful.

**Comment by matkoniecz** [comment] 2017-08-18 19:38
Btw, how can I know that updated version was pushed?

**Comment by simonpoole** [comment] 2017-08-18 19:44
In principle google should point it out to you,  In any case downgrading is a bit of a pain and if you can wait and see if we can get the new version out this weekend I would wait. Alternative you can use the version signed with my debug key from google drive but as the key is different in means installing and deinstalling too (and I haven't actually updated that yet but will later this evening). 

I'll give a heads up here in any case.

**Comment by simonpoole** [comment] 2017-08-18 22:46
Build 1294 is with @MarcusWolschon  but he was away at a conference so I'm not sure when he will have time. 

Note you can always install the latest version from https://drive.google.com/drive/folders/0B9pKLmh8s1h8bFI5bGd4VnhYWkk?usp=sharing these builds are signed with my debug key, so you need to sideload them (and zap the config).

**Comment by simonpoole** [comment] 2017-08-19 08:28
@matkoniecz seems as if @MarcusWolschon will earliest be able to update the build on google play on Wednesday.

**Comment by simonpoole** [comment] 2017-08-20 18:27
Just as a final comment on this: we will be moving directly to the release version nect week, again thanks for the testing.

**Closed by simonpoole** 2017-08-20 18:27 UTC
