### ISSUE TITLE
Have Current Location, but no Current Position

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2053] opened 2023-01-25 05:01 UTC
Go to Current Location moves the map to my current location.
But Current Position Info says No Usable Location.

They should both work the same.

If one works even when one is in their house's basement (no GPS) then the other should too. 

Yes, in an open field both will work.

**Comment by simonpoole** [comment] 2023-01-25 09:40
Duplicate of https://github.com/MarcusWolschon/osmeditor4android/issues/2008

**Closed by simonpoole** 2023-01-25 09:40 UTC
