### ISSUE TITLE
shop=car_parts hard to find

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1030] opened 2019-10-31 15:43 UTC
Description:
---

Not found by searching "car parts". Titled "parts" found by "parts" search.

Device info:
---
<table>
<tr><td>App version</td><td>14.0.0.2</td></tr>
<tr><td>App version code</td><td>1301</td></tr>
<tr><td>Android build version</td><td>V10.0.15.0.PDLMIXM</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PKQ1.180917.001.V10.0.15.0.PDLMIXM</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>daisy_sprout</td></tr>
<tr><td>Device model</td><td>Mi A2 Lite</td></tr>
<tr><td>Device product name</td><td>daisy</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by HolgerJeromin** [comment] 2019-11-01 05:52
Why does this issue no reporter in the text?
It is probably @matkoniecz

**Comment by simonpoole** [comment] 2019-11-01 07:16
@HolgerJeromin because the display name wasn't available (aka no connection to the API had previously happened). We don't store this on device and so there will be situations in which we simply don't have it yet.

**Comment by simonpoole** [comment] 2019-11-01 17:07
As to the actual issue  @matkoniecz the issue is that the name of the preset is "Parts" and not "Car parts" so the preference given to exact and partial name matches doesn't work, combined with both "car" and "parts" being both short and common terms, this leads to the correct preset being found but it potentially not making the top 10 results.

There are a couple of ways to address this and I'm experimenting with what works best.

**Comment by simonpoole** [comment] 2019-11-05 08:53
This was fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/36c808ca543d14145422aba08d5d6aee6acfbe7d

**Closed by simonpoole** 2019-11-05 08:53 UTC
