### ISSUE TITLE
Doubling the member count of suspicious relation

### ISSUE THREAD

**Issue by drolbr** [MarcusWolschon/osmeditor4android#859] opened 2019-02-11 11:10 UTC

**Comment by drolbr** [comment] 2019-02-11 11:13
Please have a look at the changeset https://www.openstreetmap.org/changeset/67093992
In that changeset, relation 2632934 has doubled in member count from 21k to 42k.

Would it be possible to make the editor more data error resilient in this regard? I think the relation is already broken before and even more broken afterwards.

**Comment by MaartenDeen** [comment] 2019-02-11 11:32
Offending version with 42k members was 106.
[click on own risk](https://www.openstreetmap.org/api/0.6/relation/2632934/106)

**Comment by simonpoole** [comment] 2019-02-11 14:40
It seems as the initial issue with the relation started with https://www.openstreetmap.org/changeset/65448087 see https://api.openstreetmap.org/api/0.6//relation/2632934/99 (not Vespucci related). 

Has anybody actually asked the user what they were doing at the time?

**Comment by MaartenDeen** [comment] 2019-02-11 14:58
I made a comment in the changeset.

**Comment by simonpoole** [comment] 2019-02-11 15:06
Note: versions 102, 103 and 104 were edited by Vespucci without any negative effects (outside of the Relation still containing 21k members) and version 105 was edited with JOSM (and still contained 21k members), so while the doubling may have been caused by a bug, it just as well could have been operator error.

**Comment by simonpoole** [comment] 2019-02-14 18:34
Fixed on https://github.com/MarcusWolschon/osmeditor4android/commit/40be548cbc11196506932c0ca5b36df60452b1f5

**Closed by simonpoole** 2019-02-14 18:34 UTC
Labels: Needs clarification

**Comment by mueschel** [comment] 2019-02-23 15:52
It looks like at least several hundred relations are affected by this bug. Worldwide there are 600 relations where each member appears on average twice or more. I checked a few and about 50% seem to be due to an edit using Vespucci.

**Comment by simonpoole** [comment] 2019-02-23 16:00
That's not very helpful without providing a list of the relations in question.

**Comment by mueschel** [comment] 2019-02-23 16:15
Hi Simon,
I compiled a list of relations (first link in the document)  and some additional xml files with automatically "corrected" relations that can be loaded into JOSM to check each relation by hand (here about 30-40% are false positives and must not be uploaded). The list contains all suspicious relations, whether they were edited using Vespucci or not.
https://etherpad.gwdg.de/p/OsmRelationsWithDuplicates

**Comment by simonpoole** [comment] 2019-02-23 22:32
@mueschel thanks!

I've done a first pass over the files and roughly half of them were real errors. Most important the  following relations caused conflicts (because the relation has been edited in the mean time):

69917
198370
392856
569604
571064
1107741
1973043
2832326
2908212
3005300
6132056
6171799
6668390
7215270
 
If you could regenerate the files for these relations I could fix them too.

Further

1164087
1174528
5716196

were already done as far as I saw, two of them by you.

Then there where to legit no u turn turn restrictions

6615902
7442968

And then

226799
229600
236871
277441
391094
543191
909082
1152539
1187862
1243214
1255219
1336012
1359102
1553399
1699062
1702681
1702686
1865210
1949128
2102855
2261228
2270070
2320564
2782803
2798458
2849430
2979407
3061205
3182111
3182137
3237948
3323218
3372024
3396604
3478646
3954785
4669053
5149774
5206328
5311104
5324343
5328455
5362433
5378243
5654479
5847730
6016473
6048961
6328343
6422835
6461594
6563723
6663125
6722851
6779756
6810011
6810118
6810119
6886746
6993542
7374734
7422303
7422320
7423594
7519162
7670284
7792957
7811438
7902555
7996343
8046791
8160497
8191338
8208395
8209861
8212096
8212167
8217945
8221116
8238728
8246444
8281529
8432264
8450082
8555287
8592793
8955883
9070132
9163796

which were not edited by Vespucci and had duplicate ways some of them obviously intentional, for others it is unclear (I naturally didn't change these).

**Comment by MaartenDeen** [comment] 2019-02-24 06:45
Are these all relations with < 32767 members? I checked some of them.

**Comment by simonpoole** [comment] 2019-02-24 08:16
Which ones are you referring too? The roughly ~100 that I fixed are now naturally smaller in any case.

**Comment by mueschel** [comment] 2019-02-24 09:41
Hi Simon,
thanks for the cleanup. I checked the relations with conflicts and fixed them as well.

**Comment by simonpoole** [comment] 2019-02-24 09:53
> 
> 
> Hi Simon,
> thanks for the cleanup. I checked the relations with conflicts and fixed them as well.

Note, I would suggest waiting a month or so and then re-running the analysis as people tend to upgrade late or not at all.

**Comment by MaartenDeen** [comment] 2019-02-24 10:31
Simon, of course I only checked relations that  you didn't list. I only checked a few, but none were > 32767 members.

**Comment by simonpoole** [comment] 2019-02-24 10:47
> 
> 
> Simon, of course I only checked relations that you didn't list. I only checked a few, but none were > 32767 members.

I loaded all of the ones I didn't fix and viewed them in JOSMs history. Most of them were small and I didn't remember any of them being extraordinary large. There are some large public transport, well railway routes, where it isn't clear why everything is duplicated, but that is something that IMHO locals need to look at.

**Comment by mueschel** [comment] 2019-02-24 10:48
@MaartenDeen The largest relation in yesterdays planet that met my criteria is 3061205 with 9545 members, and 2247 unique members.

**Comment by mueschel** [comment] 2019-04-22 15:11
> Note, I would suggest waiting a month or so and then re-running the analysis as people tend to upgrade late or not at all.

It's two months now (sorry, forgot to do it earlier). I updated my list and found 400 suspicious relations in the latest planet.  
https://etherpad.gwdg.de/p/OsmRelationsWithDuplicates

I just fixed this relation and noticed something strange.
https://www.openstreetmap.org/relation/27683/history
It seems to got broken in https://www.openstreetmap.org/changeset/69014795
and the changeset claims to be from Vespucci 12.1.8.0 while your fix was implemented earlier.

**Comment by simonpoole** [comment] 2019-04-22 16:13
Yes looking at that I think it tickled a related problem with splitting a closed way that is present twice in the same relation (these people should play lotto), I'm in the process of fixing that which is a bit tricky because of turn restrictions.

**Comment by simonpoole** [comment] 2019-04-24 12:54
@mueschel  I suspect that the underlying issue may have actually not been what I originally fixed, but an error in the undo code, in any case I've fixed that too now (unluckily no actual user has reported an issue, so it is guess work what they were doing at the time).

There was a fair number of conflicts, see https://gist.github.com/simonpoole/f31ed07ba71d7222a236761c39f7979c (I don't know how you generated the files, but I could potentially do it myself if you can provide me with the scripts/whatever).

**Comment by mueschel** [comment] 2019-04-24 13:26
The planet file is already 6 days old now, I'll rerun the analysis tomorrow when the new one is available.

My script is quite simple using osmium and perl:
https://gist.github.com/mueschel/553e37f17078017c27dc7bb86de48835

**Comment by simonpoole** [comment] 2019-04-24 13:48
You can keep a planet up to date real simple with  pyosmium-up-to-date In any case I'll give the script a spin some time later today.

**Comment by simonpoole** [comment] 2019-04-25 07:53
@mueschel I did the remaining ~50 with conflicts yesterday evening. 

BTW slight modification of your process to get meaningful file names instead of standard split names:
`awk -F' ' '{print > $1".opl"}' ../allerrors.txt`
instead of using split.
