### ISSUE TITLE
OSMOSE bugs displaying in German

### ISSUE THREAD

**Issue by CloCkWeRX** [MarcusWolschon/osmeditor4android#393] opened 2016-01-02 06:08 UTC
OSMose gives handy errors... but in German!  I have to retype these into Google translate to understand them,  as the bug text is not selectable.

**Comment by simonpoole** [comment] 2016-01-02 08:54
To understand the context a bit better: you are getting German messages and you can't read German? Normally you should get them in whatever language your device is set to.

**Comment by simonpoole** [comment] 2016-01-03 12:06
@CloCkWeRX and vespucci version, device and Android version would be halpful too.

**Comment by simonpoole** [comment] 2016-01-03 12:17
I've found the (silly) error. Patch asap.

**Comment by simonpoole** [comment] 2016-01-03 13:43
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/3ca266e1046439071a44114aa08b6d7ba978930b
A build with the patch is available from google drive and will be pushed to the play store asap.

**Comment by HolgerJeromin** [comment] 2016-01-03 13:51
having copy and paste is always nice :-)

**Comment by simonpoole** [comment] 2016-01-03 17:08
@HolgerJeromin true but 
* that is an enhancement and not a bug fix (I might open a corresponding issue for the multiple places where it would be "nice" to have C&P support)
* in general C&P of stuff where is hasn't been provided by google is a pain, any in some cases it would seem not to be worth the trouble.

**Comment by CloCkWeRX** [comment] 2016-01-04 02:10
Another variation of this today that was a pain: I've created a bunch of notes with useful URLs for more info in my area. Though they are highlighted in a style of a URL; I can't open them via a click or copy/paste - its not clear if its because the textarea has focus or if its readonly text or what. 

+1 to a new issue for the copy/paste feature and associated other bits and pieces.

**Comment by simonpoole** [comment] 2016-01-05 19:09
Build with fix should be available on google play shortly.

**Closed by simonpoole** 2016-01-05 19:09 UTC
Labels: Defect, FIXED!, High Priority, Known issue
