### ISSUE TITLE
searching "service" in preset search crashes program

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#729] opened 2018-06-12 10:36 UTC
## Vespucci Version

11.0.0-8

## Download source

Google play

## Device (Manufacturer and Model)

Xiaomi Redmi 4

## Android Version 

6.0.2

## Behaviour/Symptoms

Search service, crash

## Expected Behaviour

Shows entries including computer service

## How to recreate

Go to preset search, search "service"

## Crash dump submitted (no or yes + date)

Yes, via in-program send

## Any other potentially relevant information

Is it useful to report both via in-app and GitHub? Or is in-app report good enough?

**Comment by simonpoole** [comment] 2018-06-12 11:12
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/d1e325c8d3fe7e841980e08213492ef4ac7b1f49 (seems as if Android 8 is a bit more lenient about the cause for the crash which is why it didn't turn up in testing).

I'll likely have a test build on google drive later today with this fix.

In general it is always useful to submit both a crash dump and open an issue.

**Closed** 2018-06-12 11:12 UTC
Labels: BETA, Defect, High Priority

**Comment by simonpoole** [comment] 2018-06-18 18:11
The beta on the play store has been updated with the fix.

**Comment by matkoniecz** [comment] 2018-06-18 18:59
I can confirm that it is no longer crashing for me. Thanks!
