### ISSUE TITLE
Consider linking readme badges to source of this data

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#752] opened 2018-07-09 09:55 UTC
On top of the readme there are badges declaring among others that Vespucci has no bugs at all. It is not based on issue tracker (that has [14 open issues with defect label](https://github.com/MarcusWolschon/osmeditor4android/issues?q=is%3Aissue+is%3Aopen+label%3ADefect)) but on some code analyser.

I think that the badges would be far more useful if that code analysis would be linked from badges.

**Comment by simonpoole** [comment] 2018-07-09 12:07
Duplicate of https://github.com/MarcusWolschon/osmeditor4android/issues/742 (the source is sonarqube/cloud which is same code analysis that JOSM uses)

**Closed by simonpoole** 2018-07-09 12:07 UTC

**Comment by matkoniecz** [comment] 2018-07-09 12:49
ops, I somehow managed to miss my own ticket. Sorry.
