### ISSUE TITLE
"Placeholder id's must be unique for created elements"

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1180] opened 2020-06-15 08:44 UTC
Description:
---

Hi. I can no longer upload changes. How do I solve this issue?

Device info:
---
<table>
<tr><td>App version</td><td>14.1.4.0</td></tr>
<tr><td>App version code</td><td>1407</td></tr>
<tr><td>Android build version</td><td>3b59e</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PPIS29.65-51-3</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>doha_n</td></tr>
<tr><td>Device model</td><td>moto g(8) plus</td></tr>
<tr><td>Device product name</td><td>doha_reteu_n</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Gunnarw</td></tr>
</table>

**Comment by simonpoole** [comment] 2020-06-15 09:28
You should save the current edits in an OSC file and attach it to this ticket (I can fix the data manually, and upload its) did you have a crash or something similar before this happened?

**Comment by Tantrumcycles** [comment] 2020-06-16 07:48
No , no crashes. I think I have forgotten to upload some adjustments in another area, on case that can be the problem.
Thanx for helping out .

Gunnar

**Comment by Tantrumcycles** [comment] 2020-06-16 07:50
I now struggle to attach the file 2020-06-16T072518.osc

**Comment by simonpoole** [comment] 2020-06-16 08:04
You might have to rename it to .txt

**Comment by Tantrumcycles** [comment] 2020-06-16 08:45
[2020-06-16T072518.txt](https://github.com/MarcusWolschon/osmeditor4android/files/4785472/2020-06-16T072518.txt)

**Comment by simonpoole** [comment] 2020-06-16 09:22
[2020-06-16T072518-fixed.txt](https://github.com/MarcusWolschon/osmeditor4android/files/4785650/2020-06-16T072518-fixed.txt)

Interesting, there was an exact duplicate of way -7 in the file, not clear at all how that could happen (outside of cosmic rays) . You should be able to re-download the area in question, apply the OSC file and then upload (either in Vespucci or JOSM).

**Comment by simonpoole** [comment] 2020-06-16 11:02
Pro memoria: outside of a memory glitch this shouldn't happen, the map holding the objects only allows one entry per iD, and the method that creates the diff simply iterates over the content.

**Comment by Tantrumcycles** [comment] 2020-06-17 13:19
Yea, a few weird things here. I removed 2 duplicate tracks that was tagged as "floating bridge" even there's no water or bridges nerebye.

And funny you asked about crashing. Have never happened before you asked. But now Vespucci crashes every time I try to uploade the file you corrected.. 
Am I doing something wrong here?
Had to change name back from .txt to .osc the get Vespucci to read, but maybe Ive missed something?

![Screenshot_20200617-062635](https://user-images.githubusercontent.com/66993104/84902884-adcdd500-b0ad-11ea-8a9f-5c1f16edebf6.png)

**Comment by simonpoole** [comment] 2020-06-17 13:25
> 
> And funny you asked about crashing. Have never happened before you asked. But now Vespucci crashes every time I try to uploade the file you corrected..
> Am I doing something wrong here?
> 
As a first step you need to replace the data in your device with a clean download, then apply the OSC file. Have you sent us the crash dumps?

**Comment by Tantrumcycles** [comment] 2020-06-17 13:34
I think so. But in think it worked now. At least the last message now was "uploaded to OSM" 🤞🤪
Anyhow Thanx for all support, and sorry for being a complete good old noob in on this..

**Comment by simonpoole** [comment] 2020-06-17 13:52
Not your fault, such in memory corruption shouldn't happen in the first place (and it is currently completely unclear what actually did occur). But once you have it, you need to replace everything in memory, that's why generating an OSC file, potentially fixing, and reapplying the edits typically will work.

**Comment by simonpoole** [comment] 2020-08-08 16:22
Closing as stale

**Closed by simonpoole** 2020-08-08 16:22 UTC
Labels: Needs clarification
