### ISSUE TITLE
Link to Simple 3D building preset in help does no longer work 

### ISSUE THREAD

**Issue by versat** [MarcusWolschon/osmeditor4android#1031] opened 2019-11-01 19:19 UTC
## Vespucci Version
14.0.3

## Download source
google play store

## Device (Manufacturer and Model)
Samsung M50

## Android Version 
9.0 stock

## Behaviour/Symptoms
Link is dead 

## Expected Behaviour
Link to the latest stable version of the preset opens

## How to recreate
In the preset settings click on help and then on the link to the simple 3D building preset from Kendzi

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information
According to Kendzi the link is dead, he moved to github: https://github.com/kendzi/Simple3dBuildingsPreset/issues/3

**Comment by versat** [comment] 2019-11-01 19:40
I tried to add the preset from the new URL: https://github.com/kendzi/Simple3dBuildingsPreset/releases/download/0.9_2018-05-08/s3db-preset.zip
When downloading the zip file to my smartphone and choose the downloaded file in Vespucci it crashes. I have sent a report at 20:34 (few minutes ago) German time.
When I replace the dead URL with the new one then Vespucci always shows an error message saying that the download failed. But the same URL copied to the Browser works.

**Comment by simonpoole** [comment] 2019-11-01 22:09
Did you configure the download url directly in vespucci or did you download per browser and then tried to open in in the preset configuration (it seems the later, but just to be sure). It it is the later where die you download to (folder/directory).

The issue seems to be a permissions problem of sorts, but currently I can't recreate.

**Comment by versat** [comment] 2019-11-01 22:23
I tried both ways.
Trying to load the file that I have downloaded to the internal memory (default download directory) crashed Vespucci. 

If i replace the wrong URL with the correct one in Vespucci in the preset settings, it says that the download failed. Is it possible to add more details why it exactly failed to the error message?

**Comment by simonpoole** [comment] 2019-11-01 22:33
hmm I just re-tested against android 9 and can't get either variant to fail, the one with crash was when you tried to open the file in the download directory? At least it seems so from the dump.

**Comment by versat** [comment] 2019-11-01 22:55
> hmm I just re-tested against android 9 and can't get either variant to fail, the one with crash was when you tried to open the file in the download directory?

Yes. Maybe I have to reinstall Vespucci. That solved problems with permissions in the past already IIRC.

**Comment by versat** [comment] 2019-11-01 23:03
I have reinstalled Vespucci but it keeps crashing when I try to open the file from the internal SD card. I have sent another report with a dump just few minutes ago.

**Comment by simonpoole** [comment] 2019-11-02 12:10
https://github.com/MarcusWolschon/osmeditor4android/commit/d010f5073fae319b81d13e575a52f608f4291475 contains a fix to the crash however will likely not fix the root cause of why you can't open the files. Is there anything special about how you install vespucci (for example on the SD card?), or any anti-virus/malware programs that might be causing the issue?

**Comment by versat** [comment] 2019-11-02 12:35
The smartphone is very new. Original firmware, no antivirus app or so installed. Everything is installed to the internal SD card. There is absolutely nothing special on the phone that i can think of. I can open the .zip file that crashed Vespucci and all files look fine.

**Comment by simonpoole** [comment] 2019-11-02 13:56
The reason for the question is that while the SAF file picker finds the file, the content resolver can't actually resolve it, which is weird. Excerpt from the log:

```
11-01 23:59:16.008 D/URLListEditActivity(16895): onActivityResult
436	11-01 23:59:16.008 D/de.blau.android.util.al(16895): reading content://com.android.providers.downloads.documents/document/294
437	11-01 23:59:16.021 D/AndroidRuntime(16895): Shutting down VM
438	--------- beginning of crash
439	11-01 23:59:16.024 E/AndroidRuntime(16895): FATAL EXCEPTION: main
440	11-01 23:59:16.024 E/AndroidRuntime(16895): Process: de.blau.android, PID: 16895
441	11-01 23:59:16.024 E/AndroidRuntime(16895): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=9340, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/294 flg=0x43 }} to activity {de.blau.android/de.blau.android.prefs.PresetEditorActivity}: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/294
442	11-01 23:59:16.024 E/AndroidRuntime(16895): at android.app.ActivityThread.deliverResults(ActivityThread.java:4643)
443	11-01 23:59:16.024 E/AndroidRuntime(16895): at android.app.ActivityThread.handleSendResult(ActivityThread.java:4685)
444	11-01 23:59:16.024 E/AndroidRuntime(16895): at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
445	11-01 23:59:16.024 E/AndroidRuntime(16895): at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
446	11-01 23:59:16.024 E/AndroidRuntime(16895): at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
447	11-01 23:59:16.024 E/AndroidRuntime(16895): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1970)
448	11-01 23:59:16.024 E/AndroidRuntime(16895): at android.os.Handler.dispatchMessage(Handler.java:106)
449	11-01 23:59:16.024 E/AndroidRuntime(16895): at android.os.Looper.loop(Looper.java:214)
450	11-01 23:59:16.024 E/AndroidRuntime(16895): at android.app.ActivityThread.main(ActivityThread.java:7156)
451	11-01 23:59:16.024 E/AndroidRuntime(16895): at java.lang.reflect.Method.invoke(Native Method)
452	11-01 23:59:16.024 E/AndroidRuntime(16895): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
453	11-01 23:59:16.024 E/AndroidRuntime(16895): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
454	11-01 23:59:16.024 E/AndroidRuntime(16895): Caused by: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/294
455	11-01 23:59:16.024 E/AndroidRuntime(16895): at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
456	11-01 23:59:16.024 E/AndroidRuntime(16895): at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
457	11-01 23:59:16.024 E/AndroidRuntime(16895): at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
458	11-01 23:59:16.024 E/AndroidRuntime(16895): at android.content.ContentResolver.query(ContentResolver.java:809)
459	11-01 23:59:16.024 E/AndroidRuntime(16895): at android.content.ContentResolver.query(ContentResolver.java:759)
460	11-01 23:59:16.024 E/AndroidRuntime(16895): at android.content.ContentResolver.query(ContentResolver.java:717)
461	11-01 23:59:16.024 E/AndroidRuntime(16895): at de.blau.android.util.al.c(SelectFile.java:265)
462	11-01 23:59:16.024 E/AndroidRuntime(16895): at de.blau.android.util.al.a(SelectFile.java:241)
463	11-01 23:59:16.024 E/AndroidRuntime(16895): at de.blau.android.util.p.a(FileUtil.java:115)
464	11-01 23:59:16.024 E/AndroidRuntime(16895): at de.blau.android.prefs.PresetEditorActivity$5$1.a(PresetEditorActivity.java:611)
465	11-01 23:59:16.024 E/AndroidRuntime(16895): at de.blau.android.util.al.a(SelectFile.java:180)
466	11-01 23:59:16.024 E/AndroidRuntime(16895): at de.blau.android.prefs.URLListEditActivity.onActivityResult(URLListEditActivity.java:538)
467	11-01 23:59:16.024 E/AndroidRuntime(16895): at android.app.Activity.dispatchActivityResult(Activity.java:7791)
468	11-01 23:59:16.024 E/AndroidRuntime(16895): at android.app.ActivityThread.deliverResults(ActivityThread.java:4636)
469	11-01 23:59:16.024 E/AndroidRuntime(16895): ... 11 more
```

**Comment by simonpoole** [comment] 2019-11-02 15:47
Unluckily the M50 is not available here so testing on a real device is tricky, I suspect an A40 is fairly similar and will try on that.

**Comment by simonpoole** [comment] 2019-11-03 14:37
OK, just tried on an A40 with 14.0.3 from the play store and no problem. Just as on all other samsung devices with 9.0 that I've tested, so -something- must be different about your device.

**Comment by simonpoole** [comment] 2019-11-03 15:01
Could you try to download directly in vespucci (that is by specifying the url directly in the preset config), and then manually send another crash dump?

**Comment by versat** [comment] 2019-11-03 17:46
> Could you try to download directly in vespucci (that is by specifying the url directly in the preset config), and then manually send another crash dump? And, could you check if the system app "Download Manager" is enabled or not?

It works if i specify the URL in Vespucci and let Vespucci download the preset. Since the URL has been charged i think this ticket can be marked as fixed. 

Yes. The download manager is installed and enabled / active.

**Comment by simonpoole** [comment] 2019-11-05 10:30
New issue created for tracking the remaining issue. Closing this.

**Closed by simonpoole** 2019-11-05 10:30 UTC
