### ISSUE TITLE
Version 0.9.7.1.1153-fdroid crashes on start

### ISSUE THREAD

**Issue by Self-Perfection** [MarcusWolschon/osmeditor4android#474] opened 2016-09-04 12:32 UTC
```
09-04 14:20:03.855 31353 31353 D AndroidRuntime: Shutting down VM
09-04 14:20:03.870 31353 31353 E ACRA    : ACRA caught a NoSuchFieldError for de.blau.android
09-04 14:20:03.870 31353 31353 E ACRA    : java.lang.NoSuchFieldError: android.support.v4.app.Watson.mFragments
09-04 14:20:03.870 31353 31353 E ACRA    :      at android.support.v4.app.Watson.onCreatePanelMenu(Watson.java:50)
09-04 14:20:03.870 31353 31353 E ACRA    :      at com.actionbarsherlock.ActionBarSherlock.callbackCreateOptionsMenu(ActionBarSherlock.java:560)
09-04 14:20:03.870 31353 31353 E ACRA    :      at com.actionbarsherlock.internal.ActionBarSherlockNative.dispatchCreateOptionsMenu(ActionBarSherlockNative.java:64)
09-04 14:20:03.870 31353 31353 E ACRA    :      at com.actionbarsherlock.app.SherlockFragmentActivity.onCreatePanelMenu(SherlockFragmentActivity.java:164)
09-04 14:20:03.870 31353 31353 E ACRA    :      at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:393)
09-04 14:20:03.870 31353 31353 E ACRA    :      at com.android.internal.policy.impl.PhoneWindow.invalidatePanelMenu(PhoneWindow.java:747)
09-04 14:20:03.870 31353 31353 E ACRA    :      at com.actionbarsherlock.internal.ActionBarSherlockNative.dispatchInvalidateOptionsMenu(ActionBarSherlockNative.java:51)
09-04 14:20:03.870 31353 31353 E ACRA    :      at com.actionbarsherlock.app.SherlockFragmentActivity.invalidateOptionsMenu(SherlockFragmentActivity.java:149)
09-04 14:20:03.870 31353 31353 E ACRA    :      at de.blau.android.Main.triggerMenuInvalidation(Main.java:2662)
09-04 14:20:03.870 31353 31353 E ACRA    :      at de.blau.android.Main.setShowGPS(Main.java:1304)
09-04 14:20:03.870 31353 31353 E ACRA    :      at de.blau.android.Main.onResume(Main.java:569)
09-04 14:20:03.870 31353 31353 E ACRA    :      at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1184)
09-04 14:20:03.870 31353 31353 E ACRA    :      at android.app.Activity.performResume(Activity.java:5082)
09-04 14:20:03.870 31353 31353 E ACRA    :      at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2572)
09-04 14:20:03.870 31353 31353 E ACRA    :      at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2610)
09-04 14:20:03.870 31353 31353 E ACRA    :      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2096)
09-04 14:20:03.870 31353 31353 E ACRA    :      at android.app.ActivityThread.access$600(ActivityThread.java:137)
09-04 14:20:03.870 31353 31353 E ACRA    :      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
09-04 14:20:03.870 31353 31353 E ACRA    :      at android.os.Handler.dispatchMessage(Handler.java:99)
09-04 14:20:03.870 31353 31353 E ACRA    :      at android.os.Looper.loop(Looper.java:137)
09-04 14:20:03.870 31353 31353 E ACRA    :      at android.app.ActivityThread.main(ActivityThread.java:4781)
09-04 14:20:03.870 31353 31353 E ACRA    :      at java.lang.reflect.Method.invokeNative(Native Method)
09-04 14:20:03.870 31353 31353 E ACRA    :      at java.lang.reflect.Method.invoke(Method.java:511)
09-04 14:20:03.870 31353 31353 E ACRA    :      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:805)
09-04 14:20:03.870 31353 31353 E ACRA    :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:568)
09-04 14:20:03.870 31353 31353 E ACRA    :      at dalvik.system.NativeStart.main(Native Method)
09-04 14:20:03.907 31390 31390 I ACRA    : ACRA is enabled for de.blau.android, initializing...

...

09-04 14:20:04.588 30568 30733 W ActivityManager: Exception when unbinding service de.blau.android/.services.TrackerService
09-04 14:20:04.588 30568 30733 W ActivityManager: android.os.DeadObjectException
09-04 14:20:04.588 30568 30733 W ActivityManager:       at android.os.BinderProxy.transact(Native Method)
09-04 14:20:04.588 30568 30733 W ActivityManager:       at android.app.ApplicationThreadProxy.scheduleUnbindService(ApplicationThreadNative.java:825)
09-04 14:20:04.588 30568 30733 W ActivityManager:       at com.android.server.am.ActivityManagerService.removeConnectionLocked(ActivityManagerService.java:13002)
09-04 14:20:04.588 30568 30733 W ActivityManager:       at com.android.server.am.ActivityStack.cleanUpActivityServicesLocked(ActivityStack.java:3981)
09-04 14:20:04.588 30568 30733 W ActivityManager:       at com.android.server.am.ActivityStack.removeActivityFromHistoryLocked(ActivityStack.java:3967)
09-04 14:20:04.588 30568 30733 W ActivityManager:       at com.android.server.am.ActivityManagerService.removeActivityRecordLocked(ActivityManagerService.java:3490)
09-04 14:20:04.588 30568 30733 W ActivityManager:       at com.android.server.am.ActivityManagerService.handleAppDiedLocked(ActivityManagerService.java:3334)
09-04 14:20:04.588 30568 30733 W ActivityManager:       at com.android.server.am.ActivityManagerService.appDiedLocked(ActivityManagerService.java:3518)
09-04 14:20:04.588 30568 30733 W ActivityManager:       at com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied(ActivityManagerService.java:896)
09-04 14:20:04.588 30568 30733 W ActivityManager:       at android.os.BinderProxy.sendDeathNotice(Binder.java:449)
09-04 14:20:04.588 30568 30733 W ActivityManager:       at dalvik.system.NativeStart.run(Native Method)
09-04 14:20:04.595 30568 30733 W ActivityManager: Exception when stopping service de.blau.android/.services.TrackerService
09-04 14:20:04.595 30568 30733 W ActivityManager: android.os.DeadObjectException
09-04 14:20:04.595 30568 30733 W ActivityManager:       at android.os.BinderProxy.transact(Native Method)
09-04 14:20:04.595 30568 30733 W ActivityManager:       at android.app.ApplicationThreadProxy.scheduleStopService(ApplicationThreadNative.java:854)
09-04 14:20:04.595 30568 30733 W ActivityManager:       at com.android.server.am.ActivityManagerService.bringDownServiceLocked(ActivityManagerService.java:12487)
09-04 14:20:04.595 30568 30733 W ActivityManager:       at com.android.server.am.ActivityManagerService.removeConnectionLocked(ActivityManagerService.java:13010)
09-04 14:20:04.595 30568 30733 W ActivityManager:       at com.android.server.am.ActivityStack.cleanUpActivityServicesLocked(ActivityStack.java:3981)
09-04 14:20:04.595 30568 30733 W ActivityManager:       at com.android.server.am.ActivityStack.removeActivityFromHistoryLocked(ActivityStack.java:3967)
09-04 14:20:04.595 30568 30733 W ActivityManager:       at com.android.server.am.ActivityManagerService.removeActivityRecordLocked(ActivityManagerService.java:3490)
09-04 14:20:04.595 30568 30733 W ActivityManager:       at com.android.server.am.ActivityManagerService.handleAppDiedLocked(ActivityManagerService.java:3334)
09-04 14:20:04.595 30568 30733 W ActivityManager:       at com.android.server.am.ActivityManagerService.appDiedLocked(ActivityManagerService.java:3518)
09-04 14:20:04.595 30568 30733 W ActivityManager:       at com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied(ActivityManagerService.java:896)
09-04 14:20:04.595 30568 30733 W ActivityManager:       at android.os.BinderProxy.sendDeathNotice(Binder.java:449)
09-04 14:20:04.595 30568 30733 W ActivityManager:       at dalvik.system.NativeStart.run(Native Method)
09-04 14:20:04.598 31390 31390 D OSM_FS_PROVIDER: Closing tile database
```

Downgrading to 0.9.7.1.1151-fdroid did not help. I had to downgrade to 0.9.7.1.1147-fdroid to get Vespucci working.

Just in case, my device is Jolla with SailfishOS.

**Comment by simonpoole** [comment] 2016-09-04 14:19
We do not not control what is built and distributed via f-droid and we have no way to perform pre-distribution QA. 

That said it seems as if the problem was (in both 1151 and 1153) due to it being build against versions of googles  v4 support library that are incompatible with ABS. I downgraded the version of the support library for 1153 and even further for 1155 on the 2nd in the gradle script that f-droid supposedly uses,, however it hasn't started to be distributed yet.

Note: you can avoid all of the hassle by simply using the signed APK from https://github.com/MarcusWolschon/osmeditor4android/releases which is the same as the APK distributed from the amazon and google stores.

**Comment by Self-Perfection** [comment] 2016-09-04 15:18
I confirm, that [vespuccu-0.9.7r1151.apk.aligned.apk](https://github.com/MarcusWolschon/osmeditor4android/releases/download/0.9.7r1155/vespuccu-0.9.7r1151.apk.aligned.apk) from releases page works on my device.

Are tags 1151 and 1153 built via f-droid known to crash on all devices? If true it is a flaw in F-Droid build/update process. We should not expect F-Droid team to carefully manually test each published release, but at least apks might be checked in automated way in emulator to not crash first 5 seconds after start.

**Comment by simonpoole** [comment] 2016-09-04 15:25
Given that it is likely the same root cause, yes I expect the crashes are device independent. The good news is that for 0.9.8 we are using the same build system as f-droid so at least the probability of such issues should be reduced.

**Comment by krt16s** [comment] 2016-09-05 22:00
I am very sorry for not testing the builds lately. I tended to do that for all apps once... but the number of apps constantly raises, while my personal spare time is getting less and less. Automation might help to some degree, but I don't know how easy that might be. For reference: https://gitlab.com/fdroid/fdroidserver/issues/209.

Again: I am very sorry for any inconveniences.

**Comment by mnalis** [comment] 2016-09-06 11:51
Just to note, 1155 still crashes with f-droid (on LG G3 with CM12.1). 1147 is also last working version from f-droid for me.

While I agree that using github releases instead would probably work, that would be quite inconvenient (replacing automatic f-droid upgrades with manual checking and upgrading -- I guess people would react same if package was removed from google play and people instructed to just go to release page on github and download there instead). Also I think reproducability is important - if open source package cannot be built by others, that hurts everyone.

So I hope some solution could be found so f-droid releases can work again (I'll stay on f-droid 1147 as it works fine for me). And thanks for all the hard work! It really is very appreciated.

**Comment by simonpoole** [comment] 2016-09-06 14:19
@mmalis building with gradle was not really supported with 0.9.7 (aka "you are on your own") . 0.9.8 builds just fine with it so I don't expect any issues when 0.9.8 is released. I'll see if I can finally determine what the last version of the support library that works with ABS really is, seems weird that the error is still there.

**Comment by simonpoole** [comment] 2016-09-06 14:51
Seems as if I might have been engaging in a wild goose chase by trying to fix the issue via changing the version in build.gradle. 

@krt16s are you actually using the v4 support library specified in the dependencies? If not, you should be, not just for the specific current build issue (the v4 support library became incompatible with ABS around 22.2.something), but in general google tends to break things now and then and locking the version of the googles libraries is something which you can't really get around.

**Comment by krt16s** [comment] 2016-09-10 10:53
The issue is still with acra. I disabled the build. Will look at it this weekend.

**Comment by simonpoole** [comment] 2016-09-17 20:52
@krt16s any progress? I'm playinf with the idea of soft releasing 0.9.8 (aka release it on f-droid first) to get around these issues. But that would require not changing the gradle config.

**Comment by krt16s** [comment] 2016-09-18 14:18
There should be a working 1155 in the repo for some days now. I havent fixed the build itself, but greenlit the acra jar for now.

**Comment by simonpoole** [comment] 2016-09-20 06:02
@krt16s I don't believe the 1155 works I'm still getting tons of crash reports because of the support library vs ABS issue.

How much work would it be to get a f-droid build working with 0.9.8 (where all the dependencies are now retrieved with gradle)?

**Comment by krt16s** [comment] 2016-09-20 08:42
1155: Please verify, the APK is at https://f-droid.org/repo/de.blau.android_80.apk. I tested it on my device and it works fine (Android6/CM13, x86). I hope crashreports are from people not using this apk, but the previous one (we cannot auto-remove them from users nor would they get notified about a changed apk).

0.9.8: Are your own repositories (  `maven { url 'https://dl.bintray.com/simonpoole/div' }` and `maven { url 'https://dl.bintray.com/content/simonpoole/osm' }` ) mirrored into jcenter/central? If not, we most likely need to build dependencies served from there from source.. or rely on jitpack or something...

**Comment by Self-Perfection** [comment] 2016-09-20 11:35
I confirm, that [build 1155 from F-Droid](https://f-droid.org/repo/de.blau.android_80.apk) works on my device.

**Comment by simonpoole** [comment] 2016-09-20 20:11
@krt16s I'm in the process of getting them synced to jcenter, however I'm only doing that for the stuff currently directly needed for the build (there's a slightly modified gradle plugin that I need for MD->HTML conversion, but that hasn't been integrated in to the build process yet for a number of reasons).

**Comment by mnalis** [comment] 2016-09-22 10:20
@krt16 I can also confirm, downloading 1155 via provided link now works (while previously original 1155 from f-droid crashed on startup). Thanks! 

Maybe version could be bumped on f-droid to fix it for existing users who are not tracking this bug report (that is, if new f-droid release is not forthcoming relatively soon anyway)?

**Comment by simonpoole** [comment] 2016-10-18 22:44
@krt16s in principle all three packages could be mirrored on to jcenter, however only one has actually been accepted to date. Not clear if some magic sauce is needed of what the issue is, but I hope that it will be resolved in a couple of days.

**Comment by simonpoole** [comment] 2016-11-06 13:19
@krt16s any chance of switching to 0.9.8 in the foreseeable future?

**Comment by Self-Perfection** [comment] 2016-11-06 14:11
@simonpoole [version 0.9.8.1.1205 available on f-droid since 2016-10-25](https://f-droid.org/repository/browse/?fdfilter=vespucci&fdid=de.blau.android).

**Comment by simonpoole** [comment] 2016-11-06 20:46
Ok, seems as if the problem has been resolved, I've tagged an intermediate build to allow f-droid users to catch up a bit with the users that get the app from one of the stores.

**Closed by simonpoole** 2016-11-06 20:46 UTC
Labels: Developer doc

**Comment by krt16s** [comment] 2016-11-06 22:24
Whoops, sorry for not responding. I thought I did reply here, but sometimes you mix up projects -.-. Sorry.
