### ISSUE TITLE
Split equally 

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2043] opened 2023-01-21 05:58 UTC
Currently there is Split:
>Split the selected way. The nodes at the available locations for splitting will have a visible touch area. The "Split" action is only available if the way has more than two nodes...

A new Split Equally function could ask the user for an integer.  Let's say he gave it 8. Well then that way could be split  into 8 equally sized houses etc.!

Sort of like https://wiki.openstreetmap.org/wiki/JOSM/Plugins/Terracer.. 

I.e., given a rectangle, Vespucci could first detect which two sides are the longer sides, and then split them into 8 equally long segments, and then join the nodes on the  other side, and voila, we've got 8 equally spaced houses!.

Vespucci could balk out if there  was other than exactly four sides to start with.

Parallelogram? No problem. You just get 8 baby parallelograms.

Of course it's always best to use the Square function first on the rectangle. The future Help commentary could mention that, along with "Remember to add all tags before splitting."

165 parking spaces, all joined at each corner, voosh... done! Imagine attempting the same thing by current methods... scary.

How about automatic numbering like the JOSM plugin? Yes that could be a bonus...

"Hey, who said I always want to split on the long sides, sometimes I want to split on the short sides for some reason." No problem, a little checkbox could be available to say that to user really wanted to split on the short sides.

"Hey, at the back of each of my 8 houses there's a barbecue grill." Well that's beyond the scope of this feature request. Plus fried foods are bad for you.

**Comment by simonpoole** [comment] 2023-02-01 09:33
Duplicate of https://github.com/MarcusWolschon/osmeditor4android/issues/983

**Closed by simonpoole** 2023-02-01 09:33 UTC
Labels: Enhancement
