### ISSUE TITLE
Add image as background layer?

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1698] opened 2022-07-14 08:03 UTC
Description:
---

Hi!
I made a picture of a map of a camping place with all the buildings and ways on the camping place. Since that data is currently not mapped in OSM I thought I do this by 'just' adding the picture as a background in Vespucci and draw the points and ways by hand. But i cannot find a way to add a picture to the background… Is this not possible? If not, are you aware of any other way/app to do this? I don't think I'm the first one with this problem? 🤔😉
Many thanks! Michael
PS: i will add the picture if there is a thread set up somewhere.

Device info:
---
<table>
<tr><td>App version</td><td>17.1.2.0</td></tr>
<tr><td>App version code</td><td>2103</td></tr>
<tr><td>Android build version</td><td>A528BXXS1CVF1</td></tr>
<tr><td>Android release version</td><td>12</td></tr>
<tr><td>Android SDK version</td><td>31</td></tr>
<tr><td>Android build ID</td><td>SP1A.210812.016.A528BXXS1CVF1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>a52sxq</td></tr>
<tr><td>Device model</td><td>SM-A528B</td></tr>
<tr><td>Device product name</td><td>a52sxqeea</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/DodalerAfenger"/>DodalerAfenger</A></td></tr>
</table>

**Comment by simonpoole** [comment] 2022-07-14 08:33
This is a duplicate of https://github.com/MarcusWolschon/osmeditor4android/issues/1062 and I would continue to suggest to use mapwarper to do this (it isn't as simply as simply adding an image as a layer as you you literally need to be able to warp it to fit which is not trivial).

Note that the plan/map will be copyrighted and you will need permission from the owner to reuse it (that is why I deleted the image you included).

**Closed by simonpoole** 2022-07-14 08:33 UTC
