### ISSUE TITLE
opening_hours in form based tag editor – only first line is visible

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1311] opened 2020-12-20 00:14 UTC
## Vespucci Version
15.1.2

## Download source
Google Play Store

## Device (Manufacturer and Model)
Huawei Honor 7x

## Android Version 
9.1.0

## Behaviour/Symptoms
I don't know if this a intended change, but I don't hope so. I think since version 15.1.0, the form based tag editor only shows the first "line" (rule) of opening_hours (and collection_times). In previous versions of Vespucci, all lines were shown, which is good for a quick check – with a better readability as in the tag editor ("Detail" tab) ... 

Example:
`opening_hours="Mo-Fr 10:00-22:00; Sa 10:00-24:00; PH,Su off"`

=> Only "Mo-Fr 10:00-22:00" is shown in the the form based tag editor, in the normal tag editor you can see the complete values (in a bad way, without line breaks, hard to read ... this could also be improved by the way ... long texts could generally get a bigger input field in the tag editor ...). The opening hours editor itself is perfectly fine (as before), and can of course be used now for a check of the values, but it would be nice to see all lines as before ... it's also confusing now.

It also happens with comma separated rules like:

`collection_times="Mo-Fr 16:00, Sa 10:00"` => only "Mo-Fr 16:00" is shown

2 screenshots:

![opening_hours_form_tag_editor](https://user-images.githubusercontent.com/48966999/102702025-16189180-425e-11eb-84fc-70f7e601a336.jpg)

![opening_hours_tag_editor](https://user-images.githubusercontent.com/48966999/102702037-35172380-425e-11eb-9b8d-9edf21be9755.jpg)

## Expected Behaviour
Alle lines/rules of opening_hours and collection_times should be shown in the form based tag editor.

## How to recreate
obvious

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information
no

**Comment by simonpoole** [comment] 2020-12-20 00:46
It is likely a regression due to the accessibility related improvements.

**Comment by simonpoole** [comment] 2020-12-20 10:07
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/fd4d4e360d344faf927933a9ea51b2e519f3f620

**Closed** 2020-12-27 14:40 UTC
Labels: Defect, FIXED, High Priority
