### ISSUE TITLE
denotation=natural_monument
not found by preset search

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#950] opened 2019-07-24 18:43 UTC
Description:
---

Phone set to Polish 

I selected natural=tree node, went to preset search, searched "pomnik przyrody".

Nothing was found.

Note that denotation=natural_monument is described as "pomnik przyrody" within Vespucci.

Device info:
---
<table>
<tr><td>App version</td><td>13.1.0.0</td></tr>
<tr><td>App version code</td><td>1203</td></tr>
<tr><td>Android build version</td><td>V8.0.3.0.0.MCECNDG</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>prada</td></tr>
<tr><td>Device model</td><td>Redmi 4</td></tr>
<tr><td>Device product name</td><td>prada</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by simonpoole** [comment] 2019-07-24 21:22
Thanks for the report. The bug was caused by not using the translation context when adding to the search index.

Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/425f0cd9254f891d0dc1d396c27d6b2fef492389

**Closed by simonpoole** 2019-07-24 21:22 UTC
