### ISSUE TITLE
no background

### ISSUE THREAD

**Issue by amilopowers** [MarcusWolschon/osmeditor4android#495] opened 2016-11-22 06:39 UTC
Hello
<br />For weeks Vespucci from F-droid and Play store don't lpad any background images. I tried it with stock Android on Angler and Cyanogenmod 13.

**Comment by simonpoole** [comment] 2016-11-22 09:18
Have you sent in a crash report (if there was one)? 

0.9.8 stores the tiles in an sqllite database and no longer as individual files, further it does this on secondary storage if present (see http://vespucci.io/help/en/0.9.8%20Release%20notes/ ). This is likely what is causing your specific issue, please check:

- that Vespucci has the permission to write to external storage

- that there is enough space available on your device

**Comment by amilopowers** [comment] 2016-11-22 09:28
No not possible it has location and storage permission and i have 53 GB free storage on my phone. I use an Android 7 phone.

**Comment by simonpoole** [comment] 2016-11-22 09:50
You didn't answer the question wrt a crash dump or other error message. I'm assuming that you've tried more than one layer?

**Comment by amilopowers** [comment] 2016-11-22 10:13
I first need an app to logcat Vespucci without superuser rights. Any suggestions?

**Comment by simonpoole** [comment] 2016-11-22 12:46
The question was if Vespucci had offered to send a crash dump or has it displayed an error message? In any case getting a copy of the log would be helpful, as what you are experiencing is not a general issue.

**Comment by simonpoole** [comment] 2016-11-23 15:21
Just as an update: I retested against 7.0 on an emulator and was no issue at all.

**Comment by amilopowers** [comment] 2016-11-23 21:23
![screenshot_20161123-222045](https://cloud.githubusercontent.com/assets/9914682/20579149/5e97924e-b1cb-11e6-943e-f3367e65e27c.png)
Thats what ist says but that isn't true. It has access to both.

**Comment by simonpoole** [comment] 2016-11-23 21:38
If you have a file explorer of sorts on your device can you check if you can find the database files?

Typically they will be in a directory named Android/data/de,blau.android/files/databases/

The files should be 

osmaptilesfscache_db.db
and
osmaptilesfscache_db.db-journal

if you've found them (they could be somewhere else as the system generates the location, and storage in Android is one big mess), please report back the actual absolute location and then delete the two files and then start Vespucci.

**Comment by amilopowers** [comment] 2016-11-23 21:47
Folder "files" is empty. I enabled hidden folders and files but there is nothing.

**Comment by simonpoole** [comment] 2016-11-23 21:50
No other places where the DB could be located? If not try deleting the whole de.blau.android tree.

**Comment by amilopowers** [comment] 2016-11-24 01:03
That's the location I meant: /storage/emulated/0/Android/data/de.blau.android/files

I tried to find those two files from the home folder but they don't exist. I have to say that I don't have super user rights.

**Comment by amilopowers** [comment] 2016-11-24 01:08
Debug information doesn't reveal anything I guess:

"Vespucci (F-Droid) 0.9.8r1214-fdroid
Maximum avaliable memory 536870912
Total memory used 60405048
Tile Cache BING usage Size 0 of maximum 67108864 #entries 0
Tile Cache NONE usage Size 0 of maximum 67108864 #entries 0
State file size 45332 last changed 2016-11-24 02:07:35
Bug state file size 248 last changed 2016-11-24 02:07:35
Relations (current/API): 20/0
Ways (current/API): 164/0
Nodes (current/Waynodes/API): 1229/1359/0
Available location providers
passive enabled true
gps enabled true
network enabled true"

**Comment by simonpoole** [comment] 2016-11-24 10:12
Can you try this https://drive.google.com/open?id=0B9pKLmh8s1h8aklmQmd2bHJpRFk APK? Note that it is signed with my debug key so you will have to deinstall the installed regularly signed version.

**Comment by amilopowers** [comment] 2016-11-24 10:55
With that version everything works just fine.

**Comment by simonpoole** [comment] 2016-11-24 11:03
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/7e4dd69a1923c6c71e27a739a2bf4b375d8478c3

**Comment by amilopowers** [comment] 2016-11-24 11:12
Thanks for your fix. Does it come with the next regular update? I know I have to delete your Google Drive version first.

**Comment by simonpoole** [comment] 2016-11-24 11:16
I've already asked Marcus to update the google play build so it should be available latest in a couple of days. F-Droid should be earlier.

The problem is specific to devices without external storage (aka SD-card) but unluckily didn't turn up on such devices that I tested on.

**Comment by simonpoole** [comment] 2016-11-28 08:46
Playstore and github releases updated to 1216

**Comment by simonpoole** [comment] 2016-12-01 17:42
F-droid has updated now too, closing.

**Closed by simonpoole** 2016-12-01 17:42 UTC
Labels: Critical Priority, Defect, FIXED!, Known issue, Usability
