### ISSUE TITLE
Crash when closing Add imagery from OAM

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#887] opened 2019-03-30 20:18 UTC
Description:
---

1. Tools
2. Add imagery from OAM
3. Done
The app crash

Reported 3 times: 30. 3. ~21:15

Device info:
---
<table>
<tr><td>App version</td><td>13.0.0.3</td></tr>
<tr><td>App version code</td><td>1102</td></tr>
<tr><td>Android build version</td><td>A300FUXXU1CRF1</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M.A300FUXXU1CRF1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>a3ulte</td></tr>
<tr><td>Device model</td><td>SM-A300FU</td></tr>
<tr><td>Device product name</td><td>a3ultexx</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>kudlav</td></tr>
</table>

**Comment by kudlav** [comment] 2019-03-30 20:21
Reported by @kudlav

**Comment by simonpoole** [comment] 2019-03-30 20:42
Can you indicate which imagery from OAM causes the issue? It doesn't seem to be a general problem.

**Comment by kudlav** [comment] 2019-03-30 21:00
It seems it's a problem is dialog itself, I don't choose any of imagery.
![2019-03-30-21-51-36_screenRecording](https://user-images.githubusercontent.com/11516259/55281590-e9f50880-5336-11e9-9289-3470247f6970.gif)

**Comment by simonpoole** [comment] 2019-03-30 21:11
Could be caused by one of the entties from the downloaded list for the bounding box as it looks like. Rough coordinates for that area would be good.

**Comment by kudlav** [comment] 2019-03-31 10:00
min: lat 49.2017917 lon 16.5814269
max: lat 49.2039718 lon 16.5835619

**Comment by simonpoole** [comment] 2019-03-31 14:05
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/329cc82b75942c5dd866c139681d323d979c35b8 this was actually simply a weird Android 6ism that was triggered by something entirely unrelated to OAM layers. Thanks for the support.

**Closed by simonpoole** 2019-03-31 14:05 UTC
Labels: BETA, Defect
