### ISSUE TITLE
Workaround to see full name

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2166] opened 2023-03-14 10:32 UTC
![Screenshot_20230314_181409_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/224969547-c273b9d5-9745-4876-bbbb-ea7fce61de10.jpg)
Maybe allow a long press to show the full non-truncated name.
The idea is we keep our finger pressed on the screen. As we move it over each item the full name shows. Then when we are finally happy that it is  the item we want,  we release our finger, thus selecting the item!

**Comment by simonpoole** [comment] 2023-03-14 11:04
Duplicate of https://github.com/MarcusWolschon/osmeditor4android/issues/1235 and related issues, pls stop opening new issues for the same problem.

**Closed by simonpoole** 2023-03-14 11:04 UTC
Labels: Enhancement
