### ISSUE TITLE
no feedback after submitting crash report

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#605] opened 2017-09-24 08:27 UTC
I got "Vespucci crashed or found.. " message. After selecting OK I got no feedback whatever report was submitted (what was made worse by using flaky internet connection, so I was unsure whatever report was successfully submitted).

**Comment by simonpoole** [comment] 2017-09-24 10:35
Did you add an e-mail address or a OSM login name or similar ? Because without there is no way to associate a dump with a specific user without extra information (device, OS and roughly when the crash dump was submitted).

**Comment by matkoniecz** [comment] 2017-09-24 21:47
I am not sure, I triggered it again by uploading note and submitted with "matkoniecz@gmail.com" in text field.

**Comment by simonpoole** [comment] 2017-09-24 21:57
I may have simply missed it will check again tomorrow (I can't filter on the comment field so I need to manually check the reports).

**Comment by simonpoole** [comment] 2017-09-26 21:27
In any case if this related to the Notes issue that should be fixed in the version rolling out now.

**Comment by matkoniecz** [comment] 2017-09-27 19:06
This report is more general - after I submitted crash report I expected confirmation that sending was susccesful.

**Comment by simonpoole** [comment] 2017-09-27 20:34
That would have to be a request to the upstream repo for acra I believe https://github.com/ACRA/acra IIRC ther eis currently no option to provide a confirmation outside of writing your own sender (at that time is imho better spent fixing the root causes).

**Comment by matkoniecz** [comment] 2017-09-27 21:16
> That option exists, if you are using dialog mode: use resDialogOkToast

https://github.com/ACRA/acra/issues/598#issuecomment-332652194

**Comment by simonpoole** [comment] 2017-09-27 21:22
Hmm there is no documentation that indicates that the message from https://github.com/ACRA/acra/wiki/Configuration-A-Z#resdialogoktoast is dependent on the crash dump actually being submitted successfully but I'll test when I'm back from vacation.

**Comment by simonpoole** [comment] 2017-10-08 12:23
As suspected the option doesn't actually provide the required functionality.

**Comment by simonpoole** [comment] 2018-01-06 16:49
In https://github.com/MarcusWolschon/osmeditor4android/commit/3b510623514c421a3896894c30d238563b0080c5 I added the 5.0.0 version of ACRA including text strings to show as confirmation, but it currently doesn't actually seem to work.

**Comment by simonpoole** [comment] 2018-01-29 00:43
This has now been fixed in upstream.

**Closed by simonpoole** 2018-01-29 00:43 UTC
Labels: Enhancement, Upstream issue
