### ISSUE TITLE
Use countryCodes restrictions from name-suggestion-index

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#849] opened 2019-01-24 21:40 UTC
name-suggestion-index has countryCodes data that may specify that some entry is known to exist only in specific countries and it is useless to propose it elsewhere 

Vespucci is not using this data.

See for example https://github.com/osmlab/name-suggestion-index/blob/master/config/canonical.json#L4 (it means that ABANCA bank is Spain-specific institution) or https://github.com/osmlab/name-suggestion-index/blob/master/config/canonical.json#L13999 that specifies that Poczta Polska (Polish Post) exists only in Poland.

## Vespucci Version
12.1.0

## Download source
google play store

## Device (Manufacturer and Model)
Xiaomi Redmi 4

## Android Version 
6.0.1

## Behaviour/Symptoms
Vespucci ignores countryCodes restrictions.

## Expected Behaviour
countryCodes data is used to filter out useless suggestions making it easier to select wanted ones - less typing may be required

## How to recreate
Create node outside Poland, type `name=Ruch` - and note that Ruch brand is proposed despite that it is specified to exist only in Poland

Try the same with ABANCA outside Spain.

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information
I planned to work on adding missing countryCodes restrictions ( https://github.com/osmlab/name-suggestion-index/issues/2201 ) to make Vespucci easier to use. Now it turns out that it would not help.

StreetComplete has well working, fast and tested country detection code existing as a separate project (https://github.com/westnordost/countryboundaries) - maybe it can be reused in Vespucci?

**Comment by simonpoole** [comment] 2019-01-24 23:05
a) making the suggestions country specific goes back to suggestions by me (many years back in the mean time)
b) the Vespucci code already supports a "region" string which was intended to work similar as the facility that has been introduced now (all without discussion - naturally), no real reason why it can't be modified to support the new format
c) we use the countryboundaries library (which in turn is based on country boundaries produced by the JOSM devs), it is slightly abstracted so that we can exchange it when something better comes along. We currently use it to provide country specific speed limits,  left-hand traffic, metric system and so on.

**Comment by matkoniecz** [comment] 2019-01-25 14:46
> making the suggestions country specific goes back to suggestions by me (many years back in the mean time)

Thanks, that was a great idea!

> the Vespucci code already supports a "region" string which was intended to work similar as the facility that has been introduced now

ops, breaking backward compatibility without really good reasons is a poor idea. Well, hopefully at least it means that it will not be too complicated to rewrite relevant code

**Comment by simonpoole** [comment] 2019-01-29 14:55
I just had a look at this. It seems that the countryCodes value is not actually propagated to the index properly and currently remains just in canonical.json this would be easy to fix, but I don't want to end up with yet another fork of a osmlabs/mapbox project, so it really needs to be addressed by Bryan.

**Comment by simonpoole** [comment] 2019-02-22 15:38
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/f0265b2162864534fc35b34e301feba6d17b0a0c

Note as https://github.com/osmlab/name-suggestion-index currently doesn't copy the countryCodes field to the dist output (as discussed in https://github.com/osmlab/name-suggestion-index/issues/2274 ) and would seem to depend a bit too much on wikidata, the facility actually being useful depends on me generating a custom version of the distribution files.

**Closed by simonpoole** 2019-02-22 15:38 UTC
Labels: Enhancement, Medium Priority

**Comment by matkoniecz** [comment] 2019-02-23 11:34
So support is added but it will be not used untill dist output in [name-suggestion-index](https://github.com/osmlab/name-suggestion-index) will be fixed?

**Comment by simonpoole** [comment] 2019-02-23 11:53
No it's currently simply dependent on me not forgetting that I have to generate the file specially or maybe I should change the associated cradle task.

**Comment by matkoniecz** [comment] 2019-03-12 10:54
Good news! I fixed generated file in name-suggestion-index. It can be build with `npm run dist` or by waiting for a release.

I am also working on using OSM data to detect wrong countryCodes (Ireland mistaken with Iran etc) and add missing ones - based on OSM data.

Next version should have far better countryCodes info, hopefully resulting in a noticeably better autocompletion.

**Comment by matkoniecz** [comment] 2019-05-30 19:04
name-suggestion-index releases now contain proper `countryCodes` in released versions so no workarounds should be needed now.

See for example https://raw.githubusercontent.com/osmlab/name-suggestion-index/master/dist/name-suggestions.json
