### ISSUE TITLE
Imagery list initialisation incomplete when starting from intent (was Suddenly only aerial imagery, no maps)

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1953] opened 2022-11-24 02:07 UTC
Today, even though I selected the All radio button, it is just like I only selected aerial imagery. There's no way to see, for instance, Openstreetmap as a background anymore oddly.
![Screenshot_20221123-195759_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/203678068-95c209de-e279-450f-9574-4e7929688932.jpg)

**Comment by jidanni** [comment] 2022-11-24 03:53
Odd. Now it's back with tons of imagery.![Screenshot_20221123-215124_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/203690256-bfe8118d-4833-4fc2-9163-dc1344063395.jpg)

**Comment by simonpoole** [comment] 2022-11-24 09:46
The location where this happened would be helpful.

**Comment by jidanni** [comment] 2022-12-03 07:58
Today it happened after I shared a location from another app to Vespucci, here in Highland Park illinois.

Aerial ima6 was already selected when the share arrived. When I then selected "all maps" still only aerial imagery remained:
![Screenshot_20221203-015218_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/205430989-c89787e1-be7b-4476-8c5c-66166f7dcc1f.jpg)

**Comment by simonpoole** [comment] 2022-12-03 12:20
From your description it isn't clear what exactly the steps were leading up to the issue, did you already have the imagery selection modal/dialog open when you shared the position? Or something else?

**Comment by jidanni** [comment] 2022-12-03 22:25
It seems I can usually reproduce it with:
1. Select the "aerial imagery" radio button (from the three at the top row,) and then close the app.
2. Open the app via remote call, "intent", as above.
3. Now select "all" from the top row of radio buttons.
The list just  stays the same  as it was, as if we didn't select the "all" radio button.

**Comment by simonpoole** [comment] 2022-12-04 17:13
> It seems I can usually reproduce it with:

Worksforme.

Can you check what the (auto-)download radius is set to? See http://vespucci.io/help/en/Advanced%20preferences/#download-radius

You can try to send in some debug information via the Debug screen in the main overflow menu, but that will need to be immediately after the issue occurs to have any hope of capturing enough of the debug log.

**Comment by simonpoole** [comment] 2022-12-04 18:06
> It seems I can usually reproduce it with:
> 
>     1. Select the "aerial imagery" radio button (from the three at the top row,) and then close the app.
Close the app as in, exiting the selection dialog, the layer dialog and then with back press out of the app?
> 
>     2. Open the app via remote call, "intent", as above.
> 
>     3. Now select "all" from the top row of radio buttons.
>        The list just  stays the same  as it was, as if we didn't select the "all" radio button.

**Comment by jidanni** [comment] 2022-12-05 10:15
> Close the app as in

Hitting the Android [||| button](https://www.samsung.com/us/support/answer/ANS00062622/), I mean [Overview button](https://android.stackexchange.com/questions/32697/what-is-the-offical-name-of-the-third-on-screen-button), then X on Vespucci.

**Comment by simonpoole** [comment] 2022-12-05 10:22
> Hitting the Android [||| button](https://www.samsung.com/us/support/answer/ANS00062622/), I mean [Overview button](https://android.stackexchange.com/questions/32697/what-is-the-offical-name-of-the-third-on-screen-button), then X on Vespucci, which then "flies away."

You shouldn't do that (goes for any app), that essentially force closes the app with the related potentially negative consequences.

**Comment by jidanni** [comment] 2022-12-05 11:06
I may in fact might not have closed the app at all. Mainly the "intent:" coming in seemed to knock it too hard...

**Comment by simonpoole** [comment] 2022-12-05 11:17
> I may in fact might not have closed the app at all. Mainly the "intent:" coming in seemed to knock it too hard...

The problem is that the initialization of the in memory list of sources is different when being started via intent than "normally" (then the list is initialized while the splash screen is being shown), force closing the app makes sure that that list is no longer available, and that is why you see the issue. It probably also shows up if you have a situation in which the OS removes the app from memory for other reasons.

**Closed** 2022-12-05 14:55 UTC
Labels: Defect, Minor
