### ISSUE TITLE
Check for emptied relations in more places

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1299] opened 2020-12-04 22:58 UTC
Description:
---

Empty relation created by removing last member from within tag editor of _member_ shows up as changed instead of deleted in the upload dialog

Device info:
---
<table>
<tr><td>App version</td><td>15.0.8.0</td></tr>
<tr><td>App version code</td><td>1509</td></tr>
<tr><td>Android build version</td><td>2011010100</td></tr>
<tr><td>Android release version</td><td>11</td></tr>
<tr><td>Android SDK version</td><td>30</td></tr>
<tr><td>Android build ID</td><td>IN2023_15_201101</td></tr>
<tr><td>Device brand</td><td>OnePlus</td></tr>
<tr><td>Device manufacturer</td><td>OnePlus</td></tr>
<tr><td>Device name</td><td>OnePlus8Pro</td></tr>
<tr><td>Device model</td><td>IN2023</td></tr>
<tr><td>Device product name</td><td>OnePlus8Pro_EEA</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>joihoin</td></tr>
</table>

**Comment by simonpoole** [comment] 2020-12-05 08:33
This is not an error. Emptying a relation doesn't delete it and empty relations are at worst an annoyance, not a serious problem. 

We do check if the user wants to delete a relation by displaying a dialog if the users empties it by selecting the element and then removing all its members. We currently don't do that if the relation is indirectly emptied by removing relation memberships via the member (which would include deleting the member). Noted as a feature request.

**Comment by simonpoole** [comment] 2020-12-05 08:39
See also https://github.com/MarcusWolschon/osmeditor4android/issues/1161

**Comment by johantiden** [comment] 2020-12-05 08:40
Agreed, not very serious but it's a bit confusing when using the app. As a user I assumed that since there was no dialog, there would be a sane default action. As a dev I understand that this may seem like an edge case.

**Comment by simonpoole** [comment] 2020-12-05 09:01
The problem is that it is really undecidable for the app, assume a short route relation with two members has changed and you want to remove those two members and add two different ones back without losing the tags and history of the original route..

**Comment by johantiden** [comment] 2020-12-05 18:06
I agree, it's far from trivial. I guess the only way to find an empty relation is through the upload dialog. In that case it's still fine if the relation is marked as deleted until the user adds something else, which could render the relation "changed" instead of deleted. 

A sort of automatic state based on the state of the relation. There might be other cases which I'm missing. Can't think of any at the moment.

**Comment by simonpoole** [comment] 2020-12-05 18:33
I was just going to reply that you should be able to search for relations with a certain number of members, but seems you can't https://github.com/simonpoole/JosmFilterParser but I'll add that as an extension.

**Comment by simonpoole** [comment] 2020-12-07 21:21
Extension added in https://github.com/simonpoole/JosmFilterParser/commit/5e5631a8ef7c69c8348b4798010d98270c84d90b

**Comment by simonpoole** [comment] 2021-02-04 20:37
More checks added in https://github.com/MarcusWolschon/osmeditor4android/commit/ed2679b6f576fbcd6bd5da332cd405c1fad0d436

https://github.com/MarcusWolschon/osmeditor4android/commit/f1277c6f340f2a0292a6aae0b9b3f618dd72f5b1 adds a Validator check for this so the relations get highlighted in the upload dialog.

**Closed by simonpoole** 2021-02-04 20:37 UTC
Labels: Enhancement
