### ISSUE TITLE
Indicate at all times if the user has some edits pending to upload

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1110] opened 2020-02-29 00:35 UTC
I noticed let the screen looks pretty much the same no matter if you have made some edits or not made any edits.
 in fact you might not really remember that you had some edits that you haven't uploaded yet, until one day you push the download new data button and it asks you "you have edits to upload should you discard them?"

Therefore, in locked mode, and I suppose unlocked mode too, there should be some thing on the screen that was red that turns to blue or, or blue that turns to red, or some little number in red showing the number of pending at its if any.

**Comment by simonpoole** [comment] 2020-02-29 08:50
Duplicate of https://github.com/MarcusWolschon/osmeditor4android/issues/1007

**Closed by simonpoole** 2020-02-29 08:50 UTC
