### ISSUE TITLE
Even distribution of points along a straight line

### ISSUE THREAD

**Issue by davidpnewton** [MarcusWolschon/osmeditor4android#1552] opened 2022-02-06 03:46 UTC
When doing things like mapping parking spaces and other items which occur regularly and evenly along a straight line it is very useful in JOSM to be able to select a number of nodes along a straight way and distribute those nodes along the way with even spacing. The keyboard shortcut for this in JOSM is Shift + B.

Please add similar functionality to Vespucci, available when at least three nodes along a given way are multi-selected.

**Comment by jajajaneeneenee** [comment] 2022-02-19 04:03
I am waiting for such a feature since a long time, too. See my comments in issue #881 (July 2020) and issue #1267 of October 2020 ...

Please note: Not only a distribute nodes feature could be added, also the straighten feature could be improved – at the moment you can only straighten a selected unclosed line (with more than 2 nodes), but not **any** selected nodes (if more than 2 of course) – like the JOSM command “Align Nodes in Line” (shortcut in JOSM: L) is working ... a very basic thing IMO ...

**Comment by simonpoole** [comment] 2022-02-23 08:43
> Please add similar functionality to Vespucci, available when at least three nodes along a given way are multi-selected.

This is not as trivial as it sounds. In particular the geometry of ways in OSM are defined by the nodes, that is moving the nodes changes the geometry . This leads to a large number of situations that need to be handled, for example what to do if a line isn't "straight" (moving a corner node will change the length of the way), closed ways, shared nodes and so on.

**Comment by davidpnewton** [comment] 2022-02-25 15:43
Solution to this? Make running the straighten way routine a pre-requisite for it.

Straighten way is already in the software so there's no additional coding required there and running that routine would automatically make sure that everything is lined up ready for even distribution. That stops corners and closed ways being a problem.

**Comment by simonpoole** [comment] 2023-02-01 09:30
Duplicate of https://github.com/MarcusWolschon/osmeditor4android/issues/1267

**Closed by simonpoole** 2023-02-01 09:30 UTC
Labels: Enhancement
