### ISSUE TITLE
Crashes when hitting "Upload data to OSM server"

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2356] opened 2023-07-23 22:04 UTC
Description:
---

The app crashes everytime I hit the upload button. I've made 502 changes (which is now really frustrating). My changes are still cached, which I at least appreciate, but it doesn't help that I can't push them regardless.

I presume it's not due to the server upload process since that happens after I approve it and add the notes. My guess is it's when it tries to render 500 change items..?

Worse, I can't even export an OSC file. The button is disabled (wth?).

My only other option for uploading appears to be manually copying every change to the browser editor which actually does work.

Now, I get that 500 changes is probably too many. But if so, the app is still at fault for letting me even make that many changes before requiring upload.
If nothing else, PREVENT a user from making more than however many changes it takes to break the app, and require them to upload before proceeding.

Thx. I am also a developer. If this app is open sourced, I would consider contributing, even if just for my own sanity..

Device info:
---
<table>
<tr><td>App version</td><td>17.1.2.0</td></tr>
<tr><td>App version code</td><td>2103</td></tr>
<tr><td>Android build version</td><td>G970U1UES8IWD3</td></tr>
<tr><td>Android release version</td><td>12</td></tr>
<tr><td>Android SDK version</td><td>31</td></tr>
<tr><td>Android build ID</td><td>SP1A.210812.016.G970U1UES8IWD3</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>beyond0q</td></tr>
<tr><td>Device model</td><td>SM-G970U1</td></tr>
<tr><td>Device product name</td><td>beyond0qlteue</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/cs32"/>cs32</A></td></tr>
</table>

**Comment by simonpoole** [comment] 2023-07-24 01:49
There is no limit at 500 changes or similar, you can make 1000s of edits and should be able to upload them.

**Comment by CodeSmith32** [comment] 2023-07-24 02:57
Hey @simonpoole,

Thanks for the response! It's 'cs32'. I didn't realize my report would post on GitHub until I submitted it. Otherwise, I'd probably have signed in to report.

I ended up manually transcribing the changes to the online OSM iD editor, and uploaded it that way.

I then updated the app after that, since it didn't matter if I lost the changes, but to my delight, they actually still held. I cleared them out anyway, since I already submitted them, but before that, I tried starting the process of submitting to see if it worked, and it did *not* crash. So, my guess is, either it was some kind of overload of cache, or it was a bug that has long been fixed.

Either way, I do think this issue can be closed, as it was most likely an issue that has been fixed, or otherwise cannot be tested at this point. But if it does happen again, with the new version, I'll try to do more diagnosis, and report it again.

Thanks!

**Comment by simonpoole** [comment] 2023-07-24 06:36
What is weird, besides the crash, is that saving as an ocs file was disabled as that is only the case when the datastructure holding edits is empty, if that is the case you can't upload either. 

As you can imagine the upload functionality is one of the best exercised bits of the app and something systematically there not working would immediately lead to massive complaints.

Just to be sure when the crash happened, were you asked to submit a crash dump or not?

**Comment by simonpoole** [comment] 2023-07-24 18:48
So I located the crash dump (since I'm on vacation that took a sec), the crash was caused be pre-upload validation, and I'm fairly sure fixed in https://github.com/MarcusWolschon/osmeditor4android/blob/master/CHANGELOG.txt#L257

**Closed by simonpoole** 2023-07-24 18:48 UTC

**Comment by CodeSmith32** [comment] 2023-07-24 19:15
One node ways... Right! Good to hear that issue was fixed. I may have had a single point road or building accidentally while trying to do certain things.

UX suggestions, and possibly the cause:

At one point I was trying really hard to split one building into two. e.g.,

![image](https://github.com/MarcusWolschon/osmeditor4android/assets/21373557/6f03eaf0-39ce-4974-be9f-e2c5126e8c2d)

I would expect to be able to split two points on the way, and then it becomes two separate loops, kind of like in Illustrator. But I tried cut/pasting the points of the one building half, only to find myself with a bunch of disconnected points (really not very helpful). I believe I deleted them all, but maybe not?

At another point (the issue was more likely due to this), I was trying to switch which road name a segment of street belonged to (took me around 10mins...). It was connected to one road way, but should've been connected to the other road way. e.g.:

![image](https://github.com/MarcusWolschon/osmeditor4android/assets/21373557/e4af40ae-4434-4448-a964-4a5bbbf142b4)


I was at first able to split the old road with the scissors, but I couldn't figure out how to join to the new road. Then, after undoing, I think the scissor tool stopped showing up, so I tried using the (useless?) "Extract node" button instead, which didn't help (https://github.com/MarcusWolschon/osmeditor4android/blob/master/svg/extract_node_light.svg). This may have left me with a one-node way?

---

Maybe doing things like this are easier in the new version? I haven't tried yet. But if not, please advise.

**Comment by simonpoole** [comment] 2023-07-24 22:03
> 
> At one point I was trying really hard to split one building into two. e.g.,
> 
There is already a split in to two polygon function that does exactly that.

> 
> At another point (the issue was more likely due to this), I was trying to switch which road name a segment of street belonged to (took me around 10mins...). It was connected to one road way, but should've been connected to the other road way. e.g.:
> 
Split the longer way, then select the segment of that way that you want to merge and the short way, select merge. Note that you will potentially need to fix the tags of the resulting way.

There are other ways to do this, but using the multi-select merge is the most universal.

**Comment by CodeSmith32** [comment] 2023-07-24 23:56
> There is already a split in to two polygon function that does exactly that.

Ok, got it, I just tried it out and, after awhile, I see how it works now.

> Split the longer way, then select the segment of that way that you want to merge and the short way, select merge. Note that you will potentially need to fix the tags of the resulting way.

Again, I also just tried it and finally figured out all the steps involved.

---

A few recommendations now that I understand the source of my struggles using the tools:

I come from a background using Illustrator; so I'm very used to certain behaviors not available here.

I'm used to being able to select two points, hit a button, and then they join. I think, for a single path, turning a line into a polygon, this would be intuitive. It would also be cool to see this for merging two different features, providing the multi-select merge as you mentioned.

I'm also used to being able to pick a single point and break the connection at that point. Now, this already exists here for separately 'joined' features, but I cannot cut a single feature into two pieces (with the scissors) by first selecting the node to cut at. I have to select the whole way, *then* hit the scissors, and *then* pick the single point. But I think it makes a lot of sense to be able to pick a single node and break it, first by separating any 'joined' features at the spot, but afterward by splitting the feature itself (turning a polygon into a line, or a line into two lines).

Also, please forgive me, but *what* is the usefulness of the 'extract node' tool? It's only ever caused me major issues and confusion (like this whole thread...). Maybe it's really useful and I don't understand it, but if I need to add a point, I just hit the green (+) and "Add tagged node". I've never needed to 'extract' a single point from a line or way..

Lastly, minor concern: The first time I used the app, it wasn't very clear to me that the help button from the three-dots menu is contextual. I read the one page and thought that was everything, without realizing there was a hamburger menu with many other articles. Perhaps clarify this?

So, fwiw, that's been my user experience. But I do appreciate your tips which ultimately guided me to understand why the tools work the way they do.

Great app though! Thanks @simonpoole
